// This file is autogenerated from anim/generate_anim.py

const static Int2 positions[] =
{
    vec(2, 2),    // 0
    vec(8, 2),    // 1
    vec(2, 2),    // 2
    vec(2, 2),    // 3
    vec(2, 2),    // 4
    vec(2, 2),    // 5
    vec(3, 2),    // 6
    vec(4, 2),    // 7
    vec(5, 2),    // 8
    vec(6, 2),    // 9
    vec(7, 2),    // 10
    vec(8, 2),    // 11
    vec(7, 2),    // 12
    vec(6, 2),    // 13
    vec(5, 2),    // 14
    vec(4, 2),    // 15
    vec(3, 2),    // 16
    vec(2, 2),    // 17
    vec(2, 2),    // 18
    vec(2, 2),    // 19
    vec(3, 2),    // 20
    vec(4, 2),    // 21
    vec(5, 2),    // 22
    vec(6, 2),    // 23
    vec(7, 2),    // 24
    vec(8, 2),    // 25
    vec(8, 2),    // 26
    vec(8, 2),    // 27
    vec(8, 2),    // 28
    vec(8, 2),    // 29
    vec(7, 2),    // 30
    vec(6, 2),    // 31
    vec(5, 2),    // 32
    vec(4, 2),    // 33
    vec(3, 2),    // 34
    vec(2, 2),    // 35
    vec(2, 2),    // 36
    vec(8, 2),    // 37
    vec(2, 2),    // 38
    vec(8, 2),    // 39
    vec(2, 2),    // 40
    vec(8, 2),    // 41
    vec(2, 2),    // 42
    vec(8, 2),    // 43
    vec(56, 16),    // 44
    vec(56, 16),    // 45
    vec(56, 16),    // 46
    vec(53, 2),    // 47
    vec(59, 2),    // 48
    vec(52, 2),    // 49
    vec(60, 2),    // 50
    vec(54, 2),    // 51
    vec(58, 2),    // 52
    vec(54, 2),    // 53
    vec(58, 2),    // 54
    vec(88, 16),    // 55
    vec(86, 16),    // 56
    vec(84, 16),    // 57
    vec(80, 16),    // 58
    vec(72, 16),    // 59
    vec(64, 16),    // 60
    vec(56, 16),    // 61
    vec(48, 16),    // 62
    vec(40, 16),    // 63
    vec(36, 16),    // 64
    vec(32, 16),    // 65
    vec(30, 16),    // 66
    vec(28, 16),    // 67
    vec(26, 16),    // 68
    vec(25, 16),    // 69
    vec(24, 16),    // 70
    vec(24, 16),    // 71
    vec(26, 16),    // 72
    vec(28, 16),    // 73
    vec(32, 16),    // 74
    vec(40, 16),    // 75
    vec(48, 16),    // 76
    vec(56, 16),    // 77
    vec(64, 16),    // 78
    vec(72, 16),    // 79
    vec(76, 16),    // 80
    vec(80, 16),    // 81
    vec(82, 16),    // 82
    vec(84, 16),    // 83
    vec(86, 16),    // 84
    vec(87, 16),    // 85
    vec(88, 16),    // 86
    vec(2, 2),    // 87
    vec(6, 2),    // 88
    vec(10, 2),    // 89
    vec(2, 2),    // 90
    vec(6, 2),    // 91
    vec(10, 2),    // 92
    vec(2, 2),    // 93
    vec(6, 2),    // 94
    vec(10, 2),    // 95
    vec(2, 2),    // 96
    vec(6, 2),    // 97
    vec(10, 2),    // 98
    vec(2, 2),    // 99
    vec(6, 2),    // 100
    vec(10, 2),    // 101
    vec(88, 16),    // 102
    vec(86, 16),    // 103
    vec(84, 16),    // 104
    vec(80, 16),    // 105
    vec(72, 16),    // 106
    vec(64, 16),    // 107
    vec(56, 16),    // 108
    vec(48, 16),    // 109
    vec(40, 16),    // 110
    vec(36, 16),    // 111
    vec(32, 16),    // 112
    vec(30, 16),    // 113
    vec(28, 16),    // 114
    vec(26, 16),    // 115
    vec(25, 16),    // 116
    vec(24, 16),    // 117
    vec(24, 16),    // 118
    vec(26, 16),    // 119
    vec(28, 16),    // 120
    vec(32, 16),    // 121
    vec(40, 16),    // 122
    vec(48, 16),    // 123
    vec(56, 16),    // 124
    vec(64, 16),    // 125
    vec(72, 16),    // 126
    vec(76, 16),    // 127
    vec(80, 16),    // 128
    vec(82, 16),    // 129
    vec(84, 16),    // 130
    vec(86, 16),    // 131
    vec(87, 16),    // 132
    vec(88, 16),    // 133
    vec(2, 2),    // 134
    vec(3, 2),    // 135
    vec(4, 2),    // 136
    vec(5, 2),    // 137
    vec(6, 2),    // 138
    vec(7, 2),    // 139
    vec(8, 2),    // 140
    vec(9, 2),    // 141
    vec(10, 2),    // 142
    vec(10, 2),    // 143
    vec(6, 2),    // 144
    vec(6, 2),    // 145
    vec(5, 2),    // 146
    vec(4, 2),    // 147
    vec(3, 2),    // 148
    vec(2, 2),    // 149
    vec(2, 2),    // 150
    vec(10, 2),    // 151
    vec(10, 2),    // 152
    vec(9, 2),    // 153
    vec(8, 2),    // 154
    vec(7, 2),    // 155
    vec(6, 2),    // 156
    vec(6, 2),    // 157
    vec(2, 2),    // 158
    vec(2, 2),    // 159
    vec(3, 2),    // 160
    vec(4, 2),    // 161
    vec(5, 2),    // 162
    vec(6, 2),    // 163
    vec(6, 2),    // 164
    vec(6, 2),    // 165
    vec(6, 2),    // 166
    vec(7, 2),    // 167
    vec(8, 2),    // 168
    vec(9, 2),    // 169
    vec(10, 2),    // 170
    vec(10, 2),    // 171
    vec(10, 2),    // 172
    vec(9, 2),    // 173
    vec(8, 2),    // 174
    vec(7, 2),    // 175
    vec(6, 2),    // 176
    vec(5, 2),    // 177
    vec(4, 2),    // 178
    vec(3, 2),    // 179
    vec(2, 2),    // 180
    vec(2, 2),    // 181
    vec(2, 2),    // 182
    vec(8, 2),    // 183
    vec(2, -11),    // 184
    vec(2, -9),    // 185
    vec(2, -7),    // 186
    vec(2, -5),    // 187
    vec(2, -3),    // 188
    vec(2, -1),    // 189
    vec(2, 0),    // 190
    vec(2, 1),    // 191
    vec(2, 1),    // 192
    vec(2, 2),    // 193
    vec(8, -11),    // 194
    vec(8, -9),    // 195
    vec(8, -7),    // 196
    vec(8, -5),    // 197
    vec(8, -3),    // 198
    vec(8, -1),    // 199
    vec(8, 0),    // 200
    vec(8, 1),    // 201
    vec(8, 1),    // 202
    vec(8, 2),    // 203
    vec(2, 3),    // 204
    vec(2, 4),    // 205
    vec(2, 5),    // 206
    vec(2, 6),    // 207
    vec(2, 7),    // 208
    vec(2, 8),    // 209
    vec(2, 9),    // 210
    vec(2, 10),    // 211
    vec(2, 12),    // 212
    vec(2, 16),    // 213
    vec(8, 3),    // 214
    vec(8, 4),    // 215
    vec(8, 5),    // 216
    vec(8, 6),    // 217
    vec(8, 7),    // 218
    vec(8, 8),    // 219
    vec(8, 9),    // 220
    vec(8, 10),    // 221
    vec(8, 12),    // 222
    vec(8, 16),    // 223
    vec(2, -11),    // 224
    vec(2, -10),    // 225
    vec(2, -9),    // 226
    vec(2, -8),    // 227
    vec(2, -7),    // 228
    vec(2, -6),    // 229
    vec(2, -5),    // 230
    vec(2, -4),    // 231
    vec(2, -3),    // 232
    vec(2, -2),    // 233
    vec(2, -1),    // 234
    vec(2, 0),    // 235
    vec(2, 1),    // 236
    vec(2, 1),    // 237
    vec(2, 2),    // 238
    vec(8, -11),    // 239
    vec(8, -10),    // 240
    vec(8, -9),    // 241
    vec(8, -8),    // 242
    vec(8, -7),    // 243
    vec(8, -6),    // 244
    vec(8, -5),    // 245
    vec(8, -4),    // 246
    vec(8, -3),    // 247
    vec(8, -2),    // 248
    vec(8, -1),    // 249
    vec(8, 0),    // 250
    vec(8, 1),    // 251
    vec(8, 1),    // 252
    vec(8, 2),    // 253
    vec(2, 3),    // 254
    vec(2, 4),    // 255
    vec(2, 5),    // 256
    vec(2, 6),    // 257
    vec(2, 7),    // 258
    vec(2, 8),    // 259
    vec(2, 9),    // 260
    vec(2, 10),    // 261
    vec(2, 11),    // 262
    vec(2, 12),    // 263
    vec(2, 13),    // 264
    vec(2, 14),    // 265
    vec(2, 15),    // 266
    vec(2, 15),    // 267
    vec(8, 3),    // 268
    vec(8, 4),    // 269
    vec(8, 5),    // 270
    vec(8, 6),    // 271
    vec(8, 7),    // 272
    vec(8, 8),    // 273
    vec(8, 9),    // 274
    vec(8, 10),    // 275
    vec(8, 11),    // 276
    vec(8, 12),    // 277
    vec(8, 13),    // 278
    vec(8, 14),    // 279
    vec(8, 15),    // 280
    vec(8, 15),    // 281
    vec(2, 2),    // 282
    vec(6, 2),    // 283
    vec(10, 2),    // 284
    vec(2, -11),    // 285
    vec(2, -9),    // 286
    vec(2, -7),    // 287
    vec(2, -5),    // 288
    vec(2, -3),    // 289
    vec(2, -1),    // 290
    vec(2, 0),    // 291
    vec(2, 1),    // 292
    vec(2, 1),    // 293
    vec(2, 2),    // 294
    vec(6, -11),    // 295
    vec(6, -9),    // 296
    vec(6, -7),    // 297
    vec(6, -5),    // 298
    vec(6, -3),    // 299
    vec(6, -1),    // 300
    vec(6, 0),    // 301
    vec(6, 1),    // 302
    vec(6, 1),    // 303
    vec(6, 2),    // 304
    vec(10, -11),    // 305
    vec(10, -9),    // 306
    vec(10, -7),    // 307
    vec(10, -5),    // 308
    vec(10, -3),    // 309
    vec(10, -1),    // 310
    vec(10, 0),    // 311
    vec(10, 1),    // 312
    vec(10, 1),    // 313
    vec(10, 2),    // 314
    vec(2, 3),    // 315
    vec(2, 4),    // 316
    vec(2, 5),    // 317
    vec(2, 6),    // 318
    vec(2, 7),    // 319
    vec(2, 8),    // 320
    vec(2, 9),    // 321
    vec(2, 10),    // 322
    vec(2, 12),    // 323
    vec(2, 16),    // 324
    vec(6, 3),    // 325
    vec(6, 4),    // 326
    vec(6, 5),    // 327
    vec(6, 6),    // 328
    vec(6, 7),    // 329
    vec(6, 8),    // 330
    vec(6, 9),    // 331
    vec(6, 10),    // 332
    vec(6, 12),    // 333
    vec(6, 16),    // 334
    vec(10, 3),    // 335
    vec(10, 4),    // 336
    vec(10, 5),    // 337
    vec(10, 6),    // 338
    vec(10, 7),    // 339
    vec(10, 8),    // 340
    vec(10, 9),    // 341
    vec(10, 10),    // 342
    vec(10, 12),    // 343
    vec(10, 16),    // 344
    vec(2, -11),    // 345
    vec(2, -10),    // 346
    vec(2, -9),    // 347
    vec(2, -8),    // 348
    vec(2, -7),    // 349
    vec(2, -6),    // 350
    vec(2, -5),    // 351
    vec(2, -4),    // 352
    vec(2, -3),    // 353
    vec(2, -2),    // 354
    vec(2, -1),    // 355
    vec(2, 0),    // 356
    vec(2, 1),    // 357
    vec(2, 1),    // 358
    vec(2, 2),    // 359
    vec(6, -11),    // 360
    vec(6, -10),    // 361
    vec(6, -9),    // 362
    vec(6, -8),    // 363
    vec(6, -7),    // 364
    vec(6, -6),    // 365
    vec(6, -5),    // 366
    vec(6, -4),    // 367
    vec(6, -3),    // 368
    vec(6, -2),    // 369
    vec(6, -1),    // 370
    vec(6, 0),    // 371
    vec(6, 1),    // 372
    vec(6, 1),    // 373
    vec(6, 2),    // 374
    vec(10, -11),    // 375
    vec(10, -10),    // 376
    vec(10, -9),    // 377
    vec(10, -8),    // 378
    vec(10, -7),    // 379
    vec(10, -6),    // 380
    vec(10, -5),    // 381
    vec(10, -4),    // 382
    vec(10, -3),    // 383
    vec(10, -2),    // 384
    vec(10, -1),    // 385
    vec(10, 0),    // 386
    vec(10, 1),    // 387
    vec(10, 1),    // 388
    vec(10, 2),    // 389
    vec(2, 3),    // 390
    vec(2, 4),    // 391
    vec(2, 5),    // 392
    vec(2, 6),    // 393
    vec(2, 7),    // 394
    vec(2, 8),    // 395
    vec(2, 9),    // 396
    vec(2, 10),    // 397
    vec(2, 11),    // 398
    vec(2, 12),    // 399
    vec(2, 13),    // 400
    vec(2, 14),    // 401
    vec(2, 15),    // 402
    vec(2, 15),    // 403
    vec(6, 3),    // 404
    vec(6, 4),    // 405
    vec(6, 5),    // 406
    vec(6, 6),    // 407
    vec(6, 7),    // 408
    vec(6, 8),    // 409
    vec(6, 9),    // 410
    vec(6, 10),    // 411
    vec(6, 11),    // 412
    vec(6, 12),    // 413
    vec(6, 13),    // 414
    vec(6, 14),    // 415
    vec(6, 15),    // 416
    vec(6, 15),    // 417
    vec(10, 3),    // 418
    vec(10, 4),    // 419
    vec(10, 5),    // 420
    vec(10, 6),    // 421
    vec(10, 7),    // 422
    vec(10, 8),    // 423
    vec(10, 9),    // 424
    vec(10, 10),    // 425
    vec(10, 11),    // 426
    vec(10, 12),    // 427
    vec(10, 13),    // 428
    vec(10, 14),    // 429
    vec(10, 15),    // 430
    vec(10, 15),    // 431
    vec(2, 2),    // 432
    vec(8, 2),    // 433
    vec(2, 2),    // 434
    vec(8, 2),    // 435
    vec(2, 2),    // 436
    vec(6, 2),    // 437
    vec(10, 2),    // 438
    vec(2, 2),    // 439
    vec(6, 2),    // 440
    vec(10, 2),    // 441
};

const static AnimObjData animObjData[] =
{
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[0] },    // AnimType_NotWord 0
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[1] },    // AnimType_NotWord 1
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[2] },    // AnimType_SlideL 2
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 7, &positions[12] },    // AnimType_SlideL 3
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 7, &positions[19] },    // AnimType_SlideR 4
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[26] },    // AnimType_SlideR 5
    { &Tile2Glow, &Tile2Blank, &Tile2MetaGlow, 0, Layer_BG0, 0, 1, &positions[36] },    // AnimType_OldWord 6
    { &Tile2Glow, &Tile2Blank, &Tile2MetaGlow, 0, Layer_BG0, 0, 1, &positions[37] },    // AnimType_OldWord 7
    { &Tile2Glow, &Tile2Blank, &Tile2MetaGlow, 0, Layer_BG0, 0, 1, &positions[38] },    // AnimType_NewWord 8
    { &Tile2Glow, &Tile2Blank, &Tile2MetaGlow, 0, Layer_BG0, 0, 1, &positions[39] },    // AnimType_NewWord 9
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[40] },    // AnimType_EndofRound 10
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[41] },    // AnimType_EndofRound 11
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[42] },    // AnimType_Shuffle 12
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[43] },    // AnimType_Shuffle 13
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[44] },    // AnimType_HintBarAppear 14
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[46] },    // AnimType_HintBarDisappear 15
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[55] },    // AnimType_HintSlideL 16
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[71] },    // AnimType_HintSlideR 17
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[87] },    // AnimType_NotWord 18
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[88] },    // AnimType_NotWord 19
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[89] },    // AnimType_NotWord 20
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[134] },    // AnimType_SlideL 21
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 7, &positions[144] },    // AnimType_SlideL 22
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 7, &positions[151] },    // AnimType_SlideL 23
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 7, &positions[158] },    // AnimType_SlideR 24
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 7, &positions[165] },    // AnimType_SlideR 25
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[172] },    // AnimType_SlideR 26
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[90] },    // AnimType_OldWord 27
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[91] },    // AnimType_OldWord 28
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[92] },    // AnimType_OldWord 29
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[93] },    // AnimType_NewWord 30
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[94] },    // AnimType_NewWord 31
    { &Tile3Glow, &Tile3Blank, &Tile3MetaGlow, 0, Layer_BG0, 0, 1, &positions[95] },    // AnimType_NewWord 32
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[96] },    // AnimType_EndofRound 33
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[97] },    // AnimType_EndofRound 34
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[98] },    // AnimType_EndofRound 35
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[99] },    // AnimType_Shuffle 36
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[100] },    // AnimType_Shuffle 37
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[101] },    // AnimType_Shuffle 38
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[102] },    // AnimType_HintSlideL 39
    { 0, 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[118] },    // AnimType_HintSlideR 40
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[184] },    // AnimType_NormalTilesEnter 41
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[194] },    // AnimType_NormalTilesEnter 42
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[204] },    // AnimType_NormalTilesExit 43
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 10, &positions[214] },    // AnimType_NormalTilesExit 44
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 15, &positions[224] },    // AnimType_MetaTilesEnter 45
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 15, &positions[239] },    // AnimType_MetaTilesEnter 46
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[182] },    // AnimType_MetaTilesShow 47
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[183] },    // AnimType_MetaTilesShow 48
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 14, &positions[254] },    // AnimType_MetaTilesExit 49
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 14, &positions[268] },    // AnimType_MetaTilesExit 50
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[285] },    // AnimType_NormalTilesEnter 51
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[295] },    // AnimType_NormalTilesEnter 52
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[305] },    // AnimType_NormalTilesEnter 53
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[315] },    // AnimType_NormalTilesExit 54
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[325] },    // AnimType_NormalTilesExit 55
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 10, &positions[335] },    // AnimType_NormalTilesExit 56
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 15, &positions[345] },    // AnimType_MetaTilesEnter 57
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 15, &positions[360] },    // AnimType_MetaTilesEnter 58
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 15, &positions[375] },    // AnimType_MetaTilesEnter 59
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[282] },    // AnimType_MetaTilesShow 60
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[283] },    // AnimType_MetaTilesShow 61
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[284] },    // AnimType_MetaTilesShow 62
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 14, &positions[390] },    // AnimType_MetaTilesExit 63
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 14, &positions[404] },    // AnimType_MetaTilesExit 64
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 14, &positions[418] },    // AnimType_MetaTilesExit 65
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[432] },    // AnimType_MetaTilesReveal 66
    { &Tile2Meta, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[433] },    // AnimType_MetaTilesReveal 67
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[434] },    // AnimType_NormalTilesReveal 68
    { &Tile2, &Tile2Blank, &Tile2Meta, 0, Layer_BG0, 0, 1, &positions[435] },    // AnimType_NormalTilesReveal 69
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[436] },    // AnimType_MetaTilesReveal 70
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[437] },    // AnimType_MetaTilesReveal 71
    { &Tile3Meta, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[438] },    // AnimType_MetaTilesReveal 72
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[439] },    // AnimType_NormalTilesReveal 73
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[440] },    // AnimType_NormalTilesReveal 74
    { &Tile3, &Tile3Blank, &Tile3Meta, 0, Layer_BG0, 0, 1, &positions[441] },    // AnimType_NormalTilesReveal 75
};

const static AnimData animData[] =
{
    { 1.f, true, 0, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 0, &animObjData[0]},    // AnimType_SlideL
    { 0.5f, false, 0, &animObjData[0]},    // AnimType_SlideR
    { 1.f, true, 0, &animObjData[0]},    // AnimType_OldWord
    { 1.5f, false, 0, &animObjData[0]},    // AnimType_NewWord
    { 1.f, true, 0, &animObjData[0]},    // AnimType_EndofRound
    { 0.5f, true, 0, &animObjData[0]},    // AnimType_Shuffle
    { 1.f, false, 1, &animObjData[14]},    // AnimType_HintBarAppear
    { 3.f, true, 0, &animObjData[0]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[15]},    // AnimType_HintBarDisappear
    { 3.f, false, 0, &animObjData[0]},    // AnimType_HintWindUpSlide
    { 1.f, true, 0, &animObjData[0]},    // AnimType_HintSlideL
    { 1.f, true, 0, &animObjData[0]},    // AnimType_HintSlideR
    { 0.5f, false, 0, &animObjData[0]},    // AnimType_NormalTilesEnter
    { 0.5f, false, 0, &animObjData[0]},    // AnimType_NormalTilesExit
    { 1.1f, false, 0, &animObjData[0]},    // AnimType_MetaTilesEnter
    { 0.66f, false, 0, &animObjData[0]},    // AnimType_MetaTilesShow
    { 1.1f, false, 0, &animObjData[0]},    // AnimType_MetaTilesExit
    { 1.1f, false, 0, &animObjData[0]},    // AnimType_MetaTilesReveal
    { 1.1f, false, 0, &animObjData[0]},    // AnimType_NormalTilesReveal
    { 1.f, true, 2, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 2, &animObjData[2]},    // AnimType_SlideL
    { 0.5f, false, 2, &animObjData[4]},    // AnimType_SlideR
    { 1.f, true, 2, &animObjData[6]},    // AnimType_OldWord
    { 1.5f, false, 2, &animObjData[8]},    // AnimType_NewWord
    { 1.f, true, 2, &animObjData[10]},    // AnimType_EndofRound
    { 0.5f, true, 2, &animObjData[12]},    // AnimType_Shuffle
    { 1.f, false, 1, &animObjData[14]},    // AnimType_HintBarAppear
    { 3.f, true, 0, &animObjData[0]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[15]},    // AnimType_HintBarDisappear
    { 3.f, false, 0, &animObjData[0]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[16]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[17]},    // AnimType_HintSlideR
    { 0.5f, false, 2, &animObjData[41]},    // AnimType_NormalTilesEnter
    { 0.5f, false, 2, &animObjData[43]},    // AnimType_NormalTilesExit
    { 1.1f, false, 2, &animObjData[45]},    // AnimType_MetaTilesEnter
    { 0.66f, false, 2, &animObjData[47]},    // AnimType_MetaTilesShow
    { 1.1f, false, 2, &animObjData[49]},    // AnimType_MetaTilesExit
    { 1.1f, false, 2, &animObjData[66]},    // AnimType_MetaTilesReveal
    { 1.1f, false, 2, &animObjData[68]},    // AnimType_NormalTilesReveal
    { 1.f, true, 3, &animObjData[18]},    // AnimType_NotWord
    { 0.5f, false, 3, &animObjData[21]},    // AnimType_SlideL
    { 0.5f, false, 3, &animObjData[24]},    // AnimType_SlideR
    { 1.f, true, 3, &animObjData[27]},    // AnimType_OldWord
    { 1.5f, false, 3, &animObjData[30]},    // AnimType_NewWord
    { 1.f, true, 3, &animObjData[33]},    // AnimType_EndofRound
    { 0.5f, true, 3, &animObjData[36]},    // AnimType_Shuffle
    { 1.f, false, 1, &animObjData[14]},    // AnimType_HintBarAppear
    { 3.f, true, 0, &animObjData[0]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[15]},    // AnimType_HintBarDisappear
    { 3.f, false, 0, &animObjData[0]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[39]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[40]},    // AnimType_HintSlideR
    { 0.5f, false, 3, &animObjData[51]},    // AnimType_NormalTilesEnter
    { 0.5f, false, 3, &animObjData[54]},    // AnimType_NormalTilesExit
    { 1.1f, false, 3, &animObjData[57]},    // AnimType_MetaTilesEnter
    { 0.66f, false, 3, &animObjData[60]},    // AnimType_MetaTilesShow
    { 1.1f, false, 3, &animObjData[63]},    // AnimType_MetaTilesExit
    { 1.1f, false, 3, &animObjData[70]},    // AnimType_MetaTilesReveal
    { 1.1f, false, 3, &animObjData[73]},    // AnimType_NormalTilesReveal
};

