// This file is autogenerated from anim/generate_anim.py

const static Vec2 positions[] =
{
    Vec2(2, 2),    // 0
    Vec2(8, 2),    // 1
    Vec2(2, 2),    // 2
    Vec2(2, 2),    // 3
    Vec2(2, 2),    // 4
    Vec2(2, 2),    // 5
    Vec2(3, 2),    // 6
    Vec2(4, 2),    // 7
    Vec2(5, 2),    // 8
    Vec2(6, 2),    // 9
    Vec2(7, 2),    // 10
    Vec2(8, 2),    // 11
    Vec2(7, 2),    // 12
    Vec2(6, 2),    // 13
    Vec2(5, 2),    // 14
    Vec2(4, 2),    // 15
    Vec2(3, 2),    // 16
    Vec2(2, 2),    // 17
    Vec2(2, 2),    // 18
    Vec2(2, 2),    // 19
    Vec2(3, 2),    // 20
    Vec2(4, 2),    // 21
    Vec2(5, 2),    // 22
    Vec2(6, 2),    // 23
    Vec2(7, 2),    // 24
    Vec2(8, 2),    // 25
    Vec2(8, 2),    // 26
    Vec2(8, 2),    // 27
    Vec2(8, 2),    // 28
    Vec2(8, 2),    // 29
    Vec2(7, 2),    // 30
    Vec2(6, 2),    // 31
    Vec2(5, 2),    // 32
    Vec2(4, 2),    // 33
    Vec2(3, 2),    // 34
    Vec2(2, 2),    // 35
    Vec2(2, 2),    // 36
    Vec2(8, 2),    // 37
    Vec2(2, 2),    // 38
    Vec2(8, 2),    // 39
    Vec2(2, 2),    // 40
    Vec2(8, 2),    // 41
    Vec2(2, 2),    // 42
    Vec2(8, 2),    // 43
    Vec2(3, 3),    // 44
    Vec2(56, 16),    // 45
    Vec2(56, 16),    // 46
    Vec2(56, 16),    // 47
    Vec2(53, 2),    // 48
    Vec2(59, 2),    // 49
    Vec2(52, 2),    // 50
    Vec2(60, 2),    // 51
    Vec2(54, 2),    // 52
    Vec2(58, 2),    // 53
    Vec2(54, 2),    // 54
    Vec2(58, 2),    // 55
    Vec2(88, 16),    // 56
    Vec2(86, 16),    // 57
    Vec2(84, 16),    // 58
    Vec2(80, 16),    // 59
    Vec2(72, 16),    // 60
    Vec2(64, 16),    // 61
    Vec2(56, 16),    // 62
    Vec2(48, 16),    // 63
    Vec2(40, 16),    // 64
    Vec2(36, 16),    // 65
    Vec2(32, 16),    // 66
    Vec2(30, 16),    // 67
    Vec2(28, 16),    // 68
    Vec2(26, 16),    // 69
    Vec2(25, 16),    // 70
    Vec2(24, 16),    // 71
    Vec2(24, 16),    // 72
    Vec2(26, 16),    // 73
    Vec2(28, 16),    // 74
    Vec2(32, 16),    // 75
    Vec2(40, 16),    // 76
    Vec2(48, 16),    // 77
    Vec2(56, 16),    // 78
    Vec2(64, 16),    // 79
    Vec2(72, 16),    // 80
    Vec2(76, 16),    // 81
    Vec2(80, 16),    // 82
    Vec2(82, 16),    // 83
    Vec2(84, 16),    // 84
    Vec2(86, 16),    // 85
    Vec2(87, 16),    // 86
    Vec2(88, 16),    // 87
};

const static AnimObjData animObjData[] =
{
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[0] },    // AnimType_NotWord 0
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[1] },    // AnimType_NotWord 1
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 10, &positions[2] },    // AnimType_SlideL 2
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 7, &positions[12] },    // AnimType_SlideL 3
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 7, &positions[19] },    // AnimType_SlideR 4
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 10, &positions[26] },    // AnimType_SlideR 5
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[36] },    // AnimType_OldWord 6
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[37] },    // AnimType_OldWord 7
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[38] },    // AnimType_NewWord 8
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[39] },    // AnimType_NewWord 9
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[40] },    // AnimType_EndofRound 10
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[41] },    // AnimType_EndofRound 11
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[42] },    // AnimType_Shuffle 12
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[43] },    // AnimType_Shuffle 13
    { &LevelComplete, &LevelComplete, 0, Layer_BG0, 0, 1, &positions[44] },    // AnimType_CityProgression 14
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[45] },    // AnimType_HintBarAppear 15
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[46] },    // AnimType_HintBarIdle 16
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[47] },    // AnimType_HintBarDisappear 17
    { 0, 0, &HintSprite, Layer_Sprite, 0, 8, &positions[48] },    // AnimType_HintWindUpSlide 18
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[56] },    // AnimType_HintSlideL 19
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[72] },    // AnimType_HintSlideR 20
};

const static AnimData animData[] =
{
    { 1.f, true, 2, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 2, &animObjData[2]},    // AnimType_SlideL
    { 0.5f, false, 2, &animObjData[4]},    // AnimType_SlideR
    { 1.f, true, 2, &animObjData[6]},    // AnimType_OldWord
    { 1.5f, true, 2, &animObjData[8]},    // AnimType_NewWord
    { 1.f, true, 2, &animObjData[10]},    // AnimType_EndofRound
    { 0.5f, true, 2, &animObjData[12]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[19]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[20]},    // AnimType_HintSlideR
    { 1.f, true, 2, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 2, &animObjData[2]},    // AnimType_SlideL
    { 0.5f, false, 2, &animObjData[4]},    // AnimType_SlideR
    { 1.f, true, 2, &animObjData[6]},    // AnimType_OldWord
    { 1.5f, true, 2, &animObjData[8]},    // AnimType_NewWord
    { 1.f, true, 2, &animObjData[10]},    // AnimType_EndofRound
    { 0.5f, true, 2, &animObjData[12]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[19]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[20]},    // AnimType_HintSlideR
    { 1.f, true, 2, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 2, &animObjData[2]},    // AnimType_SlideL
    { 0.5f, false, 2, &animObjData[4]},    // AnimType_SlideR
    { 1.f, true, 2, &animObjData[6]},    // AnimType_OldWord
    { 1.5f, true, 2, &animObjData[8]},    // AnimType_NewWord
    { 1.f, true, 2, &animObjData[10]},    // AnimType_EndofRound
    { 0.5f, true, 2, &animObjData[12]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[19]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[20]},    // AnimType_HintSlideR
};

