// This file is autogenerated from anim/generate_anim.py

const static Vec2 positions[] =
{
    Vec2(2, 2),    // 0
    Vec2(8, 2),    // 1
    Vec2(2, 2),    // 2
    Vec2(2, 2),    // 3
    Vec2(2, 2),    // 4
    Vec2(2, 2),    // 5
    Vec2(3, 2),    // 6
    Vec2(4, 2),    // 7
    Vec2(5, 2),    // 8
    Vec2(6, 2),    // 9
    Vec2(7, 2),    // 10
    Vec2(8, 2),    // 11
    Vec2(7, 2),    // 12
    Vec2(6, 2),    // 13
    Vec2(5, 2),    // 14
    Vec2(4, 2),    // 15
    Vec2(3, 2),    // 16
    Vec2(2, 2),    // 17
    Vec2(2, 2),    // 18
    Vec2(2, 2),    // 19
    Vec2(3, 2),    // 20
    Vec2(4, 2),    // 21
    Vec2(5, 2),    // 22
    Vec2(6, 2),    // 23
    Vec2(7, 2),    // 24
    Vec2(8, 2),    // 25
    Vec2(8, 2),    // 26
    Vec2(8, 2),    // 27
    Vec2(8, 2),    // 28
    Vec2(8, 2),    // 29
    Vec2(7, 2),    // 30
    Vec2(6, 2),    // 31
    Vec2(5, 2),    // 32
    Vec2(4, 2),    // 33
    Vec2(3, 2),    // 34
    Vec2(2, 2),    // 35
    Vec2(2, 2),    // 36
    Vec2(8, 2),    // 37
    Vec2(2, 2),    // 38
    Vec2(8, 2),    // 39
    Vec2(2, 2),    // 40
    Vec2(8, 2),    // 41
    Vec2(2, 2),    // 42
    Vec2(8, 2),    // 43
    Vec2(3, 3),    // 44
    Vec2(56, 16),    // 45
    Vec2(56, 16),    // 46
    Vec2(56, 16),    // 47
    Vec2(53, 2),    // 48
    Vec2(59, 2),    // 49
    Vec2(52, 2),    // 50
    Vec2(60, 2),    // 51
    Vec2(54, 2),    // 52
    Vec2(58, 2),    // 53
    Vec2(54, 2),    // 54
    Vec2(58, 2),    // 55
    Vec2(88, 16),    // 56
    Vec2(86, 16),    // 57
    Vec2(84, 16),    // 58
    Vec2(80, 16),    // 59
    Vec2(72, 16),    // 60
    Vec2(64, 16),    // 61
    Vec2(56, 16),    // 62
    Vec2(48, 16),    // 63
    Vec2(40, 16),    // 64
    Vec2(36, 16),    // 65
    Vec2(32, 16),    // 66
    Vec2(30, 16),    // 67
    Vec2(28, 16),    // 68
    Vec2(26, 16),    // 69
    Vec2(25, 16),    // 70
    Vec2(24, 16),    // 71
    Vec2(24, 16),    // 72
    Vec2(26, 16),    // 73
    Vec2(28, 16),    // 74
    Vec2(32, 16),    // 75
    Vec2(40, 16),    // 76
    Vec2(48, 16),    // 77
    Vec2(56, 16),    // 78
    Vec2(64, 16),    // 79
    Vec2(72, 16),    // 80
    Vec2(76, 16),    // 81
    Vec2(80, 16),    // 82
    Vec2(82, 16),    // 83
    Vec2(84, 16),    // 84
    Vec2(86, 16),    // 85
    Vec2(87, 16),    // 86
    Vec2(88, 16),    // 87
    Vec2(2, 2),    // 88
    Vec2(6, 2),    // 89
    Vec2(10, 2),    // 90
    Vec2(2, 2),    // 91
    Vec2(6, 2),    // 92
    Vec2(10, 2),    // 93
    Vec2(2, 2),    // 94
    Vec2(6, 2),    // 95
    Vec2(10, 2),    // 96
    Vec2(2, 2),    // 97
    Vec2(6, 2),    // 98
    Vec2(10, 2),    // 99
    Vec2(2, 2),    // 100
    Vec2(6, 2),    // 101
    Vec2(10, 2),    // 102
    Vec2(88, 16),    // 103
    Vec2(86, 16),    // 104
    Vec2(84, 16),    // 105
    Vec2(80, 16),    // 106
    Vec2(72, 16),    // 107
    Vec2(64, 16),    // 108
    Vec2(56, 16),    // 109
    Vec2(48, 16),    // 110
    Vec2(40, 16),    // 111
    Vec2(36, 16),    // 112
    Vec2(32, 16),    // 113
    Vec2(30, 16),    // 114
    Vec2(28, 16),    // 115
    Vec2(26, 16),    // 116
    Vec2(25, 16),    // 117
    Vec2(24, 16),    // 118
    Vec2(24, 16),    // 119
    Vec2(26, 16),    // 120
    Vec2(28, 16),    // 121
    Vec2(32, 16),    // 122
    Vec2(40, 16),    // 123
    Vec2(48, 16),    // 124
    Vec2(56, 16),    // 125
    Vec2(64, 16),    // 126
    Vec2(72, 16),    // 127
    Vec2(76, 16),    // 128
    Vec2(80, 16),    // 129
    Vec2(82, 16),    // 130
    Vec2(84, 16),    // 131
    Vec2(86, 16),    // 132
    Vec2(87, 16),    // 133
    Vec2(88, 16),    // 134
    Vec2(2, 2),    // 135
    Vec2(2, 2),    // 136
    Vec2(3, 2),    // 137
    Vec2(4, 2),    // 138
    Vec2(5, 2),    // 139
    Vec2(6, 2),    // 140
    Vec2(7, 2),    // 141
    Vec2(8, 2),    // 142
    Vec2(9, 2),    // 143
    Vec2(10, 2),    // 144
    Vec2(6, 2),    // 145
    Vec2(5, 2),    // 146
    Vec2(5, 2),    // 147
    Vec2(4, 2),    // 148
    Vec2(3, 2),    // 149
    Vec2(2, 2),    // 150
    Vec2(2, 2),    // 151
    Vec2(10, 2),    // 152
    Vec2(9, 2),    // 153
    Vec2(9, 2),    // 154
    Vec2(8, 2),    // 155
    Vec2(7, 2),    // 156
    Vec2(6, 2),    // 157
    Vec2(6, 2),    // 158
    Vec2(5, 2),    // 159
    Vec2(3, 2),    // 160
    Vec2(4, 2),    // 161
    Vec2(5, 2),    // 162
    Vec2(6, 2),    // 163
    Vec2(7, 2),    // 164
    Vec2(8, 2),    // 165
    Vec2(8, 2),    // 166
    Vec2(8, 2),    // 167
    Vec2(8, 2),    // 168
    Vec2(8, 2),    // 169
    Vec2(7, 2),    // 170
    Vec2(6, 2),    // 171
    Vec2(5, 2),    // 172
    Vec2(4, 2),    // 173
    Vec2(3, 2),    // 174
    Vec2(2, 2),    // 175
};

const static AnimObjData animObjData[] =
{
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[0] },    // AnimType_NotWord 0
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[1] },    // AnimType_NotWord 1
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 10, &positions[2] },    // AnimType_SlideL 2
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 7, &positions[12] },    // AnimType_SlideL 3
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 7, &positions[19] },    // AnimType_SlideR 4
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 10, &positions[26] },    // AnimType_SlideR 5
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[36] },    // AnimType_OldWord 6
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[37] },    // AnimType_OldWord 7
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[38] },    // AnimType_NewWord 8
    { &Tile2Glow, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[39] },    // AnimType_NewWord 9
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[40] },    // AnimType_EndofRound 10
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[41] },    // AnimType_EndofRound 11
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[42] },    // AnimType_Shuffle 12
    { &Tile2, &Tile2Blank, 0, Layer_BG0, 0, 1, &positions[43] },    // AnimType_Shuffle 13
    { &LevelComplete, &LevelComplete, 0, Layer_BG0, 0, 1, &positions[44] },    // AnimType_CityProgression 14
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[45] },    // AnimType_HintBarAppear 15
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[46] },    // AnimType_HintBarIdle 16
    { 0, 0, &HintSprite, Layer_Sprite, 0, 1, &positions[47] },    // AnimType_HintBarDisappear 17
    { 0, 0, &HintSprite, Layer_Sprite, 0, 8, &positions[48] },    // AnimType_HintWindUpSlide 18
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[56] },    // AnimType_HintSlideL 19
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[72] },    // AnimType_HintSlideR 20
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[88] },    // AnimType_NotWord 21
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[89] },    // AnimType_NotWord 22
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[90] },    // AnimType_NotWord 23
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 10, &positions[135] },    // AnimType_SlideL 24
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 7, &positions[145] },    // AnimType_SlideL 25
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 7, &positions[152] },    // AnimType_SlideL 26
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 7, &positions[159] },    // AnimType_SlideR 27
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 10, &positions[166] },    // AnimType_SlideR 28
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[0] },    // AnimType_SlideR 29
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[91] },    // AnimType_OldWord 30
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[92] },    // AnimType_OldWord 31
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[93] },    // AnimType_OldWord 32
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[94] },    // AnimType_NewWord 33
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[95] },    // AnimType_NewWord 34
    { &Tile3Glow, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[96] },    // AnimType_NewWord 35
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[97] },    // AnimType_EndofRound 36
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[98] },    // AnimType_EndofRound 37
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[99] },    // AnimType_EndofRound 38
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[100] },    // AnimType_Shuffle 39
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[101] },    // AnimType_Shuffle 40
    { &Tile3, &Tile3Blank, 0, Layer_BG0, 0, 1, &positions[102] },    // AnimType_Shuffle 41
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[103] },    // AnimType_HintSlideL 42
    { 0, 0, &HintSprite, Layer_Sprite, 0, 16, &positions[119] },    // AnimType_HintSlideR 43
};

const static AnimData animData[] =
{
    { 1.f, true, 1, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 1, &animObjData[0]},    // AnimType_SlideL
    { 0.5f, false, 1, &animObjData[0]},    // AnimType_SlideR
    { 1.f, true, 1, &animObjData[0]},    // AnimType_OldWord
    { 1.5f, true, 1, &animObjData[0]},    // AnimType_NewWord
    { 1.f, true, 1, &animObjData[0]},    // AnimType_EndofRound
    { 0.5f, true, 1, &animObjData[0]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[0]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[0]},    // AnimType_HintSlideR
    { 1.f, true, 2, &animObjData[0]},    // AnimType_NotWord
    { 0.5f, false, 2, &animObjData[2]},    // AnimType_SlideL
    { 0.5f, false, 2, &animObjData[4]},    // AnimType_SlideR
    { 1.f, true, 2, &animObjData[6]},    // AnimType_OldWord
    { 1.5f, true, 2, &animObjData[8]},    // AnimType_NewWord
    { 1.f, true, 2, &animObjData[10]},    // AnimType_EndofRound
    { 0.5f, true, 2, &animObjData[12]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[19]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[20]},    // AnimType_HintSlideR
    { 1.f, true, 3, &animObjData[21]},    // AnimType_NotWord
    { 0.5f, false, 3, &animObjData[24]},    // AnimType_SlideL
    { 0.5f, false, 3, &animObjData[27]},    // AnimType_SlideR
    { 1.f, true, 3, &animObjData[30]},    // AnimType_OldWord
    { 1.5f, true, 3, &animObjData[33]},    // AnimType_NewWord
    { 1.f, true, 3, &animObjData[36]},    // AnimType_EndofRound
    { 0.5f, true, 3, &animObjData[39]},    // AnimType_Shuffle
    { 1.f, true, 1, &animObjData[14]},    // AnimType_CityProgression
    { 1.f, true, 1, &animObjData[15]},    // AnimType_HintBarAppear
    { 3.f, false, 1, &animObjData[16]},    // AnimType_HintBarIdle
    { 0.3f, false, 1, &animObjData[17]},    // AnimType_HintBarDisappear
    { 2.f, false, 1, &animObjData[18]},    // AnimType_HintWindUpSlide
    { 1.f, true, 1, &animObjData[42]},    // AnimType_HintSlideL
    { 1.f, true, 1, &animObjData[43]},    // AnimType_HintSlideR
};

