// This file is autogenerated from dict/generate_dict.py

const unsigned NUM_PUZZLES = 25;

const static char* puzzles[] =
{
    "ACT",    // pieces: ['AC', 'T '], solutions: ['CAT', 'ACT']
    "EXACT",    // pieces: ['EX', 'AC', 'T '], solutions: ['CAT', 'EXACT', 'ACT']
    "CASTS",    // pieces: ['CA', 'ST', 'S '], solutions: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    "FACTS",    // pieces: [' F', 'AC', 'TS'], solutions: ['FACTS', 'CAST', 'ACTS', 'CATS']
    "FACTOR",    // pieces: ['FA', 'CT', 'OR'], solutions: ['FARO', 'FACT', 'FACTOR']
    "RAT",    // pieces: ['RA', 'T '], solutions: ['RAT', 'ART', 'TAR']
    "ACRE",    // pieces: ['AC', 'RE'], solutions: ['CARE', 'ACRE']
    "BUS",    // pieces: ['BU', 'S '], solutions: ['BUS', 'SUB']
    "BUYS",    // pieces: ['BU', 'YS'], solutions: ['BUSY', 'BUYS']
    "BUSES",    // pieces: [' B', 'US', 'ES'], solutions: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    "CLUBS",    // pieces: ['CL', 'UB', 'S '], solutions: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    "BUMPS",    // pieces: ['BU', 'MP', 'S '], solutions: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    "PART",    // pieces: ['PA', 'RT'], solutions: ['PART', 'TRAP']
    "STRING",    // pieces: ['ST', 'RI', 'NG'], solutions: ['RING', 'STIR', 'STRING']
    "RINGS",    // pieces: ['RI', 'NG', 'S '], solutions: ['SIR', 'RING', 'SRI', 'RINGS']
    "BELONG",    // pieces: ['BE', 'LO', 'NG'], solutions: ['LOBE', 'BELONG', 'LONG']
    "CLOUD",    // pieces: [' C', 'LO', 'UD'], solutions: ['CUD', 'LOUD', 'COL', 'CLOUD']
    "FAVOR",    // pieces: [' F', 'AV', 'OR'], solutions: ['FAVOR', 'FRO', 'FOR']
    "CAREER",    // pieces: ['CA', 'RE', 'ER'], solutions: ['CAREER', 'ACRE', 'CARE']
    "OLIVES",    // pieces: ['OL', 'IV', 'ES'], solutions: ['VIOL', 'OLES', 'LOSE', 'OLIVES', 'VISE', 'VIES']
    "MEMBER",    // pieces: ['ME', 'MB', 'ER'], solutions: ['MEMBER', 'MERE']
    "EIGHT",    // pieces: [' E', 'IG', 'HT'], solutions: ['EIGHT', 'GIE', 'THE', 'ETH']
    "INCOME",    // pieces: ['IN', 'CO', 'ME'], solutions: ['CONI', 'COIN', 'COME', 'INCOME']
    "ALLOW",    // pieces: ['AL', 'LO', 'W '], solutions: ['OLLA', 'LAW', 'LOW', 'ALLOW']
    "BEGUN",    // pieces: [' B', 'EG', 'UN'], solutions: ['NUB', 'GENU', 'BUN', 'BEG', 'BEGUN']
};

const static unsigned char puzzlesNumGoalAnagrams[] =
{
    2,	// ACT, nonbonus anagrams: ['CAT', 'ACT']
    3,	// EXACT, nonbonus anagrams: ['CAT', 'EXACT', 'ACT']
    4,	// CASTS, nonbonus anagrams: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    4,	// FACTS, nonbonus anagrams: ['FACTS', 'CAST', 'ACTS', 'CATS']
    2,	// FACTOR, nonbonus anagrams: ['FARO', 'FACT', 'FACTOR']
    2,	// RAT, nonbonus anagrams: ['RAT', 'ART', 'TAR']
    2,	// ACRE, nonbonus anagrams: ['CARE', 'ACRE']
    2,	// BUS, nonbonus anagrams: ['BUS', 'SUB']
    2,	// BUYS, nonbonus anagrams: ['BUSY', 'BUYS']
    3,	// BUSES, nonbonus anagrams: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    3,	// CLUBS, nonbonus anagrams: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    3,	// BUMPS, nonbonus anagrams: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    2,	// PART, nonbonus anagrams: ['PART', 'TRAP']
    2,	// STRING, nonbonus anagrams: ['RING', 'STIR', 'STRING']
    3,	// RINGS, nonbonus anagrams: ['SIR', 'RING', 'RINGS']
    3,	// BELONG, nonbonus anagrams: ['LOBE', 'BELONG', 'LONG']
    3,	// CLOUD, nonbonus anagrams: ['CUD', 'LOUD', 'COL', 'CLOUD']
    3,	// FAVOR, nonbonus anagrams: ['FAVOR', 'FRO', 'FOR']
    3,	// CAREER, nonbonus anagrams: ['CAREER', 'ACRE', 'CARE']
    1,	// OLIVES, nonbonus anagrams: ['VIOL', 'OLES', 'LOSE', 'OLIVES', 'VISE', 'VIES']
    2,	// MEMBER, nonbonus anagrams: ['MEMBER', 'MERE']
    2,	// EIGHT, nonbonus anagrams: ['EIGHT', 'THE']
    3,	// INCOME, nonbonus anagrams: ['COIN', 'COME', 'INCOME']
    3,	// ALLOW, nonbonus anagrams: ['LAW', 'LOW', 'ALLOW']
    3,	// BEGUN, nonbonus anagrams: ['NUB', 'BUN', 'BEG', 'BEGUN']
};

const static unsigned char puzzlesNumPossibleAnagrams[] =
{
    2,	// ACT, all anagrams: ['CAT', 'ACT']
    3,	// EXACT, all anagrams: ['CAT', 'EXACT', 'ACT']
    6,	// CASTS, all anagrams: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    4,	// FACTS, all anagrams: ['FACTS', 'CAST', 'ACTS', 'CATS']
    3,	// FACTOR, all anagrams: ['FARO', 'FACT', 'FACTOR']
    3,	// RAT, all anagrams: ['RAT', 'ART', 'TAR']
    2,	// ACRE, all anagrams: ['CARE', 'ACRE']
    2,	// BUS, all anagrams: ['BUS', 'SUB']
    2,	// BUYS, all anagrams: ['BUSY', 'BUYS']
    5,	// BUSES, all anagrams: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    4,	// CLUBS, all anagrams: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    4,	// BUMPS, all anagrams: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    2,	// PART, all anagrams: ['PART', 'TRAP']
    3,	// STRING, all anagrams: ['RING', 'STIR', 'STRING']
    4,	// RINGS, all anagrams: ['SIR', 'RING', 'SRI', 'RINGS']
    3,	// BELONG, all anagrams: ['LOBE', 'BELONG', 'LONG']
    4,	// CLOUD, all anagrams: ['CUD', 'LOUD', 'COL', 'CLOUD']
    3,	// FAVOR, all anagrams: ['FAVOR', 'FRO', 'FOR']
    3,	// CAREER, all anagrams: ['CAREER', 'ACRE', 'CARE']
    6,	// OLIVES, all anagrams: ['VIOL', 'OLES', 'LOSE', 'OLIVES', 'VISE', 'VIES']
    2,	// MEMBER, all anagrams: ['MEMBER', 'MERE']
    4,	// EIGHT, all anagrams: ['EIGHT', 'GIE', 'THE', 'ETH']
    4,	// INCOME, all anagrams: ['CONI', 'COIN', 'COME', 'INCOME']
    4,	// ALLOW, all anagrams: ['OLLA', 'LAW', 'LOW', 'ALLOW']
    5,	// BEGUN, all anagrams: ['NUB', 'GENU', 'BUN', 'BEG', 'BEGUN']
};

const static unsigned _puzzlesPossibleWordIndexes_ACT[] =
{
    19,	// CAT,
    1,	// ACT,
};

const static unsigned _puzzlesPossibleWordIndexes_EXACT[] =
{
    19,	// CAT,
    31,	// EXACT,
    1,	// ACT,
};

const static unsigned _puzzlesPossibleWordIndexes_CASTS[] =
{
    58,	// SAC,
    18,	// CASTS,
    2,	// ACTS,
    17,	// CAST,
    20,	// CATS,
    59,	// SCATS,
};

const static unsigned _puzzlesPossibleWordIndexes_FACTS[] =
{
    34,	// FACTS,
    17,	// CAST,
    2,	// ACTS,
    20,	// CATS,
};

const static unsigned _puzzlesPossibleWordIndexes_FACTOR[] =
{
    35,	// FARO,
    32,	// FACT,
    33,	// FACTOR,
};

const static unsigned _puzzlesPossibleWordIndexes_RAT[] =
{
    55,	// RAT,
    4,	// ART,
    66,	// TAR,
};

const static unsigned _puzzlesPossibleWordIndexes_ACRE[] =
{
    15,	// CARE,
    0,	// ACRE,
};

const static unsigned _puzzlesPossibleWordIndexes_BUS[] =
{
    11,	// BUS,
    64,	// SUB,
};

const static unsigned _puzzlesPossibleWordIndexes_BUYS[] =
{
    13,	// BUSY,
    14,	// BUYS,
};

const static unsigned _puzzlesPossibleWordIndexes_BUSES[] =
{
    11,	// BUS,
    69,	// USES,
    64,	// SUB,
    65,	// SUES,
    12,	// BUSES,
};

const static unsigned _puzzlesPossibleWordIndexes_CLUBS[] =
{
    22,	// CLUB,
    11,	// BUS,
    23,	// CLUBS,
    64,	// SUB,
};

const static unsigned _puzzlesPossibleWordIndexes_BUMPS[] =
{
    8,	// BUMP,
    11,	// BUS,
    9,	// BUMPS,
    64,	// SUB,
};

const static unsigned _puzzlesPossibleWordIndexes_PART[] =
{
    54,	// PART,
    68,	// TRAP,
};

const static unsigned _puzzlesPossibleWordIndexes_STRING[] =
{
    56,	// RING,
    62,	// STIR,
    63,	// STRING,
};

const static unsigned _puzzlesPossibleWordIndexes_RINGS[] =
{
    60,	// SIR,
    56,	// RING,
    61,	// SRI,
    57,	// RINGS,
};

const static unsigned _puzzlesPossibleWordIndexes_BELONG[] =
{
    43,	// LOBE,
    7,	// BELONG,
    44,	// LONG,
};

const static unsigned _puzzlesPossibleWordIndexes_CLOUD[] =
{
    28,	// CUD,
    46,	// LOUD,
    25,	// COL,
    21,	// CLOUD,
};

const static unsigned _puzzlesPossibleWordIndexes_FAVOR[] =
{
    36,	// FAVOR,
    38,	// FRO,
    37,	// FOR,
};

const static unsigned _puzzlesPossibleWordIndexes_CAREER[] =
{
    16,	// CAREER,
    0,	// ACRE,
    15,	// CARE,
};

const static unsigned _puzzlesPossibleWordIndexes_OLIVES[] =
{
    71,	// VIOL,
    51,	// OLES,
    45,	// LOSE,
    52,	// OLIVES,
    72,	// VISE,
    70,	// VIES,
};

const static unsigned _puzzlesPossibleWordIndexes_MEMBER[] =
{
    48,	// MEMBER,
    49,	// MERE,
};

const static unsigned _puzzlesPossibleWordIndexes_EIGHT[] =
{
    29,	// EIGHT,
    40,	// GIE,
    67,	// THE,
    30,	// ETH,
};

const static unsigned _puzzlesPossibleWordIndexes_INCOME[] =
{
    27,	// CONI,
    24,	// COIN,
    26,	// COME,
    41,	// INCOME,
};

const static unsigned _puzzlesPossibleWordIndexes_ALLOW[] =
{
    53,	// OLLA,
    42,	// LAW,
    47,	// LOW,
    3,	// ALLOW,
};

const static unsigned _puzzlesPossibleWordIndexes_BEGUN[] =
{
    50,	// NUB,
    39,	// GENU,
    10,	// BUN,
    5,	// BEG,
    6,	// BEGUN,
};

const static unsigned *puzzlesPossibleWordIndexes[] =
{
    _puzzlesPossibleWordIndexes_ACT,	// ACT,
    _puzzlesPossibleWordIndexes_EXACT,	// EXACT,
    _puzzlesPossibleWordIndexes_CASTS,	// CASTS,
    _puzzlesPossibleWordIndexes_FACTS,	// FACTS,
    _puzzlesPossibleWordIndexes_FACTOR,	// FACTOR,
    _puzzlesPossibleWordIndexes_RAT,	// RAT,
    _puzzlesPossibleWordIndexes_ACRE,	// ACRE,
    _puzzlesPossibleWordIndexes_BUS,	// BUS,
    _puzzlesPossibleWordIndexes_BUYS,	// BUYS,
    _puzzlesPossibleWordIndexes_BUSES,	// BUSES,
    _puzzlesPossibleWordIndexes_CLUBS,	// CLUBS,
    _puzzlesPossibleWordIndexes_BUMPS,	// BUMPS,
    _puzzlesPossibleWordIndexes_PART,	// PART,
    _puzzlesPossibleWordIndexes_STRING,	// STRING,
    _puzzlesPossibleWordIndexes_RINGS,	// RINGS,
    _puzzlesPossibleWordIndexes_BELONG,	// BELONG,
    _puzzlesPossibleWordIndexes_CLOUD,	// CLOUD,
    _puzzlesPossibleWordIndexes_FAVOR,	// FAVOR,
    _puzzlesPossibleWordIndexes_CAREER,	// CAREER,
    _puzzlesPossibleWordIndexes_OLIVES,	// OLIVES,
    _puzzlesPossibleWordIndexes_MEMBER,	// MEMBER,
    _puzzlesPossibleWordIndexes_EIGHT,	// EIGHT,
    _puzzlesPossibleWordIndexes_INCOME,	// INCOME,
    _puzzlesPossibleWordIndexes_ALLOW,	// ALLOW,
    _puzzlesPossibleWordIndexes_BEGUN,	// BEGUN,
};

const static bool puzzlesUseLeadingSpaces[] =
{
    false,	// ACT
    false,	// EXACT
    false,	// CASTS
    true,	// FACTS
    false,	// FACTOR
    false,	// RAT
    false,	// ACRE
    false,	// BUS
    false,	// BUYS
    true,	// BUSES
    false,	// CLUBS
    false,	// BUMPS
    false,	// PART
    false,	// STRING
    false,	// RINGS
    false,	// BELONG
    true,	// CLOUD
    true,	// FAVOR
    false,	// CAREER
    false,	// OLIVES
    false,	// MEMBER
    true,	// EIGHT
    false,	// INCOME
    false,	// ALLOW
    true,	// BEGUN
};

