// This file is autogenerated from dict/generate_dict.py

const unsigned NUM_PUZZLES = 30;

const static char* puzzles[] =
{
    "ACT ",    // pieces: ['AC', 'T '], solutions: ['CAT', 'ACT']
    "EXACT ",    // pieces: ['EX', 'AC', 'T '], solutions: ['CAT', 'EXACT', 'ACT']
    "CATS",    // pieces: ['CA', 'TS'], solutions: ['CAST', 'CATS', 'ACTS']
    "CASTS ",    // pieces: ['CA', 'ST', 'S '], solutions: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    " FACTS",    // pieces: [' F', 'AC', 'TS'], solutions: ['FACTS', 'CAST', 'ACTS', 'CATS']
    "FACTOR",    // pieces: ['FA', 'CT', 'OR'], solutions: ['FARO', 'FACT', 'FACTOR']
    "RAT ",    // pieces: ['RA', 'T '], solutions: ['RAT', 'ART', 'TAR']
    "ACRE",    // pieces: ['AC', 'RE'], solutions: ['CARE', 'ACRE']
    "BUS ",    // pieces: ['BU', 'S '], solutions: ['BUS', 'SUB']
    "BUYS",    // pieces: ['BU', 'YS'], solutions: ['BUSY', 'BUYS']
    " BUSES",    // pieces: [' B', 'US', 'ES'], solutions: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    "CLUBS ",    // pieces: ['CL', 'UB', 'S '], solutions: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    " CLUBBING",    // pieces: [' CL', 'UBB', 'ING'], solutions: ['CLUBBING', 'CLING']
    "BUMPS ",    // pieces: ['BU', 'MP', 'S '], solutions: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    "PART",    // pieces: ['PA', 'RT'], solutions: ['PART', 'TRAP']
    "STRING",    // pieces: ['ST', 'RI', 'NG'], solutions: ['RING', 'STIR', 'STRING']
    "RINGS ",    // pieces: ['RI', 'NG', 'S '], solutions: ['SIR', 'RING', 'SRI', 'RINGS']
    "BELONG",    // pieces: ['BE', 'LO', 'NG'], solutions: ['LOBE', 'BELONG', 'LONG']
    " CLOUD",    // pieces: [' C', 'LO', 'UD'], solutions: ['CUD', 'LOUD', 'COL', 'CLOUD']
    " FAVOR",    // pieces: [' F', 'AV', 'OR'], solutions: ['FAVOR', 'FRO', 'FOR']
    "CAREER",    // pieces: ['CA', 'RE', 'ER'], solutions: ['CAREER', 'ACRE', 'CARE']
    " PLEASANT",    // pieces: [' PL', 'EAS', 'ANT'], solutions: ['PLEAS', 'PLEASANT', 'PLANT']
    "MEMBER",    // pieces: ['ME', 'MB', 'ER'], solutions: ['MEMBER', 'MERE']
    " EIGHT",    // pieces: [' E', 'IG', 'HT'], solutions: ['EIGHT', 'GIE', 'THE', 'ETH']
    "DIRECTOR ",    // pieces: ['DIR', 'ECT', 'OR '], solutions: ['DIRECTOR', 'DIRECT']
    "INCOME",    // pieces: ['IN', 'CO', 'ME'], solutions: ['CONI', 'COIN', 'COME', 'INCOME']
    "ALLOW ",    // pieces: ['AL', 'LO', 'W '], solutions: ['OLLA', 'LAW', 'LOW', 'ALLOW']
    " ELECTION",    // pieces: [' EL', 'ECT', 'ION'], solutions: ['ELECT', 'ELECTION']
    " BEGUN",    // pieces: [' B', 'EG', 'UN'], solutions: ['NUB', 'GENU', 'BUN', 'BEG', 'BEGUN']
    " REMEMBER",    // pieces: [' RE', 'MEM', 'BER'], solutions: ['MEMBER', 'REMEMBER']
};

const static unsigned char puzzlesNumGoalAnagrams[] =
{
    2,	// "ACT ", all anagrams: ['CAT', 'ACT']
    3,	// "EXACT ", all anagrams: ['CAT', 'EXACT', 'ACT']
    3,	// "CATS", all anagrams: ['CAST', 'CATS', 'ACTS']
    4,	// "CASTS ", all anagrams: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    4,	// " FACTS", all anagrams: ['FACTS', 'CAST', 'ACTS', 'CATS']
    2,	// "FACTOR", all anagrams: ['FARO', 'FACT', 'FACTOR']
    2,	// "RAT ", all anagrams: ['RAT', 'ART', 'TAR']
    2,	// "ACRE", all anagrams: ['CARE', 'ACRE']
    2,	// "BUS ", all anagrams: ['BUS', 'SUB']
    2,	// "BUYS", all anagrams: ['BUSY', 'BUYS']
    3,	// " BUSES", all anagrams: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    3,	// "CLUBS ", all anagrams: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    2,	// " CLUBBING", all anagrams: ['CLUBBING', 'CLING']
    3,	// "BUMPS ", all anagrams: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    2,	// "PART", all anagrams: ['PART', 'TRAP']
    2,	// "STRING", all anagrams: ['RING', 'STIR', 'STRING']
    3,	// "RINGS ", all anagrams: ['SIR', 'RING', 'SRI', 'RINGS']
    3,	// "BELONG", all anagrams: ['LOBE', 'BELONG', 'LONG']
    3,	// " CLOUD", all anagrams: ['CUD', 'LOUD', 'COL', 'CLOUD']
    3,	// " FAVOR", all anagrams: ['FAVOR', 'FRO', 'FOR']
    3,	// "CAREER", all anagrams: ['CAREER', 'ACRE', 'CARE']
    2,	// " PLEASANT", all anagrams: ['PLEAS', 'PLEASANT', 'PLANT']
    2,	// "MEMBER", all anagrams: ['MEMBER', 'MERE']
    2,	// " EIGHT", all anagrams: ['EIGHT', 'GIE', 'THE', 'ETH']
    2,	// "DIRECTOR ", all anagrams: ['DIRECTOR', 'DIRECT']
    3,	// "INCOME", all anagrams: ['CONI', 'COIN', 'COME', 'INCOME']
    3,	// "ALLOW ", all anagrams: ['OLLA', 'LAW', 'LOW', 'ALLOW']
    2,	// " ELECTION", all anagrams: ['ELECT', 'ELECTION']
    3,	// " BEGUN", all anagrams: ['NUB', 'GENU', 'BUN', 'BEG', 'BEGUN']
    2,	// " REMEMBER", all anagrams: ['MEMBER', 'REMEMBER']
};

const static unsigned char puzzlesNumPossibleAnagrams[] =
{
    2,	// ACT , all anagrams: ['CAT', 'ACT']
    3,	// EXACT , all anagrams: ['CAT', 'EXACT', 'ACT']
    3,	// CATS, all anagrams: ['CAST', 'CATS', 'ACTS']
    6,	// CASTS , all anagrams: ['SAC', 'CASTS', 'ACTS', 'CAST', 'CATS', 'SCATS']
    4,	//  FACTS, all anagrams: ['FACTS', 'CAST', 'ACTS', 'CATS']
    3,	// FACTOR, all anagrams: ['FARO', 'FACT', 'FACTOR']
    3,	// RAT , all anagrams: ['RAT', 'ART', 'TAR']
    2,	// ACRE, all anagrams: ['CARE', 'ACRE']
    2,	// BUS , all anagrams: ['BUS', 'SUB']
    2,	// BUYS, all anagrams: ['BUSY', 'BUYS']
    5,	//  BUSES, all anagrams: ['BUS', 'USES', 'SUB', 'SUES', 'BUSES']
    4,	// CLUBS , all anagrams: ['CLUB', 'BUS', 'CLUBS', 'SUB']
    2,	//  CLUBBING, all anagrams: ['CLUBBING', 'CLING']
    4,	// BUMPS , all anagrams: ['BUMP', 'BUS', 'BUMPS', 'SUB']
    2,	// PART, all anagrams: ['PART', 'TRAP']
    3,	// STRING, all anagrams: ['RING', 'STIR', 'STRING']
    4,	// RINGS , all anagrams: ['SIR', 'RING', 'SRI', 'RINGS']
    3,	// BELONG, all anagrams: ['LOBE', 'BELONG', 'LONG']
    4,	//  CLOUD, all anagrams: ['CUD', 'LOUD', 'COL', 'CLOUD']
    3,	//  FAVOR, all anagrams: ['FAVOR', 'FRO', 'FOR']
    3,	// CAREER, all anagrams: ['CAREER', 'ACRE', 'CARE']
    3,	//  PLEASANT, all anagrams: ['PLEAS', 'PLEASANT', 'PLANT']
    2,	// MEMBER, all anagrams: ['MEMBER', 'MERE']
    4,	//  EIGHT, all anagrams: ['EIGHT', 'GIE', 'THE', 'ETH']
    2,	// DIRECTOR , all anagrams: ['DIRECTOR', 'DIRECT']
    4,	// INCOME, all anagrams: ['CONI', 'COIN', 'COME', 'INCOME']
    4,	// ALLOW , all anagrams: ['OLLA', 'LAW', 'LOW', 'ALLOW']
    2,	//  ELECTION, all anagrams: ['ELECT', 'ELECTION']
    5,	//  BEGUN, all anagrams: ['NUB', 'GENU', 'BUN', 'BEG', 'BEGUN']
    2,	//  REMEMBER, all anagrams: ['MEMBER', 'REMEMBER']
};

const static unsigned char _puzzlesPossibleWordIndexes_ACT_[] =
{
    19,	// CAT,
    1,	// ACT,
};

const static unsigned char _puzzlesPossibleWordIndexes_EXACT_[] =
{
    19,	// CAT,
    37,	// EXACT,
    1,	// ACT,
};

const static unsigned char _puzzlesPossibleWordIndexes_CATS[] =
{
    17,	// CAST,
    20,	// CATS,
    2,	// ACTS,
};

const static unsigned char _puzzlesPossibleWordIndexes_CASTS_[] =
{
    65,	// SAC,
    18,	// CASTS,
    2,	// ACTS,
    17,	// CAST,
    20,	// CATS,
    66,	// SCATS,
};

const static unsigned char _puzzlesPossibleWordIndexes__FACTS[] =
{
    40,	// FACTS,
    17,	// CAST,
    2,	// ACTS,
    20,	// CATS,
};

const static unsigned char _puzzlesPossibleWordIndexes_FACTOR[] =
{
    41,	// FARO,
    38,	// FACT,
    39,	// FACTOR,
};

const static unsigned char _puzzlesPossibleWordIndexes_RAT_[] =
{
    61,	// RAT,
    4,	// ART,
    73,	// TAR,
};

const static unsigned char _puzzlesPossibleWordIndexes_ACRE[] =
{
    15,	// CARE,
    0,	// ACRE,
};

const static unsigned char _puzzlesPossibleWordIndexes_BUS_[] =
{
    11,	// BUS,
    71,	// SUB,
};

const static unsigned char _puzzlesPossibleWordIndexes_BUYS[] =
{
    13,	// BUSY,
    14,	// BUYS,
};

const static unsigned char _puzzlesPossibleWordIndexes__BUSES[] =
{
    11,	// BUS,
    76,	// USES,
    71,	// SUB,
    72,	// SUES,
    12,	// BUSES,
};

const static unsigned char _puzzlesPossibleWordIndexes_CLUBS_[] =
{
    23,	// CLUB,
    11,	// BUS,
    25,	// CLUBS,
    71,	// SUB,
};

const static unsigned char _puzzlesPossibleWordIndexes__CLUBBING[] =
{
    24,	// CLUBBING,
    21,	// CLING,
};

const static unsigned char _puzzlesPossibleWordIndexes_BUMPS_[] =
{
    8,	// BUMP,
    11,	// BUS,
    9,	// BUMPS,
    71,	// SUB,
};

const static unsigned char _puzzlesPossibleWordIndexes_PART[] =
{
    57,	// PART,
    75,	// TRAP,
};

const static unsigned char _puzzlesPossibleWordIndexes_STRING[] =
{
    63,	// RING,
    69,	// STIR,
    70,	// STRING,
};

const static unsigned char _puzzlesPossibleWordIndexes_RINGS_[] =
{
    67,	// SIR,
    63,	// RING,
    68,	// SRI,
    64,	// RINGS,
};

const static unsigned char _puzzlesPossibleWordIndexes_BELONG[] =
{
    49,	// LOBE,
    7,	// BELONG,
    50,	// LONG,
};

const static unsigned char _puzzlesPossibleWordIndexes__CLOUD[] =
{
    30,	// CUD,
    51,	// LOUD,
    27,	// COL,
    22,	// CLOUD,
};

const static unsigned char _puzzlesPossibleWordIndexes__FAVOR[] =
{
    42,	// FAVOR,
    44,	// FRO,
    43,	// FOR,
};

const static unsigned char _puzzlesPossibleWordIndexes_CAREER[] =
{
    16,	// CAREER,
    0,	// ACRE,
    15,	// CARE,
};

const static unsigned char _puzzlesPossibleWordIndexes__PLEASANT[] =
{
    59,	// PLEAS,
    60,	// PLEASANT,
    58,	// PLANT,
};

const static unsigned char _puzzlesPossibleWordIndexes_MEMBER[] =
{
    53,	// MEMBER,
    54,	// MERE,
};

const static unsigned char _puzzlesPossibleWordIndexes__EIGHT[] =
{
    33,	// EIGHT,
    46,	// GIE,
    74,	// THE,
    36,	// ETH,
};

const static unsigned char _puzzlesPossibleWordIndexes_DIRECTOR_[] =
{
    32,	// DIRECTOR,
    31,	// DIRECT,
};

const static unsigned char _puzzlesPossibleWordIndexes_INCOME[] =
{
    29,	// CONI,
    26,	// COIN,
    28,	// COME,
    47,	// INCOME,
};

const static unsigned char _puzzlesPossibleWordIndexes_ALLOW_[] =
{
    56,	// OLLA,
    48,	// LAW,
    52,	// LOW,
    3,	// ALLOW,
};

const static unsigned char _puzzlesPossibleWordIndexes__ELECTION[] =
{
    34,	// ELECT,
    35,	// ELECTION,
};

const static unsigned char _puzzlesPossibleWordIndexes__BEGUN[] =
{
    55,	// NUB,
    45,	// GENU,
    10,	// BUN,
    5,	// BEG,
    6,	// BEGUN,
};

const static unsigned char _puzzlesPossibleWordIndexes__REMEMBER[] =
{
    53,	// MEMBER,
    62,	// REMEMBER,
};

const static unsigned char *puzzlesPossibleWordIndexes[] =
{
    _puzzlesPossibleWordIndexes_ACT_,	// "ACT ",
    _puzzlesPossibleWordIndexes_EXACT_,	// "EXACT ",
    _puzzlesPossibleWordIndexes_CATS,	// "CATS",
    _puzzlesPossibleWordIndexes_CASTS_,	// "CASTS ",
    _puzzlesPossibleWordIndexes__FACTS,	// " FACTS",
    _puzzlesPossibleWordIndexes_FACTOR,	// "FACTOR",
    _puzzlesPossibleWordIndexes_RAT_,	// "RAT ",
    _puzzlesPossibleWordIndexes_ACRE,	// "ACRE",
    _puzzlesPossibleWordIndexes_BUS_,	// "BUS ",
    _puzzlesPossibleWordIndexes_BUYS,	// "BUYS",
    _puzzlesPossibleWordIndexes__BUSES,	// " BUSES",
    _puzzlesPossibleWordIndexes_CLUBS_,	// "CLUBS ",
    _puzzlesPossibleWordIndexes__CLUBBING,	// " CLUBBING",
    _puzzlesPossibleWordIndexes_BUMPS_,	// "BUMPS ",
    _puzzlesPossibleWordIndexes_PART,	// "PART",
    _puzzlesPossibleWordIndexes_STRING,	// "STRING",
    _puzzlesPossibleWordIndexes_RINGS_,	// "RINGS ",
    _puzzlesPossibleWordIndexes_BELONG,	// "BELONG",
    _puzzlesPossibleWordIndexes__CLOUD,	// " CLOUD",
    _puzzlesPossibleWordIndexes__FAVOR,	// " FAVOR",
    _puzzlesPossibleWordIndexes_CAREER,	// "CAREER",
    _puzzlesPossibleWordIndexes__PLEASANT,	// " PLEASANT",
    _puzzlesPossibleWordIndexes_MEMBER,	// "MEMBER",
    _puzzlesPossibleWordIndexes__EIGHT,	// " EIGHT",
    _puzzlesPossibleWordIndexes_DIRECTOR_,	// "DIRECTOR ",
    _puzzlesPossibleWordIndexes_INCOME,	// "INCOME",
    _puzzlesPossibleWordIndexes_ALLOW_,	// "ALLOW ",
    _puzzlesPossibleWordIndexes__ELECTION,	// " ELECTION",
    _puzzlesPossibleWordIndexes__BEGUN,	// " BEGUN",
    _puzzlesPossibleWordIndexes__REMEMBER,	// " REMEMBER",
};

const static unsigned char puzzlesNumLeadingSpaces[] =
{
    0,	// ACT 
    0,	// EXACT 
    0,	// CATS
    0,	// CASTS 
    0,	//  FACTS
    0,	// FACTOR
    0,	// RAT 
    0,	// ACRE
    0,	// BUS 
    0,	// BUYS
    0,	//  BUSES
    0,	// CLUBS 
    0,	//  CLUBBING
    0,	// BUMPS 
    0,	// PART
    0,	// STRING
    0,	// RINGS 
    0,	// BELONG
    1,	//  CLOUD
    1,	//  FAVOR
    0,	// CAREER
    0,	//  PLEASANT
    0,	// MEMBER
    0,	//  EIGHT
    0,	// DIRECTOR 
    0,	// INCOME
    0,	// ALLOW 
    0,	//  ELECTION
    0,	//  BEGUN
    0,	//  REMEMBER
};

const static bool puzzlesScramble[] =
{
    false,	// ACT 
    false,	// EXACT 
    true,	// CATS
    true,	// CASTS 
    true,	//  FACTS
    false,	// FACTOR
    true,	// RAT 
    true,	// ACRE
    true,	// BUS 
    false,	// BUYS
    false,	//  BUSES
    true,	// CLUBS 
    true,	//  CLUBBING
    true,	// BUMPS 
    true,	// PART
    true,	// STRING
    true,	// RINGS 
    true,	// BELONG
    true,	//  CLOUD
    true,	//  FAVOR
    true,	// CAREER
    true,	//  PLEASANT
    true,	// MEMBER
    true,	//  EIGHT
    true,	// DIRECTOR 
    true,	// INCOME
    true,	// ALLOW 
    true,	//  ELECTION
    true,	//  BEGUN
    true,	//  REMEMBER
};

const static unsigned char puzzlesMetaLetterIndex[] =
{
    0,	// "ACT "[A]
    4,	// "EXACT "[T]
    1,	// "CATS"[A]
    0,	// "CASTS "[C]
    1,	// " FACTS"[F]
    5,	// "FACTOR"[R]
    2,	// "RAT "[T]
    3,	// "ACRE"[E]
    2,	// "BUS "[S]
    2,	// "BUYS"[Y]
    4,	// " BUSES"[E]
    4,	// "CLUBS "[S]
    1,	// " CLUBBING"[C]
    3,	// "BUMPS "[P]
    2,	// "PART"[R]
    0,	// "STRING"[S]
    1,	// "RINGS "[I]
    3,	// "BELONG"[O]
    2,	// " CLOUD"[L]
    3,	// " FAVOR"[V]
    3,	// "CAREER"[E]
    1,	// " PLEASANT"[P]
    1,	// "MEMBER"[E]
    5,	// " EIGHT"[T]
    2,	// "DIRECTOR "[R]
    3,	// "INCOME"[O]
    1,	// "ALLOW "[L]
    1,	// " ELECTION"[E]
    4,	// " BEGUN"[U]
    3,	// " REMEMBER"[M]
};

