#include <sifteo.h>

// This file is autogenerated from dict/generate_dict.py

const unsigned PROTO_WORD_LIST_LENGTH = 28;

const static uint64_t protoWordList[] =
{
    0x8000000000001461L,		// ACE, length: 3, freq. cat.: 0
    0x8000000000005061L,		// ACT, length: 3, freq. cat.: 0
    0x80000000000001a1L,		// AM, length: 2, freq. cat.: 0
    0x1e2,		// BO, (bonus), length: 2, freq. cat.: 5
    0x80000000000061e2L,		// BOX, length: 3, freq. cat.: 0
    0x8000000000005023L,		// CAT, length: 3, freq. cat.: 0
    0x800000000002c824L,		// DARE, length: 4, freq. cat.: 1
    0x3a45,		// ERN, (bonus), length: 3, freq. cat.: 8
    0x8000000000068647L,		// GRAM, length: 4, freq. cat.: 3
    0x800000000003b828L,		// HANG, length: 4, freq. cat.: 1
    0x800000000ee4d828L,		// HAVING, length: 6, freq. cat.: 1
    0x8000000000058eacL,		// LUCK, length: 4, freq. cat.: 1
    0x8000000001958eacL,		// LUCKY, length: 5, freq. cat.: 1
    0x800000000000002dL,		// MA, length: 2, freq. cat.: 3
    0x80000006645a4f2dL,		// MYSTERY, length: 7, freq. cat.: 2
    0x80000000000051eeL,		// NOT, length: 3, freq. cat.: 0
    0x2b2b0,		// PULE, (bonus), length: 4, freq. cat.: 6
    0x800000000acd6ab0L,		// PUZZLE, length: 6, freq. cat.: 2
    0x80000000000204b2L,		// READ, length: 4, freq. cat.: 0
    0x800000000009a4b2L,		// REIS, length: 4, freq. cat.: 3
    0x8000000000e4ccb2L,		// RESIN, length: 5, freq. cat.: 3
    0x800000000003b932L,		// RING, length: 4, freq. cat.: 0
    0x8000000000003933L,		// SIN, length: 3, freq. cat.: 2
    0x800000000002c933L,		// SIRE, length: 4, freq. cat.: 3
    0x8000000000e2c933L,		// SIREN, length: 5, freq. cat.: 3
    0x800000000003b934L,		// TING, length: 4, freq. cat.: 3
    0x800000000ee4c934L,		// TIRING, length: 6, freq. cat.: 2
    0x80000000000039f4L,		// TON, length: 3, freq. cat.: 0
};
