#include <sifteo.h>

// This file is autogenerated from dict/generate_dict.py

const unsigned PROTO_WORD_LIST_LENGTH = 147;

const static uint64_t protoWordList[] =
{
    0x800000000002c861L,		// ACRE, length: 4, freq. cat.: 3
    0x8000000000005061L,		// ACT, length: 3, freq. cat.: 0
    0x800000000009d061L,		// ACTS, length: 4, freq. cat.: 1
    0x800000000177b181L,		// ALLOW, length: 5, freq. cat.: 0
    0x80000000000041a1L,		// AMP, length: 3, freq. cat.: 2
    0x8000000000005241L,		// ART, length: 3, freq. cat.: 0
    0x800000a0c264d241L,		// ARTIFACT, length: 8, freq. cat.: 3
    0x48e61,		// ASCI, (bonus), length: 4, freq. cat.: 7
    0x8000000000001ca2L,		// BEG, length: 3, freq. cat.: 0
    0x8000000000ea9ca2L,		// BEGUN, length: 5, freq. cat.: 0
    0x80000000007724a2L,		// BEING, length: 5, freq. cat.: 0
    0x800000000ee7b0a2L,		// BELONG, length: 6, freq. cat.: 0
    0x8000000000003aa2L,		// BUN, length: 3, freq. cat.: 3
    0x800000000002c823L,		// CARE, length: 4, freq. cat.: 0
    0x800000002452c823L,		// CAREER, length: 6, freq. cat.: 0
    0x80000000000a4c23L,		// CAST, length: 4, freq. cat.: 0
    0x80000000013a4c23L,		// CASTS, length: 5, freq. cat.: 2
    0x8000000000005023L,		// CAT, length: 3, freq. cat.: 0
    0x800000000009d023L,		// CATS, length: 4, freq. cat.: 2
    0x8000000000072503L,		// CHIN, length: 4, freq. cat.: 3
    0x800000000006d503L,		// CHUM, length: 4, freq. cat.: 3
    0x80000000004abd83L,		// CLOUD, length: 5, freq. cat.: 0
    0x80000000000725e3L,		// COIN, length: 4, freq. cat.: 2
    0x80000000000031e3L,		// COL, length: 3, freq. cat.: 3
    0x800000000002b5e3L,		// COME, length: 4, freq. cat.: 0
    0x4b9e3,		// CONI, (bonus), length: 4, freq. cat.: 8
    0x12a3,		// CUD, (bonus), length: 3, freq. cat.: 5
    0x800000000009c2a3L,		// CUPS, length: 4, freq. cat.: 2
    0x84ea3,		// CUSP, (bonus), length: 4, freq. cat.: 5
    0x800000002832c924L,		// DIRECT, length: 6, freq. cat.: 0
    0x80000093e832c924L,		// DIRECTOR, length: 8, freq. cat.: 0
    0x80000000000ccc25L,		// EASY, length: 4, freq. cat.: 0
    0x8000000001441d25L,		// EIGHT, length: 5, freq. cat.: 0
    0x8000000001419585L,		// ELECT, length: 5, freq. cat.: 0
    0x80000073d3419585L,		// ELECTION, length: 8, freq. cat.: 0
    0x4d85,		// ELS, (bonus), length: 3, freq. cat.: 7
    0x3a45,		// ERN, (bonus), length: 3, freq. cat.: 8
    0x2285,		// ETH, (bonus), length: 3, freq. cat.: 7
    0x8000000001418705L,		// EXACT, length: 5, freq. cat.: 1
    0x80000000000a0c26L,		// FACT, length: 4, freq. cat.: 0
    0x8000000024fa0c26L,		// FACTOR, length: 6, freq. cat.: 1
    0x80000000013a0c26L,		// FACTS, length: 5, freq. cat.: 1
    0x7c826,		// FARO, (bonus), length: 4, freq. cat.: 6
    0x800000000127d826L,		// FAVOR, length: 5, freq. cat.: 0
    0x8000000001441d26L,		// FIGHT, length: 5, freq. cat.: 0
    0x8000000000005126L,		// FIT, length: 3, freq. cat.: 0
    0x8000000001472586L,		// FLINT, length: 5, freq. cat.: 3
    0x80000000000049e6L,		// FOR, length: 3, freq. cat.: 0
    0x8000000000003e46L,		// FRO, length: 3, freq. cat.: 3
    0x8000000000003aa6L,		// FUN, length: 3, freq. cat.: 0
    0x8000000001973aa6L,		// FUNNY, length: 5, freq. cat.: 1
    0xab8a7,		// GENU, (bonus), length: 4, freq. cat.: 7
    0x1527,		// GIE, (bonus), length: 3, freq. cat.: 7
    0x8000000000003927L,		// GIN, length: 3, freq. cat.: 2
    0x8000002d12880647L,		// GRAPHITE, length: 8, freq. cat.: 3
    0x80000000005a0647L,		// GRATE, length: 5, freq. cat.: 3
    0x5b828,		// HANK, (bonus), length: 4, freq. cat.: 5
    0x8000000000005028L,		// HAT, length: 3, freq. cat.: 0
    0x80000000000048a8L,		// HER, length: 3, freq. cat.: 0
    0x8000000000040dc9L,		// INCH, length: 4, freq. cat.: 1
    0x800000000ad78dc9L,		// INCOME, length: 6, freq. cat.: 0
    0x8000000000002dc9L,		// INK, length: 3, freq. cat.: 2
    0x800000000042adc9L,		// INKED, length: 5, freq. cat.: 3
    0x800000002832cdc9L,		// INSECT, length: 6, freq. cat.: 2
    0x80000000000050aaL,		// JET, length: 3, freq. cat.: 2
    0x80000000019a50aaL,		// JETTY, length: 5, freq. cat.: 3
    0x800000000000512bL,		// KIT, length: 3, freq. cat.: 2
    0x80000000019a512bL,		// KITTY, length: 5, freq. cat.: 3
    0x8000000000005c2cL,		// LAW, length: 3, freq. cat.: 0
    0x80000000000050acL,		// LET, length: 3, freq. cat.: 0
    0x80000000000289ecL,		// LOBE, length: 4, freq. cat.: 3
    0x800000000003b9ecL,		// LONG, length: 4, freq. cat.: 0
    0x80000000000a3decL,		// LOOT, length: 4, freq. cat.: 3
    0x800000000002cdecL,		// LOSE, length: 4, freq. cat.: 0
    0x80000000000255ecL,		// LOUD, length: 4, freq. cat.: 0
    0x8000000000005decL,		// LOW, length: 3, freq. cat.: 0
    0x800000000000402dL,		// MAP, length: 3, freq. cat.: 0
    0x80000000000a4c2dL,		// MAST, length: 4, freq. cat.: 3
    0x800000000009d02dL,		// MATS, length: 4, freq. cat.: 3
    0x80000000245134adL,		// MEMBER, length: 6, freq. cat.: 0
    0x800000000002c8adL,		// MERE, length: 4, freq. cat.: 0
    0x800000000ac2112dL,		// MIDDLE, length: 6, freq. cat.: 0
    0x800000000002b12dL,		// MILE, length: 4, freq. cat.: 0
    0x800000000132b12dL,		// MILES, length: 5, freq. cat.: 1
    0x4d2d,		// MIS, (bonus), length: 3, freq. cat.: 8
    0x985ed,		// MOAS, (bonus), length: 4, freq. cat.: 7
    0x800000000690cdedL,		// MOSAIC, length: 6, freq. cat.: 3
    0x8000000000040eadL,		// MUCH, length: 4, freq. cat.: 0
    0x800000000000412eL,		// NIP, length: 3, freq. cat.: 3
    0x800000000000512eL,		// NIT, length: 3, freq. cat.: 3
    0xaae,		// NUB, (bonus), length: 3, freq. cat.: 5
    0x9958f,		// OLES, (bonus), length: 4, freq. cat.: 6
    0x80000000265b258fL,		// OLIVES, length: 6, freq. cat.: 3
    0xb18f,		// OLLA, (bonus), length: 4, freq. cat.: 7
    0x3430,		// PAM, (bonus), length: 3, freq. cat.: 7
    0x80000000000a4c30L,		// PAST, length: 4, freq. cat.: 0
    0x800000000009d030L,		// PATS, length: 4, freq. cat.: 3
    0x8000000018f950b0L,		// PETROL, length: 6, freq. cat.: 1
    0x80000da958f950b0L,		// PETROLEUM, length: 9, freq. cat.: 3
    0x8000000000003930L,		// PIN, length: 3, freq. cat.: 2
    0x8000000001470590L,		// PLANT, length: 5, freq. cat.: 0
    0x8000000001309590L,		// PLEAS, length: 5, freq. cat.: 3
    0x800000a383309590L,		// PLEASANT, length: 8, freq. cat.: 0
    0x8000000000005032L,		// RAT, length: 3, freq. cat.: 2
    0x80000000008184b2L,		// REACH, length: 5, freq. cat.: 0
    0x800000000009a4b2L,		// REIS, length: 4, freq. cat.: 3
    0x8000009144d2b4b2L,		// REMEMBER, length: 8, freq. cat.: 0
    0x8000000000e4ccb2L,		// RESIN, length: 5, freq. cat.: 3
    0x800000000003b932L,		// RING, length: 4, freq. cat.: 0
    0x800000000133b932L,		// RINGS, length: 5, freq. cat.: 2
    0x8000000000005df2L,		// ROW, length: 3, freq. cat.: 0
    0x8000000000003ab2L,		// RUN, length: 3, freq. cat.: 0
    0x8000000001973ab2L,		// RUNNY, length: 5, freq. cat.: 3
    0x8000000000000c33L,		// SAC, length: 3, freq. cat.: 3
    0x13a0473,		// SCATS, (bonus), length: 5, freq. cat.: 5
    0x8000000008e78cb3L,		// SECOND, length: 6, freq. cat.: 0
    0x80000000000a0cb3L,		// SECT, length: 4, freq. cat.: 2
    0x30b3,		// SEL, (bonus), length: 3, freq. cat.: 8
    0x80000000000238b3L,		// SEND, length: 4, freq. cat.: 0
    0x8000000000071d33L,		// SIGN, length: 4, freq. cat.: 0
    0x3533,		// SIM, (bonus), length: 3, freq. cat.: 8
    0x8000000000003933L,		// SIN, length: 3, freq. cat.: 2
    0x800000000003b933L,		// SING, length: 4, freq. cat.: 0
    0x8000000000004933L,		// SIR, length: 3, freq. cat.: 0
    0x800000000002c933L,		// SIRE, length: 4, freq. cat.: 3
    0x8000000000e2c933L,		// SIREN, length: 5, freq. cat.: 3
    0x80000000005625b3L,		// SMILE, length: 5, freq. cat.: 1
    0x80000000000a2613L,		// SPIT, length: 4, freq. cat.: 2
    0x2653,		// SRI, (bonus), length: 3, freq. cat.: 7
    0x8000000001068693L,		// STAMP, length: 5, freq. cat.: 0
    0x8000000000092693L,		// STIR, length: 4, freq. cat.: 2
    0x800000000ee4ca93L,		// STRING, length: 6, freq. cat.: 0
    0x8000000000004834L,		// TAR, length: 3, freq. cat.: 3
    0x30b4,		// TEL, (bonus), length: 3, freq. cat.: 5
    0x5cb4,		// TEW, (bonus), length: 3, freq. cat.: 8
    0x8000000000b70514L,		// THANK, length: 5, freq. cat.: 0
    0x8000000000001514L,		// THE, length: 3, freq. cat.: 0
    0x8000000000003934L,		// TIN, length: 3, freq. cat.: 1
    0x800000000009c134L,		// TIPS, length: 4, freq. cat.: 2
    0x8000000000063df4L,		// TOOL, length: 4, freq. cat.: 2
    0x80000000333095d5L,		// UNEASY, length: 6, freq. cat.: 2
    0x8000000000099536L,		// VIES, length: 4, freq. cat.: 3
    0x63d36,		// VIOL, (bonus), length: 4, freq. cat.: 5
    0x800000000002cd36L,		// VISE, length: 4, freq. cat.: 3
    0x80000000000050b7L,		// WET, length: 3, freq. cat.: 2
    0x80000000005a2517L,		// WHITE, length: 5, freq. cat.: 0
    0x8000000000773e57L,		// WRONG, length: 5, freq. cat.: 0
};
