#!/usr/bin/env python
#
# Generator script for proof_html.cpp
#
# STIR -- Sifteo Tiled Image Reducer
# M. Elizabeth Scott <beth@sifteo.com>
#
# Copyright <c> 2011 Sifteo, Inc. All rights reserved.
#

header = """
<!DOCTYPE html>
<html>
<head> 
  <script> 
 
     function tileRef(i) { 
       document.write('<img src="' + poolPrefix + pool[i] + '" width="8" height="8" />'); 
     } 
 
     function tileRange(begin, end) { 
       for (var i = begin; i < end; i++) 
         tileRef(i); 
     } 
 
     function tileArray(arr) { 
       for (var i = 0; i < arr.length; i++) 
         tileRef(arr[i]); 
     } 
 
  </script> 
  <style> 
 
    body { 
      color: #eee; 
      background: #222; 
      font-family: verdana, tahoma, helvetica, arial, sans-serif; 
      font-size: 12px; 
      margin: 10px 5px 50px 5px; 
    } 
 
    div.grid { 
      float: left; 
    } 
 
    div.clear { 
      clear: both; 
    } 
 
    h1 { 
      background: #fff; 
      color: #222; 
      font-size: 22px; 
      font-weight: normal; 
      clear: both; 
      padding: 10px; 
      margin: 0; 
    } 
 
    h2 { 
      color: #fff; 
      font-size: 16px; 
      font-weight: normal; 
      clear: both; 
      padding: 10px; 
      margin: 0; 
    } 
 
    p { 
      padding: 0 10px; 
    } 
 
  </style> 
</head> 
<body> 
"""

cppTemplate = """
/* -*- mode: C; c-basic-offset: 4; intent-tabs-mode: nil -*-
 *
 * STIR -- Sifteo Tiled Image Reducer
 * M. Elizabeth Scott <beth@sifteo.com>
 *
 * Copyright <c> 2011 Sifteo, Inc. All rights reserved.
 */

/*
 * AUTOMATICALLY GENERATED by proof_html.py
 * Do not edit by hand!
 */

#include "proof.h"

const char *Stir::ProofWriter::header =
%s;
"""

###########################################################

import sys

def cString(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    lines = s.split('\n')
    return '\n'.join(['    "%s\\n"' % l for l in lines])

f = open(sys.argv[1], 'w')
f.write(cppTemplate.lstrip() % (
        cString(header.lstrip()),
        ))
