/* -*- mode: C; c-basic-offset: 4; intent-tabs-mode: nil -*-
 *
 * STIR -- Sifteo Tiled Image Reducer
 * M. Elizabeth Scott <beth@sifteo.com>
 *
 * Copyright <c> 2011 Sifteo, Inc. All rights reserved.
 */

/*
 * AUTOMATICALLY GENERATED by proof_html.py
 * Do not edit by hand!
 */

#include "proof.h"

const char *Stir::ProofWriter::header =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head> \n"
    "  <script> \n"
    " \n"
    "     function tileRef(i) { \n"
    "       document.write('<img src=\"' + poolPrefix + pool[i] + '\" width=\"8\" height=\"8\" />'); \n"
    "     } \n"
    " \n"
    "     function tileRange(begin, end) { \n"
    "       for (var i = begin; i < end; i++) \n"
    "         tileRef(i); \n"
    "     } \n"
    " \n"
    "     function tileArray(arr) { \n"
    "       for (var i = 0; i < arr.length; i++) \n"
    "         tileRef(arr[i]); \n"
    "     } \n"
    " \n"
    "  </script> \n"
    "  <style> \n"
    " \n"
    "    body { \n"
    "      color: #eee; \n"
    "      background: #222; \n"
    "      font-family: verdana, tahoma, helvetica, arial, sans-serif; \n"
    "      font-size: 12px; \n"
    "      margin: 10px 5px 50px 5px; \n"
    "    } \n"
    " \n"
    "    div.grid { \n"
    "      float: left; \n"
    "    } \n"
    " \n"
    "    div.clear { \n"
    "      clear: both; \n"
    "    } \n"
    " \n"
    "    h1 { \n"
    "      background: #fff; \n"
    "      color: #222; \n"
    "      font-size: 22px; \n"
    "      font-weight: normal; \n"
    "      clear: both; \n"
    "      padding: 10px; \n"
    "      margin: 0; \n"
    "    } \n"
    " \n"
    "    h2 { \n"
    "      color: #fff; \n"
    "      font-size: 16px; \n"
    "      font-weight: normal; \n"
    "      clear: both; \n"
    "      padding: 10px; \n"
    "      margin: 0; \n"
    "    } \n"
    " \n"
    "    p { \n"
    "      padding: 0 10px; \n"
    "    } \n"
    " \n"
    "  </style> \n"
    "</head> \n"
    "<body> \n"
    "\n";
