#!/usr/bin/env python
#
# Generator script for proof_html.cpp
#
# STIR -- Sifteo Tiled Image Reducer
# M. Elizabeth Scott <beth@sifteo.com>
#
# Copyright <c> 2011 Sifteo, Inc. All rights reserved.
#

header = """
<!DOCTYPE html>
<html>
<head> 
  <script> 
 
     /*
      * Define a tile pool (per-group)
      */

     function defineTiles(prefix, tiles) {
       for (var i = 0; i < tiles.length; i++) {
         var img = new Image(8, 8);
         img.src = prefix + tiles[i];
         tiles[i] = img;
       }
       return tiles;
     }

     /*
      * Object for a single TileGrid, with some interactive features.
      * Renders onto an HTML5 Canvas
      */

     allTileGrids = []

     function TileGrid(pool, canvasId) {
         allTileGrids.push(this);
         this.pool = pool;
         this.canvas = document.getElementById(canvasId);
         this.ctx = this.canvas.getContext("2d");
         this.width = this.canvas.width / 8;
         this.height = this.canvas.height / 8;
     }

     TileGrid.prototype.range = function(begin, end) {
         this.tiles = [];
         for (var i = begin; i < end; i++)
             this.tiles[i - begin] = i;
     }

     TileGrid.prototype.array = function(a) {
         this.tiles = a;
     }

     TileGrid.prototype.draw = function() {
       var i = 0;

       for (var y = 0; y < this.height; y++)
         for (var x = 0; x < this.width; x++) {

           this.ctx.drawImage(this.pool[this.tiles[i]], x*8, y*8);

           i++;
           if (i >= this.tiles.length)
             return;
         }
     }

     /*
      * Draw all TileGrids after our images have loaded
      */

     function drawAllTileGrids() {
       for (var i in allTileGrids)
         allTileGrids[i].draw();
     }
 
  </script> 
  <style> 
 
    body { 
      color: #eee; 
      background: #222; 
      font-family: verdana, tahoma, helvetica, arial, sans-serif; 
      font-size: 12px; 
      margin: 10px 5px 50px 5px; 
    } 
  
    h1 { 
      background: #fff; 
      color: #222; 
      font-size: 22px; 
      font-weight: normal; 
      padding: 10px; 
      margin: 0; 
    } 
 
    h2 { 
      color: #fff; 
      font-size: 16px; 
      font-weight: normal; 
      padding: 10px; 
      margin: 0; 
    } 
 
    p { 
      padding: 0 10px; 
    } 

    canvas {
      padding: 0;
      margin: 0;
    }
 
  </style> 
</head> 
<body onload="drawAllTileGrids()"> 
"""

cppTemplate = """
/* -*- mode: C; c-basic-offset: 4; intent-tabs-mode: nil -*-
 *
 * STIR -- Sifteo Tiled Image Reducer
 * M. Elizabeth Scott <beth@sifteo.com>
 *
 * Copyright <c> 2011 Sifteo, Inc. All rights reserved.
 */

/*
 * AUTOMATICALLY GENERATED by proof_html.py
 * Do not edit by hand!
 */

#include "proof.h"

const char *Stir::ProofWriter::header =
%s;
"""

###########################################################

import sys

def cString(s):
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    lines = s.split('\n')
    return '\n'.join(['    "%s\\n"' % l for l in lines])

f = open(sys.argv[1], 'w')
f.write(cppTemplate.lstrip() % (
        cString(header.lstrip()),
        ))
