# Common makefile rules for SDK unit tests.

SIFTULATOR_FLAGS = --headless
GENERATED_FILES += tests.stamp

all: tests.stamp

tests.stamp: $(BIN)
	@echo "\n================= Running SDK Test:" $(APP) "\n"
	siftulator $(SIFTULATOR_FLAGS) $(BIN)
	echo > $@

.PHONY: all
