BIN_SIM = hello.sim
OBJS_SIM = $(ASSETS).gen.sim.o main.sim.o

BIN_STM32 = hello.stm32
OBJS_STM32 = $(ASSETS).gen.stm32.o main.stm32.o

CDEPS += *.png $(ASSETS).lua

TC_DIR = ../../..
include $(TC_DIR)/firmware/master/Makefile.rules
