TC_DIR = ../../..
include $(TC_DIR)/firmware/master/Makefile.defs

BIN_SIM = neighbor.sim$(BIN_EXT)
OBJS_SIM = main.sim.o

BIN_STM32 = neighbor.tm32
OBJS_STM32 = main.stm32.o

include $(TC_DIR)/firmware/master/Makefile.rules
