all: $(BIN_DIR)/$(BIN)$(BIN_EXT)

# Disable implicit rules. Speeds up make, especially on Windows.
.SUFFIXES:

ifeq ($(BUILD_PLATFORM),windows32)

# Win32 Link: Stripped and packed binaries, and separate debug symbols.
# upx doesn't like overwriting the output file - rm it in case we're not building after clean
$(BIN_DIR)/$(BIN)$(BIN_EXT): $(OBJS)
	$(CC) -o "src/$(BIN)-d.exe" $(OBJS) $(LDFLAGS)
	$(OBJCOPY) --only-keep-debug "src/$(BIN)-d.exe" "$(BIN).dSYM"
	$(STRIP) -s "src/$(BIN)-d$(BIN_EXT)" -o "src/$(BIN)-stripped$(BIN_EXT)"
	rm -f "$(BIN_DIR)/$(BIN)$(BIN_EXT)"
	$(UPX) -o "$(BIN_DIR)/$(BIN)$(BIN_EXT)" "src/$(BIN)-stripped$(BIN_EXT)"
else
ifeq ($(BUILD_PLATFORM),Darwin)
# Mac OS Link: Create an app bundle with a stripped binary,
# and a separate (lowercase) symlink for easier command line use.
$(BIN_DIR)/$(BIN): $(BIN_DIR)/$(BIN).app
	ln -sf $(BIN).app/Contents/MacOS/$(BIN) $(BIN_DIR)/$(LOWERCASE_BIN)
$(BIN_DIR)/$(BIN).app: $(OBJS)
	$(CC) -o "src/$(BIN)-d" $(OBJS) $(LDFLAGS)
	mkdir -p "$(BIN_DIR)/$(BIN).app/Contents/MacOS"
	mkdir -p "$(BIN_DIR)/$(BIN).app/Contents/Resources"
	cp resources/Info.plist "$(BIN_DIR)/$(BIN).app/Contents/Info.plist"
	cp resources/siftrunner_icon.icns "$(BIN_DIR)/$(BIN).app/Contents/Resources/$(BIN).icns"
	$(STRIP) -Sx "src/$(BIN)-d" -o "$(BIN_DIR)/$(BIN).app/contents/MacOS/$(BIN)"
	touch "$@"
else
# Default link (for Linux)
$(BIN_DIR)/$(BIN): $(BIN_DIR)/$(LOWERCASE_BIN)
$(BIN_DIR)/$(LOWERCASE_BIN): $(OBJS)
	$(CC) -o "src/$(LOWERCASE_BIN)-d" $(OBJS) $(LDFLAGS)
	$(STRIP) -s "src/$(LOWERCASE_BIN)-d" -o "$@"
endif
endif

%.o: %.cpp
	$(CC) -c $(CCFLAGS) $*.cpp -o $*.o

%.o: %.c
	$(CC) -c $(CFLAGS) $*.c -o $*.o

%.o: %.m
	$(CC) -c $(MFLAGS) $*.m -o $*.o

%.o: %.rc
	$(WINDRES) -i $< -o $@

resources/data.cpp: $(DATADEPS)
	$(PYTHON) resources/bin2c.py

resources/firmware-sbt.cpp: $(FIRMWARE_RST)
	$(PYTHON) resources/firmware-sbt.py $(FIRMWARE_RST)

.PHONY: clean firmware

clean:
	rm -Rf $(BIN_DIR)/$(BIN)$(BIN_EXT)
	rm -Rf $(BIN_DIR)/$(BIN)$(BIN_EXT).app
	rm -Rf $(OBJS) $(DEPFILES) $(BIN).dSYM
	rm -Rf $(GENERATED_FILES)

