/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup Ball1Group;
extern const Sifteo::AssetImage Ball1;
extern Sifteo::AssetGroup Ball2Group;
extern const Sifteo::AssetImage Ball2;
extern Sifteo::AssetGroup Ball3Group;
extern const Sifteo::AssetImage Ball3;
extern Sifteo::AssetGroup NumberGroup1;
extern Sifteo::AssetGroup NumberGroup6;
extern Sifteo::AssetGroup NumberGroup2;
extern Sifteo::AssetGroup NumberGroup3;
extern Sifteo::AssetGroup NumberGroup4;
extern Sifteo::AssetGroup NumberGroup5;
extern Sifteo::AssetGroup NumberGroup14;
extern Sifteo::AssetGroup NumberGroup7;
extern Sifteo::AssetGroup NumberGroup8;
extern Sifteo::AssetGroup NumberGroup9;
extern Sifteo::AssetGroup NumberGroup10;
extern Sifteo::AssetGroup NumberGroup11;
extern Sifteo::AssetGroup NumberGroup12;
extern Sifteo::AssetGroup NumberGroup13;
extern Sifteo::AssetGroup NumberGroup15;
extern Sifteo::AssetGroup NumberGroup16;
extern Sifteo::AssetGroup NumberGroup17;
extern Sifteo::AssetGroup NumberGroup18;
extern Sifteo::AssetGroup NumberGroup19;
extern Sifteo::AssetGroup NumberGroup20;
extern Sifteo::AssetGroup NumberGroup21;
extern Sifteo::AssetGroup NumberGroup22;
extern Sifteo::AssetGroup NumberGroup23;
extern Sifteo::AssetGroup NumberGroup24;
extern Sifteo::AssetGroup NumberGroup25;
extern const Sifteo::AssetImage NumberList[25];
