APP = test-assetslot

include $(SDK_DIR)/Makefile.defs

OBJS = $(ASSETS).gen.o main.o
ASSETDEPS += images/*.png $(ASSETS).lua

include $(TC_DIR)/test/sdk/Makefile.rules
include $(SDK_DIR)/Makefile.rules
