--GENERATED BY SANDWICH.PY, DO NOT EDIT BY HAND

-- MAP IMAGES
TileSet_castle = image{ "castle.png", width=16, height=16 }
Overlay_castle = image{ "castle_overlay.png", width=16, height=16 }
Blank_castle = image{ "castle_blank.png", width=128, height=128 }
TileSet_dungeon = image{ "dungeon.png", width=16, height=16 }
Overlay_dungeon = image{ "dungeon_overlay.png", width=16, height=16 }
Blank_dungeon = image{ "dungeon_blank.png", width=128, height=128 }
TileSet_forest = image{ "forest.png", width=16, height=16 }
Blank_forest = image{ "forest_blank.png", width=128, height=128 }

-- DIALOG IMAGES
NPC_skeleton = image{ "skeleton.png", width=32, height=32, pinned=true }
NPC_Detail_dialog = image{ "dialog.png" }
