    0,	// EVERYONE, bonus anagrams: []
    0,	// WITHIN, bonus anagrams: []
    0,	// ROYAL, bonus anagrams: []
    0,	// DIRECTION, bonus anagrams: []
    0,	// OCCUPY, bonus anagrams: []
    0,	// DANCE, bonus anagrams: []
    0,	// DIRECTOR, bonus anagrams: []
    0,	// CHILDREN, bonus anagrams: []
    0,	// PROPERTY, bonus anagrams: []
    0,	// HAPPENED, bonus anagrams: []
    0,	// AFFAIR, bonus anagrams: []
    0,	// PRACTICE, bonus anagrams: []
    0,	// WONDERFUL, bonus anagrams: []
    0,	// BESIDE, bonus anagrams: []
    0,	// UNLESS, bonus anagrams: []
    0,	// MIDDLE, bonus anagrams: []
    0,	// VESSEL, bonus anagrams: []
    0,	// TERMS, bonus anagrams: []
    0,	// WHOLE, bonus anagrams: []
    0,	// ANYTHING, bonus anagrams: []
    0,	// SURFACE, bonus anagrams: []
    0,	// COMPOUND, bonus anagrams: []
    0,	// TURNED, bonus anagrams: []
    0,	// REMEMBER, bonus anagrams: []
    0,	// MEMBER, bonus anagrams: []
    0,	// OBJECTION, bonus anagrams: []
    0,	// SECOND, bonus anagrams: []
    0,	// FIGHT, bonus anagrams: []
    0,	// PERSONAL, bonus anagrams: []
    0,	// MAJORITY, bonus anagrams: []
    0,	// WRONG, bonus anagrams: []
    0,	// NOTICE, bonus anagrams: []
    0,	// TRIANGLE, bonus anagrams: []
    0,	// ELECTRIC, bonus anagrams: []
    0,	// SUDDENLY, bonus anagrams: []
    0,	// ELECTION, bonus anagrams: []
    0,	// BECOME, bonus anagrams: []
    0,	// SOUTHERN, bonus anagrams: []
    0,	// BUILDING, bonus anagrams: []
    0,	// NORTHERN, bonus anagrams: []
    0,	// WINDOW, bonus anagrams: []
    1,	// ALTHOUGH, bonus anagrams: ['ALTHO']
    1,	// DURING, bonus anagrams: ['DUNG']
    1,	// VOICE, bonus anagrams: ['VOE']
    1,	// ORDER, bonus anagrams: ['RODE']
    1,	// MOTION, bonus anagrams: ['MONO']
    1,	// ISSUE, bonus anagrams: ['SUE']
    1,	// FRONT, bonus anagrams: ['TON']
    1,	// SHOWN, bonus anagrams: ['WON']
    1,	// FIGURE, bonus anagrams: ['REIF']
    1,	// FLOOR, bonus anagrams: ['FRO']
    1,	// NATIONAL, bonus anagrams: ['NATAL']
    1,	// FAVOR, bonus anagrams: ['FRO']
    1,	// SHOULDER, bonus anagrams: ['SHOER']
    1,	// READY, bonus anagrams: ['DARE']
    1,	// PROGRESS, bonus anagrams: ['OGRESS']
    1,	// RETURN, bonus anagrams: ['TURNER']
    1,	// TOUCH, bonus anagrams: ['OUCH']
    1,	// STAND, bonus anagrams: ['TAS']
    1,	// FOLLOWING, bonus anagrams: ['LOWING']
    1,	// BELONG, bonus anagrams: ['LOBE']
    1,	// PASSED, bonus anagrams: ['APED']
    1,	// PRESS, bonus anagrams: ['REP']
    1,	// FINISH, bonus anagrams: ['SHIN']
    1,	// THANK, bonus anagrams: ['HANK']
    1,	// AHEAD, bonus anagrams: ['DAH']
    1,	// ALLOW, bonus anagrams: ['OLLA']
    1,	// VISIT, bonus anagrams: ['TIS']
    1,	// CAREER, bonus anagrams: ['ACRE']
    1,	// DROWN, bonus anagrams: ['WON']
    1,	// THESE, bonus anagrams: ['ETH']
    1,	// SPRING, bonus anagrams: ['RIPS']
    1,	// CORNER, bonus anagrams: ['CORE']
    1,	// HEARD, bonus anagrams: ['RAD']
    1,	// RESTRAIN, bonus anagrams: ['RESIN']
    1,	// UNABLE, bonus anagrams: ['BALE']
    1,	// PUSHED, bonus anagrams: ['EDHS']
    1,	// REPLY, bonus anagrams: ['REP']
    1,	// THICK, bonus anagrams: ['HICK']
    1,	// THING, bonus anagrams: ['GIN']
    1,	// WINTER, bonus anagrams: ['RENT']
    1,	// ISLAND, bonus anagrams: ['SIAL']
    1,	// AWFUL, bonus anagrams: ['AWL']
    1,	// QUIET, bonus anagrams: ['ETUI']
    1,	// EMPIRE, bonus anagrams: ['PIER']
    1,	// CRIED, bonus anagrams: ['IRED']
    1,	// REACH, bonus anagrams: ['ACRE']
    1,	// HOURS, bonus anagrams: ['OHS']
    1,	// FRUIT, bonus anagrams: ['FUR']
    1,	// IMPRISON, bonus anagrams: ['PRIONS']
    1,	// RETIRE, bonus anagrams: ['TIER']
    1,	// STRING, bonus anagrams: ['STIR']
    1,	// PLEASANT, bonus anagrams: ['PLEAS']
    1,	// NEARLY, bonus anagrams: ['ARYL']
    1,	// TOWARD, bonus anagrams: ['WARD']
    1,	// ELECT, bonus anagrams: ['TEL']
    1,	// BEING, bonus anagrams: ['GIN']
    1,	// BECAME, bonus anagrams: ['ACME']
    2,	// INFORM, bonus anagrams: ['INFO', 'FOIN']
    2,	// DELAY, bonus anagrams: ['LADE', 'DEY']
    2,	// WOMAN, bonus anagrams: ['NAM', 'WON']
    2,	// FORCE, bonus anagrams: ['CERO', 'FRO']
    2,	// HUMAN, bonus anagrams: ['HUN', 'NAM']
    2,	// MOTHER, bonus anagrams: ['MOTH', 'OMER']
    2,	// FORTY, bonus anagrams: ['TYRO', 'FRO']
    2,	// PARTY, bonus anagrams: ['YAP', 'TRAP']
    2,	// CAUSE, bonus anagrams: ['SUE', 'ACE']
    2,	// HOUSE, bonus anagrams: ['HOE', 'SUE']
    2,	// WATER, bonus anagrams: ['RAW', 'RET']
    2,	// INCOME, bonus anagrams: ['CONI', 'COIN']
    2,	// DEATH, bonus anagrams: ['HATED', 'EDH']
    2,	// GUEST, bonus anagrams: ['TUG', 'GUT']
    2,	// DESIGN, bonus anagrams: ['SIGNED', 'SINGED']
    2,	// SUFFER, bonus anagrams: ['SUER', 'USER']
    2,	// CENTS, bonus anagrams: ['SCENT', 'SEC']
    2,	// ASKED, bonus anagrams: ['SKA', 'DESK']
    2,	// EIGHT, bonus anagrams: ['GIE', 'ETH']
    2,	// FILLED, bonus anagrams: ['DEFI', 'DELL']
    2,	// BROWN, bonus anagrams: ['BROW', 'WON']
    2,	// WORTH, bonus anagrams: ['THRO', 'WROTH']
    2,	// UNTIL, bonus anagrams: ['TIL', 'LIT']
    2,	// EXTRA, bonus anagrams: ['EAR', 'ERA']
    2,	// OFFER, bonus anagrams: ['REF', 'FER']
    2,	// FOURTH, bonus anagrams: ['THRU', 'RUTH']
    2,	// ALONE, bonus anagrams: ['ALE', 'EON']
    2,	// SOLVE, bonus anagrams: ['SOL', 'LOVES']
    2,	// SUMMER, bonus anagrams: ['SUER', 'USER']
    2,	// SMALL, bonus anagrams: ['LAMS', 'ALMS']
    2,	// CATCH, bonus anagrams: ['TACH', 'CHAT']
    2,	// KNOWN, bonus anagrams: ['WON', 'WONK']
    2,	// WOMEN, bonus anagrams: ['MEOW', 'WON']
    2,	// LESSON, bonus anagrams: ['LENO', 'NOEL']
    2,	// FINISHED, bonus anagrams: ['SHIED', 'FINED']
    2,	// DIVIDE, bonus anagrams: ['VIED', 'VIDE']
    2,	// YOUNG, bonus anagrams: ['GOY', 'GNU']
    2,	// SINGLE, bonus anagrams: ['ISLE', 'LEIS']
    2,	// LEARN, bonus anagrams: ['LEAR', 'RALE']
    2,	// OFTEN, bonus anagrams: ['FON', 'NET']
    2,	// ALIKE, bonus anagrams: ['AIL', 'KEA']
    2,	// CLOUD, bonus anagrams: ['CUD', 'COL']
    2,	// THEIR, bonus anagrams: ['HET', 'HEIR']
    2,	// OTHER, bonus anagrams: ['TOR', 'ROT']
    2,	// THINK, bonus anagrams: ['KIN', 'INK']
    2,	// CARRY, bonus anagrams: ['CRY', 'ARC']
    3,	// WHOSE, bonus anagrams: ['SEW', 'HOSE', 'HOES']
    3,	// OBTAIN, bonus anagrams: ['TAIN', 'BOTA', 'BONITA']
    3,	// REPAIR, bonus anagrams: ['PARE', 'REAP', 'APER']
    3,	// EVERY, bonus anagrams: ['VEE', 'RYE', 'EVE']
    3,	// TRACK, bonus anagrams: ['RAT', 'RACK', 'TAR']
    3,	// TEACH, bonus anagrams: ['CHEAT', 'TEA', 'TAE']
    3,	// BUILT, bonus anagrams: ['LIT', 'TIL', 'TUB']
    3,	// CLEAN, bonus anagrams: ['ELAN', 'CEL', 'LEAN']
    3,	// AFTER, bonus anagrams: ['AFT', 'ERA', 'REFT']
    3,	// STICK, bonus anagrams: ['TICKS', 'TIS', 'TICK']
    3,	// BEGUN, bonus anagrams: ['NUB', 'GENU', 'BUN']
    3,	// THOSE, bonus anagrams: ['THO', 'HOSE', 'HOES']
    3,	// HORSE, bonus anagrams: ['ORES', 'ROES', 'HES']
    3,	// SELECT, bonus anagrams: ['SEEL', 'SECT', 'LEES']
    3,	// REALLY, bonus anagrams: ['RELY', 'LYRE', 'ALLY']
    3,	// BEGIN, bonus anagrams: ['BIN', 'NIB', 'BINGE']
    3,	// CENTER, bonus anagrams: ['CERE', 'CENTRE', 'RENT']
    3,	// DOCTOR, bonus anagrams: ['ORDO', 'ROOD', 'ODOR']
    3,	// SIGHT, bonus anagrams: ['SIGH', 'TIS', 'GHIS']
    3,	// SHARP, bonus anagrams: ['SHA', 'HARPS', 'HARP']
    3,	// RESULT, bonus anagrams: ['SUTLER', 'SUER', 'USER']
    3,	// UNDER, bonus anagrams: ['NUDE', 'UNDE', 'NUDER']
    3,	// RAISE, bonus anagrams: ['RES', 'RIA', 'SER']
    3,	// HEART, bonus anagrams: ['HET', 'TAR', 'RAT']
    3,	// COLOR, bonus anagrams: ['ROC', 'COR', 'LOCO']
    3,	// WORDS, bonus anagrams: ['SOW', 'WOS', 'SWORD']
    3,	// STILL, bonus anagrams: ['TILLS', 'TIS', 'TILL']
    3,	// DOZEN, bonus anagrams: ['ZONED', 'ZONE', 'DEN']
    3,	// SINCE, bonus anagrams: ['SEC', 'SIN', 'INS']
    3,	// SHALL, bonus anagrams: ['HALLS', 'SHA', 'HALL']
    3,	// EVENT, bonus anagrams: ['VET', 'NEVE', 'NET']
    3,	// DOUBT, bonus anagrams: ['TOD', 'TUB', 'DOT']
    3,	// NORTH, bonus anagrams: ['NTH', 'THORN', 'THRO']
    3,	// NEVER, bonus anagrams: ['NERVE', 'ERN', 'VEER']
    3,	// ASSURE, bonus anagrams: ['USER', 'SUER', 'ERAS']
    3,	// CALLED, bonus anagrams: ['DELL', 'CADE', 'ACED']
    3,	// MEANT, bonus anagrams: ['ANT', 'MET', 'TAN']
    3,	// LOCAL, bonus anagrams: ['COAL', 'COL', 'COLA']
    3,	// WROTE, bonus anagrams: ['WET', 'TEW', 'ROTE']
    3,	// INSIDE, bonus anagrams: ['DENI', 'NISI', 'NIDE']
    4,	// RAPID, bonus anagrams: ['PAR', 'PADI', 'RAP', 'RID']
    4,	// PEOPLE, bonus anagrams: ['PEPO', 'POPE', 'PELE', 'PEEL']
    4,	// REMAIN, bonus anagrams: ['MARE', 'AMIN', 'REAM', 'REIN']
    4,	// MAYOR, bonus anagrams: ['MORAY', 'ROM', 'MOR', 'YAM']
    4,	// FOREST, bonus anagrams: ['RETS', 'FOSTER', 'FORE', 'ERST']
    4,	// LEAST, bonus anagrams: ['TEL', 'TAS', 'SALE', 'LEAS']
    4,	// CHART, bonus anagrams: ['TAR', 'CHAR', 'RAT', 'ARCH']
    4,	// STAMP, bonus anagrams: ['MATS', 'MAST', 'AMP', 'PAM']
    4,	// METAL, bonus anagrams: ['MEL', 'TAME', 'META', 'LAT']
    4,	// TODAY, bonus anagrams: ['TOY', 'TOAD', 'DATO', 'TOADY']
    4,	// SENSE, bonus anagrams: ['ESS', 'SENE', 'ENS', 'SEN']
    4,	// STONE, bonus anagrams: ['ENS', 'SOT', 'TONES', 'SEN']
    4,	// COAST, bonus anagrams: ['COT', 'TAS', 'ASCOT', 'OCAS']
    4,	// SHAPE, bonus anagrams: ['EPHAS', 'PES', 'SHA', 'EPHA']
    4,	// SPREAD, bonus anagrams: ['SPADER', 'REPS', 'DAPS', 'DARE']
    4,	// CLOSE, bonus anagrams: ['OLES', 'COLES', 'SEC', 'COL']
    4,	// EARLY, bonus anagrams: ['LYE', 'ARYL', 'EAR', 'ERA']
    4,	// ENTIRE, bonus anagrams: ['ERNE', 'RETINE', 'TINE', 'TIER']
    4,	// THREE, bonus anagrams: ['ETHER', 'ERE', 'ETH', 'REE']
    4,	// LEDGE, bonus anagrams: ['LEG', 'DEL', 'GEED', 'GEL']
    4,	// FIELD, bonus anagrams: ['FID', 'ELD', 'DEL', 'FILED']
    5,	// LATER, bonus anagrams: ['TELA', 'RET', 'TEAL', 'ALTER', 'LAR']
    5,	// ESCAPE, bonus anagrams: ['PEES', 'SEEP', 'ACES', 'CAPE', 'PEACES']
    5,	// TRAIN, bonus anagrams: ['TAR', 'RANI', 'RAT', 'TIN', 'NIT']
    5,	// CLEAR, bonus anagrams: ['CEL', 'LEAR', 'ARC', 'CARLE', 'RALE']
    5,	// EARTH, bonus anagrams: ['ERA', 'RATHE', 'ETH', 'EAR', 'RATH']
    5,	// PAPER, bonus anagrams: ['PAP', 'APER', 'REP', 'PARE', 'REAP']
    5,	// LISTEN, bonus anagrams: ['NEST', 'LIEN', 'LITS', 'ENLIST', 'NETS']
    5,	// TRADE, bonus anagrams: ['TAR', 'TED', 'RAT', 'TARED', 'DERAT']
    5,	// TABLE, bonus anagrams: ['ATE', 'BLAT', 'TAE', 'ETA', 'BLATE']
    5,	// SPEED, bonus anagrams: ['DEEPS', 'PEDES', 'PES', 'EDS', 'PEED']
    5,	// ALMOST, bonus anagrams: ['LATS', 'STOMAL', 'MOTS', 'MOLA', 'ALTS']
    5,	// SEVEN, bonus anagrams: ['NEVES', 'NEVE', 'ENS', 'SEN', 'EVENS']
    6,	// SERVE, bonus anagrams: ['SER', 'VEER', 'ERS', 'RES', 'VEERS', 'SEVER']
    6,	// RELIEF, bonus anagrams: ['FERE', 'LIER', 'REEF', 'LIEF', 'LIEFER', 'LIRE']
    6,	// SISTER, bonus anagrams: ['RESIST', 'REIS', 'SIRE', 'RETS', 'SITS', 'ERST']
    7,	// START, bonus anagrams: ['STAR', 'ARTS', 'RATS', 'TAR', 'TARTS', 'RAT', 'TSAR']
    7,	// STREAM, bonus anagrams: ['REAM', 'MATS', 'MARE', 'RETS', 'MAST', 'MASTER', 'ERST']
    7,	// STREET, bonus anagrams: ['RETE', 'TESTER', 'TETS', 'RETEST', 'RETS', 'STET', 'ERST']
    7,	// DESIRE, bonus anagrams: ['RESIDE', 'REIS', 'SIRE', 'DEER', 'REED', 'REDE', 'DERE']
    10,	// STEEL, bonus anagrams: ['TEEL', 'TEELS', 'TELES', 'LEETS', 'LEET', 'SLEET', 'TELE', 'ELS', 'SEL', 'STELE']
    11,	// ARREST, bonus anagrams: ['RASTER', 'ARTS', 'RARE', 'RATS', 'RAREST', 'RETS', 'TSAR', 'STAR', 'STARER', 'ERST', 'REAR']
