    0,	// ROYAL, bonus anagrams: []
    0,	// TERMS, bonus anagrams: []
    0,	// TRULY, bonus anagrams: []
    0,	// PRICE, bonus anagrams: []
    0,	// WITHIN, bonus anagrams: []
    0,	// FAVOR, bonus anagrams: []
    0,	// AFFAIR, bonus anagrams: []
    0,	// TOUCH, bonus anagrams: []
    0,	// SERVE, bonus anagrams: []
    0,	// BESIDE, bonus anagrams: []
    0,	// UNLESS, bonus anagrams: []
    0,	// THANK, bonus anagrams: []
    0,	// MIDDLE, bonus anagrams: []
    0,	// VESSEL, bonus anagrams: []
    0,	// TURNED, bonus anagrams: []
    0,	// WHILE, bonus anagrams: []
    0,	// MEMBER, bonus anagrams: []
    0,	// SECOND, bonus anagrams: []
    0,	// FIGHT, bonus anagrams: []
    0,	// NOTICE, bonus anagrams: []
    0,	// OCCUPY, bonus anagrams: []
    0,	// BECOME, bonus anagrams: []
    0,	// WINDOW, bonus anagrams: []
    1,	// GRAND, bonus anagrams: ['GRAN']
    1,	// DURING, bonus anagrams: ['DUNG']
    1,	// VOICE, bonus anagrams: ['VOE']
    1,	// SPEND, bonus anagrams: ['DEN']
    1,	// OUGHT, bonus anagrams: ['TOUGH']
    1,	// MOTION, bonus anagrams: ['MONO']
    1,	// ISSUE, bonus anagrams: ['SUE']
    1,	// FRONT, bonus anagrams: ['TON']
    1,	// TOTAL, bonus anagrams: ['LAT']
    1,	// SHOWN, bonus anagrams: ['WON']
    1,	// FIGURE, bonus anagrams: ['REIF']
    1,	// FIRST, bonus anagrams: ['FIRS']
    1,	// READY, bonus anagrams: ['DARE']
    1,	// UNABLE, bonus anagrams: ['BALE']
    1,	// RETURN, bonus anagrams: ['TURNER']
    1,	// STAND, bonus anagrams: ['ANTS']
    1,	// HONOR, bonus anagrams: ['RHO']
    1,	// BELONG, bonus anagrams: ['LOBE']
    1,	// ORDER, bonus anagrams: ['RODE']
    1,	// PASSED, bonus anagrams: ['APED']
    1,	// FINISH, bonus anagrams: ['SHIN']
    1,	// AHEAD, bonus anagrams: ['DAH']
    1,	// VISIT, bonus anagrams: ['TIS']
    1,	// SPENT, bonus anagrams: ['NET']
    1,	// EXTRA, bonus anagrams: ['AXE']
    1,	// CAREER, bonus anagrams: ['ACRE']
    1,	// DROWN, bonus anagrams: ['WON']
    1,	// SENSE, bonus anagrams: ['ENS']
    1,	// THESE, bonus anagrams: ['ETH']
    1,	// SPRING, bonus anagrams: ['RIPS']
    1,	// STONE, bonus anagrams: ['EON']
    1,	// CORNER, bonus anagrams: ['CORE']
    1,	// HEARD, bonus anagrams: ['RAD']
    1,	// RETIRE, bonus anagrams: ['TIER']
    1,	// PUSHED, bonus anagrams: ['EDHS']
    1,	// THING, bonus anagrams: ['GIN']
    1,	// WINTER, bonus anagrams: ['RENT']
    1,	// ISLAND, bonus anagrams: ['SIAL']
    1,	// SHALL, bonus anagrams: ['LASH']
    1,	// WAVES, bonus anagrams: ['WAVE']
    1,	// AWFUL, bonus anagrams: ['AWL']
    1,	// EMPIRE, bonus anagrams: ['PIER']
    1,	// REACH, bonus anagrams: ['ACRE']
    1,	// HOURS, bonus anagrams: ['OHS']
    1,	// BECAME, bonus anagrams: ['ACME']
    1,	// STRING, bonus anagrams: ['STIR']
    1,	// NEARLY, bonus anagrams: ['ARYL']
    1,	// ALLOW, bonus anagrams: ['OLLA']
    1,	// ELECT, bonus anagrams: ['TEL']
    1,	// BEING, bonus anagrams: ['GIN']
    1,	// TOWARD, bonus anagrams: ['WARD']
    2,	// INFORM, bonus anagrams: ['INFO', 'FOIN']
    2,	// DELAY, bonus anagrams: ['LADE', 'DEY']
    2,	// WOMAN, bonus anagrams: ['NAM', 'WON']
    2,	// EVERY, bonus anagrams: ['VEERY', 'VEER']
    2,	// HUMAN, bonus anagrams: ['HUN', 'NAM']
    2,	// FORTY, bonus anagrams: ['FOY', 'FORT']
    2,	// PARTY, bonus anagrams: ['YAP', 'TRAP']
    2,	// CAUSE, bonus anagrams: ['SUE', 'ACE']
    2,	// HOUSE, bonus anagrams: ['HOE', 'SUE']
    2,	// AFTER, bonus anagrams: ['RET', 'FATE']
    2,	// WATER, bonus anagrams: ['RAW', 'RET']
    2,	// BEGUN, bonus anagrams: ['NEB', 'BEN']
    2,	// INCOME, bonus anagrams: ['CONI', 'COIN']
    2,	// ABOUT, bonus anagrams: ['BAT', 'TAB']
    2,	// STOLE, bonus anagrams: ['LOTS', 'OLE']
    2,	// GREAT, bonus anagrams: ['TEA', 'TAE']
    2,	// DEATH, bonus anagrams: ['HATED', 'EDH']
    2,	// GUEST, bonus anagrams: ['TUG', 'GUT']
    2,	// DESIGN, bonus anagrams: ['SIGNED', 'SINGED']
    2,	// SUFFER, bonus anagrams: ['SUER', 'USER']
    2,	// CENTS, bonus anagrams: ['SCENT', 'SEC']
    2,	// FILLED, bonus anagrams: ['DEFI', 'DELL']
    2,	// BROWN, bonus anagrams: ['BROW', 'WON']
    2,	// UNTIL, bonus anagrams: ['TIL', 'LIT']
    2,	// OFFER, bonus anagrams: ['REF', 'FER']
    2,	// FOURTH, bonus anagrams: ['THRU', 'RUTH']
    2,	// ALONE, bonus anagrams: ['ALE', 'EON']
    2,	// SUMMER, bonus anagrams: ['SUER', 'USER']
    2,	// SMALL, bonus anagrams: ['LAMS', 'ALMS']
    2,	// WORTH, bonus anagrams: ['TROW', 'WORT']
    2,	// SHAPE, bonus anagrams: ['PASH', 'APE']
    2,	// KNOWN, bonus anagrams: ['WON', 'WONK']
    2,	// WOMEN, bonus anagrams: ['MEOW', 'WON']
    2,	// LESSON, bonus anagrams: ['LENO', 'NOEL']
    2,	// DIVIDE, bonus anagrams: ['VIED', 'VIDE']
    2,	// YOUNG, bonus anagrams: ['GOY', 'GNU']
    2,	// SINGLE, bonus anagrams: ['ISLE', 'LEIS']
    2,	// LEARN, bonus anagrams: ['LEAR', 'RALE']
    2,	// OFTEN, bonus anagrams: ['FON', 'NET']
    2,	// NEVER, bonus anagrams: ['NEVE', 'REV']
    2,	// MOTHER, bonus anagrams: ['MOTH', 'OMER']
    2,	// BELOW, bonus anagrams: ['LOBE', 'WEB']
    2,	// OTHER, bonus anagrams: ['TOR', 'ROT']
    2,	// THINK, bonus anagrams: ['KIN', 'INK']
    2,	// PLANT, bonus anagrams: ['ANT', 'TAN']
    2,	// PLANE, bonus anagrams: ['ANE', 'NAE']
    3,	// REPAIR, bonus anagrams: ['PARE', 'REAP', 'APER']
    3,	// OBTAIN, bonus anagrams: ['TAIN', 'BOTA', 'BONITA']
    3,	// ASSURE, bonus anagrams: ['USER', 'SUER', 'ERAS']
    3,	// BUILT, bonus anagrams: ['LIT', 'TIL', 'TUB']
    3,	// SELECT, bonus anagrams: ['SEEL', 'SECT', 'LEES']
    3,	// REALLY, bonus anagrams: ['RELY', 'LYRE', 'ALLY']
    3,	// CENTER, bonus anagrams: ['CERE', 'CENTRE', 'RENT']
    3,	// DOCTOR, bonus anagrams: ['ORDO', 'ROOD', 'ODOR']
    3,	// SIGHT, bonus anagrams: ['SIGH', 'TIS', 'GHIS']
    3,	// RESULT, bonus anagrams: ['SUTLER', 'SUER', 'USER']
    3,	// UNDER, bonus anagrams: ['NUDE', 'UNDE', 'NUDER']
    3,	// PAPER, bonus anagrams: ['PAR', 'RAP', 'REP']
    3,	// RAISE, bonus anagrams: ['ARISE', 'EAR', 'ERA']
    3,	// HEART, bonus anagrams: ['HET', 'TAR', 'RAT']
    3,	// COLOR, bonus anagrams: ['ROC', 'COR', 'LOCO']
    3,	// WORDS, bonus anagrams: ['SOW', 'WOS', 'SWORD']
    3,	// STILL, bonus anagrams: ['LILTS', 'ILL', 'LITS']
    3,	// EVENT, bonus anagrams: ['VET', 'NEVE', 'NET']
    3,	// DOUBT, bonus anagrams: ['TOD', 'TUB', 'DOT']
    3,	// CALLED, bonus anagrams: ['DELL', 'CADE', 'ACED']
    3,	// MEANT, bonus anagrams: ['ANT', 'MET', 'TAN']
    3,	// INSIDE, bonus anagrams: ['DENI', 'NISI', 'NIDE']
    4,	// PEOPLE, bonus anagrams: ['PEPO', 'POPE', 'PELE', 'PEEL']
    4,	// REMAIN, bonus anagrams: ['MARE', 'AMIN', 'REAM', 'REIN']
    4,	// LEAST, bonus anagrams: ['TEL', 'TAS', 'SALE', 'LEAS']
    4,	// CHART, bonus anagrams: ['TAR', 'CHAR', 'RAT', 'ARCH']
    4,	// THOSE, bonus anagrams: ['SOTH', 'ETHOS', 'OSE', 'ETH']
    4,	// STAMP, bonus anagrams: ['MATS', 'MAST', 'AMP', 'PAM']
    4,	// TODAY, bonus anagrams: ['TOY', 'TOAD', 'DATO', 'TOADY']
    4,	// THREE, bonus anagrams: ['ETHER', 'ERE', 'ETH', 'REE']
    4,	// COAST, bonus anagrams: ['COT', 'TAS', 'ASCOT', 'OCAS']
    4,	// SPREAD, bonus anagrams: ['SPADER', 'REPS', 'DAPS', 'DARE']
    4,	// ENTIRE, bonus anagrams: ['ERNE', 'RETINE', 'TINE', 'TIER']
    4,	// FOREST, bonus anagrams: ['RETS', 'FOSTER', 'FORE', 'ERST']
    4,	// METAL, bonus anagrams: ['MEL', 'TAME', 'META', 'LAT']
    4,	// FIELD, bonus anagrams: ['FID', 'ELD', 'DEL', 'FILED']
    5,	// ESCAPE, bonus anagrams: ['PEES', 'SEEP', 'ACES', 'CAPE', 'PEACES']
    5,	// LISTEN, bonus anagrams: ['NEST', 'LIEN', 'LITS', 'ENLIST', 'NETS']
    5,	// TABLE, bonus anagrams: ['ATE', 'BLAT', 'TAE', 'ETA', 'BLATE']
    5,	// LATER, bonus anagrams: ['TELA', 'RET', 'TEAL', 'ALTER', 'LAR']
    5,	// ALMOST, bonus anagrams: ['LATS', 'STOMAL', 'MOTS', 'MOLA', 'ALTS']
    6,	// SISTER, bonus anagrams: ['RESIST', 'REIS', 'SIRE', 'RETS', 'SITS', 'ERST']
    6,	// RELIEF, bonus anagrams: ['FERE', 'LIER', 'REEF', 'LIEF', 'LIEFER', 'LIRE']
    6,	// STATE, bonus anagrams: ['STAT', 'ATE', 'TASTE', 'TAE', 'ETA', 'TATS']
    7,	// STREET, bonus anagrams: ['RETE', 'TESTER', 'TETS', 'RETEST', 'RETS', 'STET', 'ERST']
    7,	// STREAM, bonus anagrams: ['REAM', 'MATS', 'MARE', 'RETS', 'MAST', 'MASTER', 'ERST']
    7,	// DESIRE, bonus anagrams: ['RESIDE', 'REIS', 'SIRE', 'DEER', 'REED', 'REDE', 'DERE']
    7,	// START, bonus anagrams: ['STAR', 'ARTS', 'RATS', 'TAR', 'TARTS', 'RAT', 'TSAR']
    11,	// ARREST, bonus anagrams: ['RASTER', 'ARTS', 'RARE', 'RATS', 'RAREST', 'RETS', 'TSAR', 'STAR', 'STARER', 'ERST', 'REAR']
