TC_DIR := ../../../..

BIN := rfspectrum

include $(TC_DIR)/Makefile.platform
include $(TC_DIR)/test/firmware/master/Makefile.defs

OBJS = main.o \
      $(TC_DIR)/firmware/master/common/rfspectrum.o

include $(TC_DIR)/test/firmware/master/Makefile.rules
