#!/usr/bin/env python
#
# Quick script to convert binary files to C arrays, so we can portably
# include them in our data segment. The emulator only needs a few external
# resources, and including them in the binary like this makes it easy to
# keep the simulator self-contained.
#
# M. Elizabeth Scott <beth@sifteo.com>
# 
# Copyright (c) 2011 Sifteo, Inc.
#

import struct

def nulTerm(data):
    return data + [0]

def sizePrefix(data):
    return map(ord, struct.pack("I", len(data))) + data

INPUTS = [
    ('rb', sizePrefix,  "../launcher/launcher.elf"),
    ('rb', None,        "resources/img_cube_face.png"),
    ('rb', None,        "resources/img_cube_face_hilight.png"),
    ('rb', None,        "resources/img_cube_face_hilight_mask.png"),
    ('rb', None,        "resources/img_wood.png"),
    ('rb', None,        "resources/img_bg_light.png"),
    ('r',  nulTerm,     "resources/cube_face_fp.glsl"),
    ('r',  nulTerm,     "resources/cube_face_vp.glsl"),
    ('r',  nulTerm,     "resources/cube_side_fp.glsl"),
    ('r',  nulTerm,     "resources/cube_side_vp.glsl"),
    ('r',  nulTerm,     "resources/background_fp.glsl"),
    ('r',  nulTerm,     "resources/background_vp.glsl"),
    ('r',  nulTerm,     "resources/scope_fp.glsl"),
    ('r',  nulTerm,     "resources/scope_vp.glsl"),
    ('rb', None,        "resources/ui_font_data.fnt"),
    ('rb', None,        "resources/ui_font_data_0.png"),
    ]

OUTPUT = "resources/data.cpp"

###############

import os.path

HEADER = """
/* -*- mode: C; c-basic-offset: 4; intent-tabs-mode: nil -*-
 *
 * Data for the Thundercracker emulator.
 * This file is AUTOMATICALLY GENERATED.
 *
 * Copyright <c> 2011 Sifteo, Inc. All rights reserved.
 */

#include <stdint.h>
""".lstrip()


def saveCodeArrays(filename, arrays):
    f = open(filename, 'w')
    f.write(HEADER)
    for name, data in arrays:
        writeArray(f, name, data)

def writeArray(f, name, data):
    f.write("\nextern const uint8_t %s[] __attribute__ ((aligned (4))) = {\n%s};\n"
            % (name, cByteArray(data)))

def cByteArray(bytes, width=16, indent="    "):
    # Format a list of byte values as a C array

    parts = []
    for i, b in enumerate(bytes):
        if (i % width) == 0:
            parts.append(indent)
        parts.append("0x%02x," % b)
        if (i % width) == width - 1 or i == len(bytes) - 1:
            parts.append("\n")
    return ''.join(parts)


if __name__ == "__main__":
    arrays = []

    for mode, fn, filename in INPUTS:
        name = os.path.splitext(os.path.split(filename)[-1])[0]
        data = map(ord, open(filename, mode).read())

        if fn:
            data = fn(data)

        arrays.append((name, data)) 

    saveCodeArrays(OUTPUT, arrays)
