#!/usr/bin/env python
#
# Quick script to convert binary files to C arrays, so we can portably
# include them in our data segment. The emulator only needs a few external
# resources, and including them in the binary like this makes it easy to
# keep the simulator self-contained.
#
# M. Elizabeth Scott <beth@sifteo.com>
# 
# Copyright (c) 2011 Sifteo, Inc.
#

INPUTS = [
    "scripts/img_cube_face.png",
    "scripts/img_cube_face_hilight.png",
    "scripts/img_cube_face_hilight_mask.png",
    "scripts/img_wood.png",
    "scripts/cube_face_fp.glsl",
    "scripts/cube_face_vp.glsl",
    "scripts/cube_side_fp.glsl",
    "scripts/cube_side_vp.glsl",
    "scripts/background_fp.glsl",
    "scripts/background_vp.glsl",
    ]

OUTPUT = "scripts/data.cpp"

###############

import os.path

def saveCodeArrays(filename, arrays):
    f = open(filename, 'w')
    f.write("""
/* -*- mode: C; c-basic-offset: 4; intent-tabs-mode: nil -*-
 *
 * Binary data for the Thundercracker emulator.
 * This file is AUTOMATICALLY GENERATED by bin2c.py
 *
 * Copyright <c> 2011 Sifteo, Inc. All rights reserved.
 */

#include <stdint.h>
""".lstrip())

    for name, data in arrays:
        f.write("\nextern const uint8_t %s[] = {\n%s};\n"
                % (name, cByteArray(data)))

def cByteArray(bytes, width=16, indent="    "):
    # Format a list of byte values as a C array

    parts = []
    for i, b in enumerate(bytes):
        if (i % width) == 0:
            parts.append(indent)
        parts.append("0x%02x," % b)
        if (i % width) == width - 1 or i == len(bytes) - 1:
            parts.append("\n")
    return ''.join(parts)


if __name__ == "__main__":
    arrays = []

    for filename in INPUTS:
        name = os.path.splitext(os.path.split(filename)[-1])[0]
        data = map(ord, open(filename, 'rb').read())

        # NUL-terminate strings. (Harmless on images)
        data.append(0)

        arrays.append((name, data)) 

    saveCodeArrays(OUTPUT, arrays)
