--file generated by BuildLua.py

BootstrapAssets = group{quality=9}

Cube1 = { image{"assets/cube1/3.png"}, image{"assets/cube1/4.png"}, }
Cube2 = { image{"assets/cube2/5.png"}, image{"assets/cube2/6.png"}, }
Cube3 = { image{"assets/cube3/2.png"}, image{"assets/cube3/7.png"}, }
Cube4 = { image{"assets/cube4/1.png"}, }
Cube5 = { image{"assets/cube5/3.png"}, image{"assets/cube5/4.png"}, }
Cube6 = { image{"assets/cube6/5.png"}, image{"assets/cube6/6.png"}, }
