#!/usr/bin/env python
"""
script to walk through image files and build an assets.lua to be built into the app
"""

import os
import sys

def main():
    path_images = "assets/"
       
    with open("assets.lua", 'w') as fout:
        fout.write( '--file generated by BuildLua.py\n\n' )
        fout.write( 'BootstrapAssets = group{quality=9}\n\n' )              
    
        dirList = os.listdir( path_images )
            
        dirAppend = 1
            
        #directories under puzzles
        for dir in dirList:
            pathdir = path_images + dir + "/"
            
            if( os.path.isdir( pathdir ) ):                        
                fileList = os.listdir( pathdir )                            
            
                if fileList:                       
                    print "about to dump images in dir " + pathdir
                    fout.write( 'Cube' + str( dirAppend ) + ' = { ' )             
                                               
                    #dump all puzzles
                    for fname in fileList:                            
                            fout.write( 'image{"' + pathdir + fname + '"}, ' )
                        
            dirAppend = dirAppend + 1
            
                                       
            fout.write( '}\n' )                        
        
if __name__ == "__main__":
    main()
