TC_DIR = ../../..
include $(TC_DIR)/firmware/master/Makefile.defs

BIN_SIM = monster.sim$(BIN_EXT)
OBJS_SIM = main.sim.o

BIN_STM32 = monster.stm32
OBJS_STM32 = main.stm32.o

CDEPS += *.h

include $(TC_DIR)/firmware/master/Makefile.rules
