# we expect $(TC_DIR)/sdk/Makefile.defs has already been included


######## Normal target rules

all: $(BIN)

%.o: %.cpp $(CDEPS)
	$(CC) -c -o $@ $< $(CCFLAGS)

$(BIN): $(OBJS) $(LD)
	$(LD) -o $@ $(OBJS) $(LDFLAGS)

ASSET_GEN_FILES := -o $(ASSETS).gen.cpp -o $(ASSETS).gen.h
ifneq ($(ASSETS_BUILD_PROOF),)
    ASSET_GEN_FILES += -o $(ASSETS).html
endif

$(ASSETS).gen.cpp: $(STIR) $(ASSETDEPS)
	$(STIR) $(ASSETS).lua $(ASSET_GEN_FILES) -v

clean:
	rm -f $(BIN) *.o *.d $(GENERATED_FILES)

.PHONY: clean all

-include $(OBJS:%.o=%.d)

######## Development utility rules

llvm-dis: $(OBJS)
	$(LLVM_BIN)/llvm-link $(OBJS) -S -o - | arm-none-eabi-c++filt | less

objdump: $(BIN)
	arm-none-eabi-objdump -d $(BIN) | arm-none-eabi-c++filt | less

asm: program.s
	less $^

program.s: $(OBJS) $(LD)
	$(LD) -asm -o $@ $(OBJS) $(LDFLAGS)

readelf: $(BIN)
	arm-none-eabi-readelf -a $(BIN) | arm-none-eabi-c++filt | less

.PHONY: llvm-dis objdump asm readelf
