# We expect $(SDK_DIR)/Makefile.defs has already been included.


######## Normal target rules

all: $(BIN)

# Disable implicit rules. Speeds up make, especially on Windows.
.SUFFIXES:

%.o: %.cpp $(CDEPS)
	@echo Compiling $<
	@$(CC) -c -o $@ $< $(CCFLAGS)

%.o: %.cc $(CDEPS)
	@echo Compiling $<
	@$(CC) -c -o $@ $< $(CCFLAGS)
    
%.o: %.c $(CDEPS)
	@echo Compiling $<
	@$(CC) -c -o $@ $< $(CFLAGS)

$(BIN): $(OBJS)
	@echo Linking $@ "$(LINK_MESSAGE)"
	@$(LD) -o $@ $(OBJS) $(LDFLAGS)

ASSET_GEN_FILES := -o $(ASSETS).gen.cpp -o $(ASSETS).gen.h
ifneq ($(ASSETS_BUILD_PROOF),)
    ASSET_GEN_FILES += -o $(ASSETS).html
endif

$(ASSETS).gen.cpp: $(ASSETDEPS)
	$(STIR) $(ASSETS).lua $(ASSET_GEN_FILES) -v

clean:
	rm -f $(BIN) $(OBJS) $(OBJS:%.o=%.d) $(GENERATED_FILES)

.PHONY: clean all

-include $(OBJS:%.o=%.d)


######## Convenience rules

run: $(BIN)
	siftulator $(SIFTULATOR_FLAGS) $<

install: $(BIN)
	swiss install $<

.PHONY: run install


######## Development utility rules

# These rely on common open source tools that aren't
# part of the standard SDK distribution.

llvm-dis: $(OBJS)
	llvm-link $(OBJS) -S -o - | arm-none-eabi-c++filt | less

objdump: $(BIN)
	arm-none-eabi-objdump -d $(BIN) | arm-none-eabi-c++filt | less

asm: program.s
	less $^

program.s: $(OBJS)
	$(LD) -asm -o $@ $(OBJS) $(LDFLAGS)

readelf: $(BIN)
	arm-none-eabi-readelf -a $(BIN) | arm-none-eabi-c++filt | less

.PHONY: llvm-dis objdump asm readelf
