#pragma once

#include "sifteo.h"
#include "View.h"
#include "TotalsCube.h"
#include "ObjectPool.h"
#include "Game.h"

namespace TotalsGame {
  
	class Token;
	class IExpression;

  class TokenView : public View 
  {
	  DECLARE_POOL(TokenView, Game::NUMBER_OF_CUBES);

  private:
	  static int sHintParity;

	  //from TokenView.data.cs  big todo
	  class PuzzleStyleData {};
	  static const PuzzleStyleData DefaultStyle;

	  //junk to make compile
	  class Color {};

	  class EventHandler: public TotalsCube::EventHandler {};
	  EventHandler eventHandler;

  public:

	static const Vec2 Mid;

    static const int BIT_TOP = 1<<SIDE_TOP;
    static const int BIT_LEFT = 1<<SIDE_LEFT;
    static const int BIT_BOTTOM = 1<<SIDE_BOTTOM;
    static const int BIT_RIGHT = 1<<SIDE_RIGHT;
    static const char *kOpNames[4];
    
	enum Status 
	{ 
		StatusIdle, 
		StatusQueued, 
		StatusOverlay, 
		StatusHinting 
	};

    Token *token;
    Status mStatus;
    IExpression *mCurrentExpression;
    PuzzleStyleData mStyle;
    float mTimeout;
    int mDigitId;
    bool useAccentDigit;
    int mHideMask;
/*    Sprite mDigit = new Sprite(null) { position = Mid };
    Sprite mCenterCap = new Sprite(null) { position = Mid };
TODO */
    Status GetCurrentStatus();
    bool mLit;

    //-------------------------------------------------------------------------
    // PUBLIC METHODS
    //-------------------------------------------------------------------------

    TokenView(TotalsCube *cube, Token *_token, bool showDigitOnInit=true);
	virtual ~TokenView() {}

    void HideOps() ;

    void PaintRandomNumeral() ;

    void ResetNumeral() ;

    void WillJoinGroup() ;

    void DidJoinGroup() ;
    void DidGroupDisconnect();

    void BlinkOverlay();

    void ShowOverlay() ;

    void ShowLit() ;

    void HideOverlay();

    void SetHideMode(int mask);

private:
    bool NotHiding(Cube::Side side) ;

    void SetState(Status state, bool resetTimer=true, bool resetExpr=true);


    //-------------------------------------------------------------------------
    // VIEW METHODS
    //-------------------------------------------------------------------------
public:
    virtual void DidAttachToCube(TotalsCube *c) ;

    void OnShakeStarted(TotalsCube *c) ;
    
    void OnButtonEvent(TotalsCube *c, bool isPressed);
    
    virtual void WillDetachFromCube(TotalsCube *c) ;

    virtual void Update(float dt) ;
    
    virtual void Paint() ;
  
    //-------------------------------------------------------------------------
    // HELPER METHODS
    //-------------------------------------------------------------------------
	private:

      void PaintCenterCap(uint8_t masks[4]);
      static int CountBits(uint8_t mask);

      void PaintDigit();


    // // // //
    // code generated by ImageTool
    void PaintTop(bool lit);
    void PaintLeft(bool lit);
    void PaintRight(bool lit);
    void PaintBottom(bool lit);
    // // // //

   
  };
  
}

