; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	C:\Users\Chris\Downloads\zlib125\zlib-1.2.5\infback.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

CONST	SEGMENT
?lenfix@?1??fixedtables@@9@9 DB 060H			; `fixedtables'::`2'::lenfix
	DB	07H
	DW	00H
	DB	00H
	DB	08H
	DW	050H
	DB	00H
	DB	08H
	DW	010H
	DB	014H
	DB	08H
	DW	073H
	DB	012H
	DB	07H
	DW	01fH
	DB	00H
	DB	08H
	DW	070H
	DB	00H
	DB	08H
	DW	030H
	DB	00H
	DB	09H
	DW	0c0H
	DB	010H
	DB	07H
	DW	0aH
	DB	00H
	DB	08H
	DW	060H
	DB	00H
	DB	08H
	DW	020H
	DB	00H
	DB	09H
	DW	0a0H
	DB	00H
	DB	08H
	DW	00H
	DB	00H
	DB	08H
	DW	080H
	DB	00H
	DB	08H
	DW	040H
	DB	00H
	DB	09H
	DW	0e0H
	DB	010H
	DB	07H
	DW	06H
	DB	00H
	DB	08H
	DW	058H
	DB	00H
	DB	08H
	DW	018H
	DB	00H
	DB	09H
	DW	090H
	DB	013H
	DB	07H
	DW	03bH
	DB	00H
	DB	08H
	DW	078H
	DB	00H
	DB	08H
	DW	038H
	DB	00H
	DB	09H
	DW	0d0H
	DB	011H
	DB	07H
	DW	011H
	DB	00H
	DB	08H
	DW	068H
	DB	00H
	DB	08H
	DW	028H
	DB	00H
	DB	09H
	DW	0b0H
	DB	00H
	DB	08H
	DW	08H
	DB	00H
	DB	08H
	DW	088H
	DB	00H
	DB	08H
	DW	048H
	DB	00H
	DB	09H
	DW	0f0H
	DB	010H
	DB	07H
	DW	04H
	DB	00H
	DB	08H
	DW	054H
	DB	00H
	DB	08H
	DW	014H
	DB	015H
	DB	08H
	DW	0e3H
	DB	013H
	DB	07H
	DW	02bH
	DB	00H
	DB	08H
	DW	074H
	DB	00H
	DB	08H
	DW	034H
	DB	00H
	DB	09H
	DW	0c8H
	DB	011H
	DB	07H
	DW	0dH
	DB	00H
	DB	08H
	DW	064H
	DB	00H
	DB	08H
	DW	024H
	DB	00H
	DB	09H
	DW	0a8H
	DB	00H
	DB	08H
	DW	04H
	DB	00H
	DB	08H
	DW	084H
	DB	00H
	DB	08H
	DW	044H
	DB	00H
	DB	09H
	DW	0e8H
	DB	010H
	DB	07H
	DW	08H
	DB	00H
	DB	08H
	DW	05cH
	DB	00H
	DB	08H
	DW	01cH
	DB	00H
	DB	09H
	DW	098H
	DB	014H
	DB	07H
	DW	053H
	DB	00H
	DB	08H
	DW	07cH
	DB	00H
	DB	08H
	DW	03cH
	DB	00H
	DB	09H
	DW	0d8H
	DB	012H
	DB	07H
	DW	017H
	DB	00H
	DB	08H
	DW	06cH
	DB	00H
	DB	08H
	DW	02cH
	DB	00H
	DB	09H
	DW	0b8H
	DB	00H
	DB	08H
	DW	0cH
	DB	00H
	DB	08H
	DW	08cH
	DB	00H
	DB	08H
	DW	04cH
	DB	00H
	DB	09H
	DW	0f8H
	DB	010H
	DB	07H
	DW	03H
	DB	00H
	DB	08H
	DW	052H
	DB	00H
	DB	08H
	DW	012H
	DB	015H
	DB	08H
	DW	0a3H
	DB	013H
	DB	07H
	DW	023H
	DB	00H
	DB	08H
	DW	072H
	DB	00H
	DB	08H
	DW	032H
	DB	00H
	DB	09H
	DW	0c4H
	DB	011H
	DB	07H
	DW	0bH
	DB	00H
	DB	08H
	DW	062H
	DB	00H
	DB	08H
	DW	022H
	DB	00H
	DB	09H
	DW	0a4H
	DB	00H
	DB	08H
	DW	02H
	DB	00H
	DB	08H
	DW	082H
	DB	00H
	DB	08H
	DW	042H
	DB	00H
	DB	09H
	DW	0e4H
	DB	010H
	DB	07H
	DW	07H
	DB	00H
	DB	08H
	DW	05aH
	DB	00H
	DB	08H
	DW	01aH
	DB	00H
	DB	09H
	DW	094H
	DB	014H
	DB	07H
	DW	043H
	DB	00H
	DB	08H
	DW	07aH
	DB	00H
	DB	08H
	DW	03aH
	DB	00H
	DB	09H
	DW	0d4H
	DB	012H
	DB	07H
	DW	013H
	DB	00H
	DB	08H
	DW	06aH
	DB	00H
	DB	08H
	DW	02aH
	DB	00H
	DB	09H
	DW	0b4H
	DB	00H
	DB	08H
	DW	0aH
	DB	00H
	DB	08H
	DW	08aH
	DB	00H
	DB	08H
	DW	04aH
	DB	00H
	DB	09H
	DW	0f4H
	DB	010H
	DB	07H
	DW	05H
	DB	00H
	DB	08H
	DW	056H
	DB	00H
	DB	08H
	DW	016H
	DB	040H
	DB	08H
	DW	00H
	DB	013H
	DB	07H
	DW	033H
	DB	00H
	DB	08H
	DW	076H
	DB	00H
	DB	08H
	DW	036H
	DB	00H
	DB	09H
	DW	0ccH
	DB	011H
	DB	07H
	DW	0fH
	DB	00H
	DB	08H
	DW	066H
	DB	00H
	DB	08H
	DW	026H
	DB	00H
	DB	09H
	DW	0acH
	DB	00H
	DB	08H
	DW	06H
	DB	00H
	DB	08H
	DW	086H
	DB	00H
	DB	08H
	DW	046H
	DB	00H
	DB	09H
	DW	0ecH
	DB	010H
	DB	07H
	DW	09H
	DB	00H
	DB	08H
	DW	05eH
	DB	00H
	DB	08H
	DW	01eH
	DB	00H
	DB	09H
	DW	09cH
	DB	014H
	DB	07H
	DW	063H
	DB	00H
	DB	08H
	DW	07eH
	DB	00H
	DB	08H
	DW	03eH
	DB	00H
	DB	09H
	DW	0dcH
	DB	012H
	DB	07H
	DW	01bH
	DB	00H
	DB	08H
	DW	06eH
	DB	00H
	DB	08H
	DW	02eH
	DB	00H
	DB	09H
	DW	0bcH
	DB	00H
	DB	08H
	DW	0eH
	DB	00H
	DB	08H
	DW	08eH
	DB	00H
	DB	08H
	DW	04eH
	DB	00H
	DB	09H
	DW	0fcH
	DB	060H
	DB	07H
	DW	00H
	DB	00H
	DB	08H
	DW	051H
	DB	00H
	DB	08H
	DW	011H
	DB	015H
	DB	08H
	DW	083H
	DB	012H
	DB	07H
	DW	01fH
	DB	00H
	DB	08H
	DW	071H
	DB	00H
	DB	08H
	DW	031H
	DB	00H
	DB	09H
	DW	0c2H
	DB	010H
	DB	07H
	DW	0aH
	DB	00H
	DB	08H
	DW	061H
	DB	00H
	DB	08H
	DW	021H
	DB	00H
	DB	09H
	DW	0a2H
	DB	00H
	DB	08H
	DW	01H
	DB	00H
	DB	08H
	DW	081H
	DB	00H
	DB	08H
	DW	041H
	DB	00H
	DB	09H
	DW	0e2H
	DB	010H
	DB	07H
	DW	06H
	DB	00H
	DB	08H
	DW	059H
	DB	00H
	DB	08H
	DW	019H
	DB	00H
	DB	09H
	DW	092H
	DB	013H
	DB	07H
	DW	03bH
	DB	00H
	DB	08H
	DW	079H
	DB	00H
	DB	08H
	DW	039H
	DB	00H
	DB	09H
	DW	0d2H
	DB	011H
	DB	07H
	DW	011H
	DB	00H
	DB	08H
	DW	069H
	DB	00H
	DB	08H
	DW	029H
	DB	00H
	DB	09H
	DW	0b2H
	DB	00H
	DB	08H
	DW	09H
	DB	00H
	DB	08H
	DW	089H
	DB	00H
	DB	08H
	DW	049H
	DB	00H
	DB	09H
	DW	0f2H
	DB	010H
	DB	07H
	DW	04H
	DB	00H
	DB	08H
	DW	055H
	DB	00H
	DB	08H
	DW	015H
	DB	010H
	DB	08H
	DW	0102H
	DB	013H
	DB	07H
	DW	02bH
	DB	00H
	DB	08H
	DW	075H
	DB	00H
	DB	08H
	DW	035H
	DB	00H
	DB	09H
	DW	0caH
	DB	011H
	DB	07H
	DW	0dH
	DB	00H
	DB	08H
	DW	065H
	DB	00H
	DB	08H
	DW	025H
	DB	00H
	DB	09H
	DW	0aaH
	DB	00H
	DB	08H
	DW	05H
	DB	00H
	DB	08H
	DW	085H
	DB	00H
	DB	08H
	DW	045H
	DB	00H
	DB	09H
	DW	0eaH
	DB	010H
	DB	07H
	DW	08H
	DB	00H
	DB	08H
	DW	05dH
	DB	00H
	DB	08H
	DW	01dH
	DB	00H
	DB	09H
	DW	09aH
	DB	014H
	DB	07H
	DW	053H
	DB	00H
	DB	08H
	DW	07dH
	DB	00H
	DB	08H
	DW	03dH
	DB	00H
	DB	09H
	DW	0daH
	DB	012H
	DB	07H
	DW	017H
	DB	00H
	DB	08H
	DW	06dH
	DB	00H
	DB	08H
	DW	02dH
	DB	00H
	DB	09H
	DW	0baH
	DB	00H
	DB	08H
	DW	0dH
	DB	00H
	DB	08H
	DW	08dH
	DB	00H
	DB	08H
	DW	04dH
	DB	00H
	DB	09H
	DW	0faH
	DB	010H
	DB	07H
	DW	03H
	DB	00H
	DB	08H
	DW	053H
	DB	00H
	DB	08H
	DW	013H
	DB	015H
	DB	08H
	DW	0c3H
	DB	013H
	DB	07H
	DW	023H
	DB	00H
	DB	08H
	DW	073H
	DB	00H
	DB	08H
	DW	033H
	DB	00H
	DB	09H
	DW	0c6H
	DB	011H
	DB	07H
	DW	0bH
	DB	00H
	DB	08H
	DW	063H
	DB	00H
	DB	08H
	DW	023H
	DB	00H
	DB	09H
	DW	0a6H
	DB	00H
	DB	08H
	DW	03H
	DB	00H
	DB	08H
	DW	083H
	DB	00H
	DB	08H
	DW	043H
	DB	00H
	DB	09H
	DW	0e6H
	DB	010H
	DB	07H
	DW	07H
	DB	00H
	DB	08H
	DW	05bH
	DB	00H
	DB	08H
	DW	01bH
	DB	00H
	DB	09H
	DW	096H
	DB	014H
	DB	07H
	DW	043H
	DB	00H
	DB	08H
	DW	07bH
	DB	00H
	DB	08H
	DW	03bH
	DB	00H
	DB	09H
	DW	0d6H
	DB	012H
	DB	07H
	DW	013H
	DB	00H
	DB	08H
	DW	06bH
	DB	00H
	DB	08H
	DW	02bH
	DB	00H
	DB	09H
	DW	0b6H
	DB	00H
	DB	08H
	DW	0bH
	DB	00H
	DB	08H
	DW	08bH
	DB	00H
	DB	08H
	DW	04bH
	DB	00H
	DB	09H
	DW	0f6H
	DB	010H
	DB	07H
	DW	05H
	DB	00H
	DB	08H
	DW	057H
	DB	00H
	DB	08H
	DW	017H
	DB	040H
	DB	08H
	DW	00H
	DB	013H
	DB	07H
	DW	033H
	DB	00H
	DB	08H
	DW	077H
	DB	00H
	DB	08H
	DW	037H
	DB	00H
	DB	09H
	DW	0ceH
	DB	011H
	DB	07H
	DW	0fH
	DB	00H
	DB	08H
	DW	067H
	DB	00H
	DB	08H
	DW	027H
	DB	00H
	DB	09H
	DW	0aeH
	DB	00H
	DB	08H
	DW	07H
	DB	00H
	DB	08H
	DW	087H
	DB	00H
	DB	08H
	DW	047H
	DB	00H
	DB	09H
	DW	0eeH
	DB	010H
	DB	07H
	DW	09H
	DB	00H
	DB	08H
	DW	05fH
	DB	00H
	DB	08H
	DW	01fH
	DB	00H
	DB	09H
	DW	09eH
	DB	014H
	DB	07H
	DW	063H
	DB	00H
	DB	08H
	DW	07fH
	DB	00H
	DB	08H
	DW	03fH
	DB	00H
	DB	09H
	DW	0deH
	DB	012H
	DB	07H
	DW	01bH
	DB	00H
	DB	08H
	DW	06fH
	DB	00H
	DB	08H
	DW	02fH
	DB	00H
	DB	09H
	DW	0beH
	DB	00H
	DB	08H
	DW	0fH
	DB	00H
	DB	08H
	DW	08fH
	DB	00H
	DB	08H
	DW	04fH
	DB	00H
	DB	09H
	DW	0feH
	DB	060H
	DB	07H
	DW	00H
	DB	00H
	DB	08H
	DW	050H
	DB	00H
	DB	08H
	DW	010H
	DB	014H
	DB	08H
	DW	073H
	DB	012H
	DB	07H
	DW	01fH
	DB	00H
	DB	08H
	DW	070H
	DB	00H
	DB	08H
	DW	030H
	DB	00H
	DB	09H
	DW	0c1H
	DB	010H
	DB	07H
	DW	0aH
	DB	00H
	DB	08H
	DW	060H
	DB	00H
	DB	08H
	DW	020H
	DB	00H
	DB	09H
	DW	0a1H
	DB	00H
	DB	08H
	DW	00H
	DB	00H
	DB	08H
	DW	080H
	DB	00H
	DB	08H
	DW	040H
	DB	00H
	DB	09H
	DW	0e1H
	DB	010H
	DB	07H
	DW	06H
	DB	00H
	DB	08H
	DW	058H
	DB	00H
	DB	08H
	DW	018H
	DB	00H
	DB	09H
	DW	091H
	DB	013H
	DB	07H
	DW	03bH
	DB	00H
	DB	08H
	DW	078H
	DB	00H
	DB	08H
	DW	038H
	DB	00H
	DB	09H
	DW	0d1H
	DB	011H
	DB	07H
	DW	011H
	DB	00H
	DB	08H
	DW	068H
	DB	00H
	DB	08H
	DW	028H
	DB	00H
	DB	09H
	DW	0b1H
	DB	00H
	DB	08H
	DW	08H
	DB	00H
	DB	08H
	DW	088H
	DB	00H
	DB	08H
	DW	048H
	DB	00H
	DB	09H
	DW	0f1H
	DB	010H
	DB	07H
	DW	04H
	DB	00H
	DB	08H
	DW	054H
	DB	00H
	DB	08H
	DW	014H
	DB	015H
	DB	08H
	DW	0e3H
	DB	013H
	DB	07H
	DW	02bH
	DB	00H
	DB	08H
	DW	074H
	DB	00H
	DB	08H
	DW	034H
	DB	00H
	DB	09H
	DW	0c9H
	DB	011H
	DB	07H
	DW	0dH
	DB	00H
	DB	08H
	DW	064H
	DB	00H
	DB	08H
	DW	024H
	DB	00H
	DB	09H
	DW	0a9H
	DB	00H
	DB	08H
	DW	04H
	DB	00H
	DB	08H
	DW	084H
	DB	00H
	DB	08H
	DW	044H
	DB	00H
	DB	09H
	DW	0e9H
	DB	010H
	DB	07H
	DW	08H
	DB	00H
	DB	08H
	DW	05cH
	DB	00H
	DB	08H
	DW	01cH
	DB	00H
	DB	09H
	DW	099H
	DB	014H
	DB	07H
	DW	053H
	DB	00H
	DB	08H
	DW	07cH
	DB	00H
	DB	08H
	DW	03cH
	DB	00H
	DB	09H
	DW	0d9H
	DB	012H
	DB	07H
	DW	017H
	DB	00H
	DB	08H
	DW	06cH
	DB	00H
	DB	08H
	DW	02cH
	DB	00H
	DB	09H
	DW	0b9H
	DB	00H
	DB	08H
	DW	0cH
	DB	00H
	DB	08H
	DW	08cH
	DB	00H
	DB	08H
	DW	04cH
	DB	00H
	DB	09H
	DW	0f9H
	DB	010H
	DB	07H
	DW	03H
	DB	00H
	DB	08H
	DW	052H
	DB	00H
	DB	08H
	DW	012H
	DB	015H
	DB	08H
	DW	0a3H
	DB	013H
	DB	07H
	DW	023H
	DB	00H
	DB	08H
	DW	072H
	DB	00H
	DB	08H
	DW	032H
	DB	00H
	DB	09H
	DW	0c5H
	DB	011H
	DB	07H
	DW	0bH
	DB	00H
	DB	08H
	DW	062H
	DB	00H
	DB	08H
	DW	022H
	DB	00H
	DB	09H
	DW	0a5H
	DB	00H
	DB	08H
	DW	02H
	DB	00H
	DB	08H
	DW	082H
	DB	00H
	DB	08H
	DW	042H
	DB	00H
	DB	09H
	DW	0e5H
	DB	010H
	DB	07H
	DW	07H
	DB	00H
	DB	08H
	DW	05aH
	DB	00H
	DB	08H
	DW	01aH
	DB	00H
	DB	09H
	DW	095H
	DB	014H
	DB	07H
	DW	043H
	DB	00H
	DB	08H
	DW	07aH
	DB	00H
	DB	08H
	DW	03aH
	DB	00H
	DB	09H
	DW	0d5H
	DB	012H
	DB	07H
	DW	013H
	DB	00H
	DB	08H
	DW	06aH
	DB	00H
	DB	08H
	DW	02aH
	DB	00H
	DB	09H
	DW	0b5H
	DB	00H
	DB	08H
	DW	0aH
	DB	00H
	DB	08H
	DW	08aH
	DB	00H
	DB	08H
	DW	04aH
	DB	00H
	DB	09H
	DW	0f5H
	DB	010H
	DB	07H
	DW	05H
	DB	00H
	DB	08H
	DW	056H
	DB	00H
	DB	08H
	DW	016H
	DB	040H
	DB	08H
	DW	00H
	DB	013H
	DB	07H
	DW	033H
	DB	00H
	DB	08H
	DW	076H
	DB	00H
	DB	08H
	DW	036H
	DB	00H
	DB	09H
	DW	0cdH
	DB	011H
	DB	07H
	DW	0fH
	DB	00H
	DB	08H
	DW	066H
	DB	00H
	DB	08H
	DW	026H
	DB	00H
	DB	09H
	DW	0adH
	DB	00H
	DB	08H
	DW	06H
	DB	00H
	DB	08H
	DW	086H
	DB	00H
	DB	08H
	DW	046H
	DB	00H
	DB	09H
	DW	0edH
	DB	010H
	DB	07H
	DW	09H
	DB	00H
	DB	08H
	DW	05eH
	DB	00H
	DB	08H
	DW	01eH
	DB	00H
	DB	09H
	DW	09dH
	DB	014H
	DB	07H
	DW	063H
	DB	00H
	DB	08H
	DW	07eH
	DB	00H
	DB	08H
	DW	03eH
	DB	00H
	DB	09H
	DW	0ddH
	DB	012H
	DB	07H
	DW	01bH
	DB	00H
	DB	08H
	DW	06eH
	DB	00H
	DB	08H
	DW	02eH
	DB	00H
	DB	09H
	DW	0bdH
	DB	00H
	DB	08H
	DW	0eH
	DB	00H
	DB	08H
	DW	08eH
	DB	00H
	DB	08H
	DW	04eH
	DB	00H
	DB	09H
	DW	0fdH
	DB	060H
	DB	07H
	DW	00H
	DB	00H
	DB	08H
	DW	051H
	DB	00H
	DB	08H
	DW	011H
	DB	015H
	DB	08H
	DW	083H
	DB	012H
	DB	07H
	DW	01fH
	DB	00H
	DB	08H
	DW	071H
	DB	00H
	DB	08H
	DW	031H
	DB	00H
	DB	09H
	DW	0c3H
	DB	010H
	DB	07H
	DW	0aH
	DB	00H
	DB	08H
	DW	061H
	DB	00H
	DB	08H
	DW	021H
	DB	00H
	DB	09H
	DW	0a3H
	DB	00H
	DB	08H
	DW	01H
	DB	00H
	DB	08H
	DW	081H
	DB	00H
	DB	08H
	DW	041H
	DB	00H
	DB	09H
	DW	0e3H
	DB	010H
	DB	07H
	DW	06H
	DB	00H
	DB	08H
	DW	059H
	DB	00H
	DB	08H
	DW	019H
	DB	00H
	DB	09H
	DW	093H
	DB	013H
	DB	07H
	DW	03bH
	DB	00H
	DB	08H
	DW	079H
	DB	00H
	DB	08H
	DW	039H
	DB	00H
	DB	09H
	DW	0d3H
	DB	011H
	DB	07H
	DW	011H
	DB	00H
	DB	08H
	DW	069H
	DB	00H
	DB	08H
	DW	029H
	DB	00H
	DB	09H
	DW	0b3H
	DB	00H
	DB	08H
	DW	09H
	DB	00H
	DB	08H
	DW	089H
	DB	00H
	DB	08H
	DW	049H
	DB	00H
	DB	09H
	DW	0f3H
	DB	010H
	DB	07H
	DW	04H
	DB	00H
	DB	08H
	DW	055H
	DB	00H
	DB	08H
	DW	015H
	DB	010H
	DB	08H
	DW	0102H
	DB	013H
	DB	07H
	DW	02bH
	DB	00H
	DB	08H
	DW	075H
	DB	00H
	DB	08H
	DW	035H
	DB	00H
	DB	09H
	DW	0cbH
	DB	011H
	DB	07H
	DW	0dH
	DB	00H
	DB	08H
	DW	065H
	DB	00H
	DB	08H
	DW	025H
	DB	00H
	DB	09H
	DW	0abH
	DB	00H
	DB	08H
	DW	05H
	DB	00H
	DB	08H
	DW	085H
	DB	00H
	DB	08H
	DW	045H
	DB	00H
	DB	09H
	DW	0ebH
	DB	010H
	DB	07H
	DW	08H
	DB	00H
	DB	08H
	DW	05dH
	DB	00H
	DB	08H
	DW	01dH
	DB	00H
	DB	09H
	DW	09bH
	DB	014H
	DB	07H
	DW	053H
	DB	00H
	DB	08H
	DW	07dH
	DB	00H
	DB	08H
	DW	03dH
	DB	00H
	DB	09H
	DW	0dbH
	DB	012H
	DB	07H
	DW	017H
	DB	00H
	DB	08H
	DW	06dH
	DB	00H
	DB	08H
	DW	02dH
	DB	00H
	DB	09H
	DW	0bbH
	DB	00H
	DB	08H
	DW	0dH
	DB	00H
	DB	08H
	DW	08dH
	DB	00H
	DB	08H
	DW	04dH
	DB	00H
	DB	09H
	DW	0fbH
	DB	010H
	DB	07H
	DW	03H
	DB	00H
	DB	08H
	DW	053H
	DB	00H
	DB	08H
	DW	013H
	DB	015H
	DB	08H
	DW	0c3H
	DB	013H
	DB	07H
	DW	023H
	DB	00H
	DB	08H
	DW	073H
	DB	00H
	DB	08H
	DW	033H
	DB	00H
	DB	09H
	DW	0c7H
	DB	011H
	DB	07H
	DW	0bH
	DB	00H
	DB	08H
	DW	063H
	DB	00H
	DB	08H
	DW	023H
	DB	00H
	DB	09H
	DW	0a7H
	DB	00H
	DB	08H
	DW	03H
	DB	00H
	DB	08H
	DW	083H
	DB	00H
	DB	08H
	DW	043H
	DB	00H
	DB	09H
	DW	0e7H
	DB	010H
	DB	07H
	DW	07H
	DB	00H
	DB	08H
	DW	05bH
	DB	00H
	DB	08H
	DW	01bH
	DB	00H
	DB	09H
	DW	097H
	DB	014H
	DB	07H
	DW	043H
	DB	00H
	DB	08H
	DW	07bH
	DB	00H
	DB	08H
	DW	03bH
	DB	00H
	DB	09H
	DW	0d7H
	DB	012H
	DB	07H
	DW	013H
	DB	00H
	DB	08H
	DW	06bH
	DB	00H
	DB	08H
	DW	02bH
	DB	00H
	DB	09H
	DW	0b7H
	DB	00H
	DB	08H
	DW	0bH
	DB	00H
	DB	08H
	DW	08bH
	DB	00H
	DB	08H
	DW	04bH
	DB	00H
	DB	09H
	DW	0f7H
	DB	010H
	DB	07H
	DW	05H
	DB	00H
	DB	08H
	DW	057H
	DB	00H
	DB	08H
	DW	017H
	DB	040H
	DB	08H
	DW	00H
	DB	013H
	DB	07H
	DW	033H
	DB	00H
	DB	08H
	DW	077H
	DB	00H
	DB	08H
	DW	037H
	DB	00H
	DB	09H
	DW	0cfH
	DB	011H
	DB	07H
	DW	0fH
	DB	00H
	DB	08H
	DW	067H
	DB	00H
	DB	08H
	DW	027H
	DB	00H
	DB	09H
	DW	0afH
	DB	00H
	DB	08H
	DW	07H
	DB	00H
	DB	08H
	DW	087H
	DB	00H
	DB	08H
	DW	047H
	DB	00H
	DB	09H
	DW	0efH
	DB	010H
	DB	07H
	DW	09H
	DB	00H
	DB	08H
	DW	05fH
	DB	00H
	DB	08H
	DW	01fH
	DB	00H
	DB	09H
	DW	09fH
	DB	014H
	DB	07H
	DW	063H
	DB	00H
	DB	08H
	DW	07fH
	DB	00H
	DB	08H
	DW	03fH
	DB	00H
	DB	09H
	DW	0dfH
	DB	012H
	DB	07H
	DW	01bH
	DB	00H
	DB	08H
	DW	06fH
	DB	00H
	DB	08H
	DW	02fH
	DB	00H
	DB	09H
	DW	0bfH
	DB	00H
	DB	08H
	DW	0fH
	DB	00H
	DB	08H
	DW	08fH
	DB	00H
	DB	08H
	DW	04fH
	DB	00H
	DB	09H
	DW	0ffH
?distfix@?1??fixedtables@@9@9 DB 010H			; `fixedtables'::`2'::distfix
	DB	05H
	DW	01H
	DB	017H
	DB	05H
	DW	0101H
	DB	013H
	DB	05H
	DW	011H
	DB	01bH
	DB	05H
	DW	01001H
	DB	011H
	DB	05H
	DW	05H
	DB	019H
	DB	05H
	DW	0401H
	DB	015H
	DB	05H
	DW	041H
	DB	01dH
	DB	05H
	DW	04001H
	DB	010H
	DB	05H
	DW	03H
	DB	018H
	DB	05H
	DW	0201H
	DB	014H
	DB	05H
	DW	021H
	DB	01cH
	DB	05H
	DW	02001H
	DB	012H
	DB	05H
	DW	09H
	DB	01aH
	DB	05H
	DW	0801H
	DB	016H
	DB	05H
	DW	081H
	DB	040H
	DB	05H
	DW	00H
	DB	010H
	DB	05H
	DW	02H
	DB	017H
	DB	05H
	DW	0181H
	DB	013H
	DB	05H
	DW	019H
	DB	01bH
	DB	05H
	DW	01801H
	DB	011H
	DB	05H
	DW	07H
	DB	019H
	DB	05H
	DW	0601H
	DB	015H
	DB	05H
	DW	061H
	DB	01dH
	DB	05H
	DW	06001H
	DB	010H
	DB	05H
	DW	04H
	DB	018H
	DB	05H
	DW	0301H
	DB	014H
	DB	05H
	DW	031H
	DB	01cH
	DB	05H
	DW	03001H
	DB	012H
	DB	05H
	DW	0dH
	DB	01aH
	DB	05H
	DW	0c01H
	DB	016H
	DB	05H
	DW	0c1H
	DB	040H
	DB	05H
	DW	00H
?order@?1??inflateBack@@9@9 DW 010H			; `inflateBack'::`2'::order
	DW	011H
	DW	012H
	DW	00H
	DW	08H
	DW	07H
	DW	09H
	DW	06H
	DW	0aH
	DW	05H
	DW	0bH
	DW	04H
	DW	0cH
	DW	03H
	DW	0dH
	DW	02H
	DW	0eH
	DW	01H
	DW	0fH
CONST	ENDS
PUBLIC	??_C@_05DFCKICEH@1?42?45?$AA@			; `string'
PUBLIC	_inflateBackInit_@20
EXTRN	_zcfree:PROC
EXTRN	_zcalloc:PROC
;	COMDAT ??_C@_05DFCKICEH@1?42?45?$AA@
; File c:\users\chris\downloads\zlib125\zlib-1.2.5\infback.c
CONST	SEGMENT
??_C@_05DFCKICEH@1?42?45?$AA@ DB '1.2.5', 00H		; `string'
; Function compile flags: /Odtp /ZI
CONST	ENDS
;	COMDAT _inflateBackInit_@20
_TEXT	SEGMENT
_state$ = -4						; size = 4
_strm$ = 8						; size = 4
_windowBits$ = 12					; size = 4
_window$ = 16						; size = 4
_version$ = 20						; size = 4
_stream_size$ = 24					; size = 4
_inflateBackInit_@20 PROC				; COMDAT

; 34   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 68					; 00000044H
	push	ebx
	push	esi
	push	edi

; 35   :     struct inflate_state FAR *state;
; 36   : 
; 37   :     if (version == Z_NULL || version[0] != ZLIB_VERSION[0] ||
; 38   :         stream_size != (int)(sizeof(z_stream)))

	cmp	DWORD PTR _version$[ebp], 0
	je	SHORT $LN6@inflateBac
	mov	eax, DWORD PTR _version$[ebp]
	movsx	ecx, BYTE PTR [eax]
	movsx	edx, BYTE PTR ??_C@_05DFCKICEH@1?42?45?$AA@
	cmp	ecx, edx
	jne	SHORT $LN6@inflateBac
	cmp	DWORD PTR _stream_size$[ebp], 56	; 00000038H
	je	SHORT $LN7@inflateBac
$LN6@inflateBac:

; 39   :         return Z_VERSION_ERROR;

	mov	eax, -6					; fffffffaH
	jmp	$LN8@inflateBac
$LN7@inflateBac:

; 40   :     if (strm == Z_NULL || window == Z_NULL ||
; 41   :         windowBits < 8 || windowBits > 15)

	cmp	DWORD PTR _strm$[ebp], 0
	je	SHORT $LN4@inflateBac
	cmp	DWORD PTR _window$[ebp], 0
	je	SHORT $LN4@inflateBac
	cmp	DWORD PTR _windowBits$[ebp], 8
	jl	SHORT $LN4@inflateBac
	cmp	DWORD PTR _windowBits$[ebp], 15		; 0000000fH
	jle	SHORT $LN5@inflateBac
$LN4@inflateBac:

; 42   :         return Z_STREAM_ERROR;

	mov	eax, -2					; fffffffeH
	jmp	$LN8@inflateBac
$LN5@inflateBac:

; 43   :     strm->msg = Z_NULL;                 /* in case we return an error */

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], 0

; 44   :     if (strm->zalloc == (alloc_func)0) {

	mov	eax, DWORD PTR _strm$[ebp]
	cmp	DWORD PTR [eax+32], 0
	jne	SHORT $LN3@inflateBac

; 45   :         strm->zalloc = zcalloc;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+32], OFFSET _zcalloc

; 46   :         strm->opaque = (voidpf)0;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+40], 0
$LN3@inflateBac:

; 47   :     }
; 48   :     if (strm->zfree == (free_func)0) strm->zfree = zcfree;

	mov	eax, DWORD PTR _strm$[ebp]
	cmp	DWORD PTR [eax+36], 0
	jne	SHORT $LN2@inflateBac
	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+36], OFFSET _zcfree
$LN2@inflateBac:

; 49   :     state = (struct inflate_state FAR *)ZALLOC(strm, 1,
; 50   :                                                sizeof(struct inflate_state));

	push	7116					; 00001bccH
	push	1
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	push	ecx
	mov	edx, DWORD PTR _strm$[ebp]
	mov	eax, DWORD PTR [edx+32]
	call	eax
	add	esp, 12					; 0000000cH
	mov	DWORD PTR _state$[ebp], eax

; 51   :     if (state == Z_NULL) return Z_MEM_ERROR;

	cmp	DWORD PTR _state$[ebp], 0
	jne	SHORT $LN1@inflateBac
	mov	eax, -4					; fffffffcH
	jmp	SHORT $LN8@inflateBac
$LN1@inflateBac:

; 52   :     Tracev((stderr, "inflate: allocated\n"));
; 53   :     strm->state = (struct internal_state FAR *)state;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+28], ecx

; 54   :     state->dmax = 32768U;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+20], 32768		; 00008000H

; 55   :     state->wbits = windowBits;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _windowBits$[ebp]
	mov	DWORD PTR [eax+36], ecx

; 56   :     state->wsize = 1U << windowBits;

	mov	eax, 1
	mov	ecx, DWORD PTR _windowBits$[ebp]
	shl	eax, cl
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+40], eax

; 57   :     state->window = window;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _window$[ebp]
	mov	DWORD PTR [eax+52], ecx

; 58   :     state->wnext = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+48], 0

; 59   :     state->whave = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+44], 0

; 60   :     return Z_OK;

	xor	eax, eax
$LN8@inflateBac:

; 61   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
_inflateBackInit_@20 ENDP
_TEXT	ENDS
PUBLIC	??_C@_0BO@ECPMAOGG@invalid?5distance?5too?5far?5back?$AA@ ; `string'
PUBLIC	??_C@_0BG@LBKINIKP@invalid?5distance?5code?$AA@	; `string'
PUBLIC	??_C@_0BM@FFFLPBBC@invalid?5literal?1length?5code?$AA@ ; `string'
PUBLIC	??_C@_0BG@GMDFCBGP@invalid?5distances?5set?$AA@	; `string'
PUBLIC	??_C@_0BM@IIMGAINC@invalid?5literal?1lengths?5set?$AA@ ; `string'
PUBLIC	??_C@_0CF@DGDMADCD@invalid?5code?5?9?9?5missing?5end?9of?9b@ ; `string'
PUBLIC	??_C@_0BK@BMMPFBBH@invalid?5bit?5length?5repeat?$AA@ ; `string'
PUBLIC	??_C@_0BJ@HDEPPGOH@invalid?5code?5lengths?5set?$AA@ ; `string'
PUBLIC	??_C@_0CE@GMIGFPBB@too?5many?5length?5or?5distance?5symb@ ; `string'
PUBLIC	??_C@_0BN@LGAADGOK@invalid?5stored?5block?5lengths?$AA@ ; `string'
PUBLIC	??_C@_0BD@PJCBIDD@invalid?5block?5type?$AA@	; `string'
PUBLIC	_inflateBack@20
EXTRN	_inflate_fast:PROC
EXTRN	_inflate_table:PROC
EXTRN	_memcpy:PROC
;	COMDAT ??_C@_0BO@ECPMAOGG@invalid?5distance?5too?5far?5back?$AA@
CONST	SEGMENT
??_C@_0BO@ECPMAOGG@invalid?5distance?5too?5far?5back?$AA@ DB 'invalid dis'
	DB	'tance too far back', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@LBKINIKP@invalid?5distance?5code?$AA@
CONST	SEGMENT
??_C@_0BG@LBKINIKP@invalid?5distance?5code?$AA@ DB 'invalid distance code'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@FFFLPBBC@invalid?5literal?1length?5code?$AA@
CONST	SEGMENT
??_C@_0BM@FFFLPBBC@invalid?5literal?1length?5code?$AA@ DB 'invalid litera'
	DB	'l/length code', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BG@GMDFCBGP@invalid?5distances?5set?$AA@
CONST	SEGMENT
??_C@_0BG@GMDFCBGP@invalid?5distances?5set?$AA@ DB 'invalid distances set'
	DB	00H						; `string'
CONST	ENDS
;	COMDAT ??_C@_0BM@IIMGAINC@invalid?5literal?1lengths?5set?$AA@
CONST	SEGMENT
??_C@_0BM@IIMGAINC@invalid?5literal?1lengths?5set?$AA@ DB 'invalid litera'
	DB	'l/lengths set', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CF@DGDMADCD@invalid?5code?5?9?9?5missing?5end?9of?9b@
CONST	SEGMENT
??_C@_0CF@DGDMADCD@invalid?5code?5?9?9?5missing?5end?9of?9b@ DB 'invalid '
	DB	'code -- missing end-of-block', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@BMMPFBBH@invalid?5bit?5length?5repeat?$AA@
CONST	SEGMENT
??_C@_0BK@BMMPFBBH@invalid?5bit?5length?5repeat?$AA@ DB 'invalid bit leng'
	DB	'th repeat', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@HDEPPGOH@invalid?5code?5lengths?5set?$AA@
CONST	SEGMENT
??_C@_0BJ@HDEPPGOH@invalid?5code?5lengths?5set?$AA@ DB 'invalid code leng'
	DB	'ths set', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0CE@GMIGFPBB@too?5many?5length?5or?5distance?5symb@
CONST	SEGMENT
??_C@_0CE@GMIGFPBB@too?5many?5length?5or?5distance?5symb@ DB 'too many le'
	DB	'ngth or distance symbols', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BN@LGAADGOK@invalid?5stored?5block?5lengths?$AA@
CONST	SEGMENT
??_C@_0BN@LGAADGOK@invalid?5stored?5block?5lengths?$AA@ DB 'invalid store'
	DB	'd block lengths', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@PJCBIDD@invalid?5block?5type?$AA@
CONST	SEGMENT
??_C@_0BD@PJCBIDD@invalid?5block?5type?$AA@ DB 'invalid block type', 00H ; `string'
; Function compile flags: /Odtp /ZI
CONST	ENDS
;	COMDAT _inflateBack@20
_TEXT	SEGMENT
tv137 = -120						; size = 4
tv76 = -120						; size = 4
tv73 = -120						; size = 4
_ret$ = -52						; size = 4
_len$ = -48						; size = 4
_last$ = -44						; size = 4
_here$ = -40						; size = 4
_from$ = -36						; size = 4
_copy$ = -32						; size = 4
_bits$ = -28						; size = 4
_hold$ = -24						; size = 4
_left$ = -20						; size = 4
_have$ = -16						; size = 4
_put$ = -12						; size = 4
_next$ = -8						; size = 4
_state$ = -4						; size = 4
_strm$ = 8						; size = 4
_in$ = 12						; size = 4
_in_desc$ = 16						; size = 4
_out$ = 20						; size = 4
_out_desc$ = 24						; size = 4
_inflateBack@20 PROC					; COMDAT

; 247  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 120				; 00000078H
	push	ebx
	push	esi
	push	edi

; 248  :     struct inflate_state FAR *state;
; 249  :     unsigned char FAR *next;    /* next input */
; 250  :     unsigned char FAR *put;     /* next output */
; 251  :     unsigned have, left;        /* available input and output */
; 252  :     unsigned long hold;         /* bit buffer */
; 253  :     unsigned bits;              /* bits in bit buffer */
; 254  :     unsigned copy;              /* number of stored or match bytes to copy */
; 255  :     unsigned char FAR *from;    /* where to copy match bytes from */
; 256  :     code here;                  /* current decoding table entry */
; 257  :     code last;                  /* parent table entry */
; 258  :     unsigned len;               /* length to copy for repeats, bits to drop */
; 259  :     int ret;                    /* return code */
; 260  :     static const unsigned short order[19] = /* permutation of code lengths */
; 261  :         {16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15};
; 262  : 
; 263  :     /* Check that the strm exists and that the state was initialized */
; 264  :     if (strm == Z_NULL || strm->state == Z_NULL)

	cmp	DWORD PTR _strm$[ebp], 0
	je	SHORT $LN346@inflateBac@2
	mov	eax, DWORD PTR _strm$[ebp]
	cmp	DWORD PTR [eax+28], 0
	jne	SHORT $LN347@inflateBac@2
$LN346@inflateBac@2:

; 265  :         return Z_STREAM_ERROR;

	mov	eax, -2					; fffffffeH
	jmp	$LN348@inflateBac@2
$LN347@inflateBac@2:

; 266  :     state = (struct inflate_state FAR *)strm->state;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _state$[ebp], ecx

; 267  : 
; 268  :     /* Reset the state */
; 269  :     strm->msg = Z_NULL;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], 0

; 270  :     state->mode = TYPE;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 11			; 0000000bH

; 271  :     state->last = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+4], 0

; 272  :     state->whave = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+44], 0

; 273  :     next = strm->next_in;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _next$[ebp], ecx

; 274  :     have = next != Z_NULL ? strm->avail_in : 0;

	cmp	DWORD PTR _next$[ebp], 0
	je	SHORT $LN350@inflateBac@2
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR tv73[ebp], ecx
	jmp	SHORT $LN351@inflateBac@2
$LN350@inflateBac@2:
	mov	DWORD PTR tv73[ebp], 0
$LN351@inflateBac@2:
	mov	edx, DWORD PTR tv73[ebp]
	mov	DWORD PTR _have$[ebp], edx

; 275  :     hold = 0;

	mov	DWORD PTR _hold$[ebp], 0

; 276  :     bits = 0;

	mov	DWORD PTR _bits$[ebp], 0

; 277  :     put = state->window;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+52]
	mov	DWORD PTR _put$[ebp], ecx

; 278  :     left = state->wsize;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	mov	DWORD PTR _left$[ebp], ecx
$LN345@inflateBac@2:

; 279  : 
; 280  :     /* Inflate until end of block marked as last */
; 281  :     for (;;)
; 282  :         switch (state->mode) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR tv76[ebp], ecx
	mov	edx, DWORD PTR tv76[ebp]
	sub	edx, 11					; 0000000bH
	mov	DWORD PTR tv76[ebp], edx
	cmp	DWORD PTR tv76[ebp], 18			; 00000012H
	ja	$LN1@inflateBac@2
	mov	eax, DWORD PTR tv76[ebp]
	movzx	ecx, BYTE PTR $LN352@inflateBac@2[eax]
	jmp	DWORD PTR $LN353@inflateBac@2[ecx*4]
$LN341@inflateBac@2:

; 283  :         case TYPE:
; 284  :             /* determine and dispatch block type */
; 285  :             if (state->last) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+4], 0
	je	SHORT $LN333@inflateBac@2
$LN339@inflateBac@2:

; 286  :                 BYTEBITS();

	mov	ecx, DWORD PTR _bits$[ebp]
	and	ecx, 7
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	and	eax, 7
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN339@inflateBac@2

; 287  :                 state->mode = DONE;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 28			; 0000001cH

; 288  :                 break;

	jmp	$LN342@inflateBac@2
$LN333@inflateBac@2:

; 289  :             }
; 290  :             NEEDBITS(3);

	cmp	DWORD PTR _bits$[ebp], 3
	jae	SHORT $LN335@inflateBac@2
$LN328@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN327@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN327@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN327@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN328@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN328@inflateBac@2
	jmp	SHORT $LN333@inflateBac@2
$LN335@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN333@inflateBac@2

; 291  :             state->last = BITS(1);

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 1
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+4], eax
$LN323@inflateBac@2:

; 292  :             DROPBITS(1);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 1
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 1
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN323@inflateBac@2

; 293  :             switch (BITS(2)) {

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 3
	mov	DWORD PTR tv137[ebp], eax
	cmp	DWORD PTR tv137[ebp], 3
	ja	SHORT $LN314@inflateBac@2
	mov	ecx, DWORD PTR tv137[ebp]
	jmp	DWORD PTR $LN354@inflateBac@2[ecx*4]
$LN318@inflateBac@2:

; 294  :             case 0:                             /* stored block */
; 295  :                 Tracev((stderr, "inflate:     stored block%s\n",
; 296  :                         state->last ? " (last)" : ""));
; 297  :                 state->mode = STORED;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 13			; 0000000dH

; 298  :                 break;

	jmp	SHORT $LN314@inflateBac@2
$LN317@inflateBac@2:

; 299  :             case 1:                             /* fixed block */
; 300  :                 fixedtables(state);

	mov	eax, DWORD PTR _state$[ebp]
	push	eax
	call	_fixedtables
	add	esp, 4

; 301  :                 Tracev((stderr, "inflate:     fixed codes block%s\n",
; 302  :                         state->last ? " (last)" : ""));
; 303  :                 state->mode = LEN;              /* decode codes */

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 20			; 00000014H

; 304  :                 break;

	jmp	SHORT $LN314@inflateBac@2
$LN316@inflateBac@2:

; 305  :             case 2:                             /* dynamic block */
; 306  :                 Tracev((stderr, "inflate:     dynamic codes block%s\n",
; 307  :                         state->last ? " (last)" : ""));
; 308  :                 state->mode = TABLE;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 16			; 00000010H

; 309  :                 break;

	jmp	SHORT $LN314@inflateBac@2
$LN315@inflateBac@2:

; 310  :             case 3:
; 311  :                 strm->msg = (char *)"invalid block type";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BD@PJCBIDD@invalid?5block?5type?$AA@

; 312  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH
$LN314@inflateBac@2:

; 313  :             }
; 314  :             DROPBITS(2);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 2
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 2
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN314@inflateBac@2

; 315  :             break;

	jmp	$LN342@inflateBac@2
$LN310@inflateBac@2:

; 316  : 
; 317  :         case STORED:
; 318  :             /* get and verify stored block length */
; 319  :             BYTEBITS();                         /* go to byte boundary */

	mov	ecx, DWORD PTR _bits$[ebp]
	and	ecx, 7
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	and	eax, 7
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN310@inflateBac@2
$LN304@inflateBac@2:

; 320  :             NEEDBITS(32);

	cmp	DWORD PTR _bits$[ebp], 32		; 00000020H
	jae	SHORT $LN306@inflateBac@2
$LN299@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN298@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN298@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN298@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN299@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN299@inflateBac@2
	jmp	SHORT $LN304@inflateBac@2
$LN306@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN304@inflateBac@2

; 321  :             if ((hold & 0xffff) != ((hold >> 16) ^ 0xffff)) {

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 65535				; 0000ffffH
	mov	ecx, DWORD PTR _hold$[ebp]
	shr	ecx, 16					; 00000010H
	xor	ecx, 65535				; 0000ffffH
	cmp	eax, ecx
	je	SHORT $LN294@inflateBac@2

; 322  :                 strm->msg = (char *)"invalid stored block lengths";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BN@LGAADGOK@invalid?5stored?5block?5lengths?$AA@

; 323  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 324  :                 break;

	jmp	$LN342@inflateBac@2
$LN294@inflateBac@2:

; 325  :             }
; 326  :             state->length = (unsigned)hold & 0xffff;

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 65535				; 0000ffffH
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+64], eax
$LN293@inflateBac@2:

; 327  :             Tracev((stderr, "inflate:       stored length %u\n",
; 328  :                     state->length));
; 329  :             INITBITS();

	mov	DWORD PTR _hold$[ebp], 0
	mov	DWORD PTR _bits$[ebp], 0
	xor	eax, eax
	jne	SHORT $LN293@inflateBac@2
$LN290@inflateBac@2:

; 330  : 
; 331  :             /* copy stored block from input to output */
; 332  :             while (state->length != 0) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+64], 0
	je	$LN289@inflateBac@2

; 333  :                 copy = state->length;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+64]
	mov	DWORD PTR _copy$[ebp], ecx
$LN288@inflateBac@2:

; 334  :                 PULL();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN287@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN287@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN287@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN288@inflateBac@2
$LN283@inflateBac@2:

; 335  :                 ROOM();

	cmp	DWORD PTR _left$[ebp], 0
	jne	SHORT $LN282@inflateBac@2
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+52]
	mov	DWORD PTR _put$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	mov	DWORD PTR _left$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _left$[ebp]
	mov	DWORD PTR [eax+44], ecx
	mov	eax, DWORD PTR _left$[ebp]
	push	eax
	mov	ecx, DWORD PTR _put$[ebp]
	push	ecx
	mov	edx, DWORD PTR _out_desc$[ebp]
	push	edx
	call	DWORD PTR _out$[ebp]
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN282@inflateBac@2
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN282@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN283@inflateBac@2

; 336  :                 if (copy > have) copy = have;

	mov	eax, DWORD PTR _copy$[ebp]
	cmp	eax, DWORD PTR _have$[ebp]
	jbe	SHORT $LN278@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	mov	DWORD PTR _copy$[ebp], eax
$LN278@inflateBac@2:

; 337  :                 if (copy > left) copy = left;

	mov	eax, DWORD PTR _copy$[ebp]
	cmp	eax, DWORD PTR _left$[ebp]
	jbe	SHORT $LN277@inflateBac@2
	mov	eax, DWORD PTR _left$[ebp]
	mov	DWORD PTR _copy$[ebp], eax
$LN277@inflateBac@2:

; 338  :                 zmemcpy(put, next, copy);

	mov	eax, DWORD PTR _copy$[ebp]
	push	eax
	mov	ecx, DWORD PTR _next$[ebp]
	push	ecx
	mov	edx, DWORD PTR _put$[ebp]
	push	edx
	call	_memcpy
	add	esp, 12					; 0000000cH

; 339  :                 have -= copy;

	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _have$[ebp], eax

; 340  :                 next += copy;

	mov	eax, DWORD PTR _next$[ebp]
	add	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _next$[ebp], eax

; 341  :                 left -= copy;

	mov	eax, DWORD PTR _left$[ebp]
	sub	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _left$[ebp], eax

; 342  :                 put += copy;

	mov	eax, DWORD PTR _put$[ebp]
	add	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _put$[ebp], eax

; 343  :                 state->length -= copy;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+64]
	sub	ecx, DWORD PTR _copy$[ebp]
	mov	edx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [edx+64], ecx

; 344  :             }

	jmp	$LN290@inflateBac@2
$LN289@inflateBac@2:

; 345  :             Tracev((stderr, "inflate:       stored end\n"));
; 346  :             state->mode = TYPE;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 11			; 0000000bH

; 347  :             break;

	jmp	$LN342@inflateBac@2
$LN272@inflateBac@2:

; 348  : 
; 349  :         case TABLE:
; 350  :             /* get dynamic table entries descriptor */
; 351  :             NEEDBITS(14);

	cmp	DWORD PTR _bits$[ebp], 14		; 0000000eH
	jae	SHORT $LN274@inflateBac@2
$LN267@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN266@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN266@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN266@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN267@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN267@inflateBac@2
	jmp	SHORT $LN272@inflateBac@2
$LN274@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN272@inflateBac@2

; 352  :             state->nlen = BITS(5) + 257;

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 31					; 0000001fH
	add	eax, 257				; 00000101H
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+96], eax
$LN262@inflateBac@2:

; 353  :             DROPBITS(5);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 5
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 5
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN262@inflateBac@2

; 354  :             state->ndist = BITS(5) + 1;

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 31					; 0000001fH
	add	eax, 1
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+100], eax
$LN259@inflateBac@2:

; 355  :             DROPBITS(5);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 5
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 5
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN259@inflateBac@2

; 356  :             state->ncode = BITS(4) + 4;

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 15					; 0000000fH
	add	eax, 4
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+92], eax
$LN256@inflateBac@2:

; 357  :             DROPBITS(4);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 4
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 4
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN256@inflateBac@2

; 358  : #ifndef PKZIP_BUG_WORKAROUND
; 359  :             if (state->nlen > 286 || state->ndist > 30) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+96], 286			; 0000011eH
	ja	SHORT $LN252@inflateBac@2
	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+100], 30			; 0000001eH
	jbe	SHORT $LN253@inflateBac@2
$LN252@inflateBac@2:

; 360  :                 strm->msg = (char *)"too many length or distance symbols";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0CE@GMIGFPBB@too?5many?5length?5or?5distance?5symb@

; 361  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 362  :                 break;

	jmp	$LN342@inflateBac@2
$LN253@inflateBac@2:

; 363  :             }
; 364  : #endif
; 365  :             Tracev((stderr, "inflate:       table sizes ok\n"));
; 366  : 
; 367  :             /* get code length code lengths (not a typo) */
; 368  :             state->have = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+104], 0
$LN251@inflateBac@2:

; 369  :             while (state->have < state->ncode) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [eax+104]
	cmp	edx, DWORD PTR [ecx+92]
	jae	$LN233@inflateBac@2
$LN246@inflateBac@2:

; 370  :                 NEEDBITS(3);

	cmp	DWORD PTR _bits$[ebp], 3
	jae	SHORT $LN248@inflateBac@2
$LN241@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN240@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN240@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN240@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN241@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN241@inflateBac@2
	jmp	SHORT $LN246@inflateBac@2
$LN248@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN246@inflateBac@2

; 371  :                 state->lens[order[state->have++]] = (unsigned short)BITS(3);

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 7
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+104]
	movzx	ecx, WORD PTR ?order@?1??inflateBack@@9@9[edx*2]
	mov	edx, DWORD PTR _state$[ebp]
	mov	WORD PTR [edx+ecx*2+112], ax
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	add	ecx, 1
	mov	edx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [edx+104], ecx
$LN236@inflateBac@2:

; 372  :                 DROPBITS(3);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 3
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 3
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN236@inflateBac@2

; 373  :             }

	jmp	$LN251@inflateBac@2
$LN233@inflateBac@2:

; 374  :             while (state->have < 19)

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+104], 19			; 00000013H
	jae	SHORT $LN232@inflateBac@2

; 375  :                 state->lens[order[state->have++]] = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	movzx	edx, WORD PTR ?order@?1??inflateBack@@9@9[ecx*2]
	xor	eax, eax
	mov	ecx, DWORD PTR _state$[ebp]
	mov	WORD PTR [ecx+edx*2+112], ax
	mov	edx, DWORD PTR _state$[ebp]
	mov	eax, DWORD PTR [edx+104]
	add	eax, 1
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+104], eax
	jmp	SHORT $LN233@inflateBac@2
$LN232@inflateBac@2:

; 376  :             state->next = state->codes;

	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 1328				; 00000530H
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+108], eax

; 377  :             state->lencode = (code const FAR *)(state->next);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+108]
	mov	DWORD PTR [eax+76], edx

; 378  :             state->lenbits = 7;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+84], 7

; 379  :             ret = inflate_table(CODES, state->lens, 19, &(state->next),
; 380  :                                 &(state->lenbits), state->work);

	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 752				; 000002f0H
	push	eax
	mov	ecx, DWORD PTR _state$[ebp]
	add	ecx, 84					; 00000054H
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	add	edx, 108				; 0000006cH
	push	edx
	push	19					; 00000013H
	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 112				; 00000070H
	push	eax
	push	0
	call	_inflate_table
	add	esp, 24					; 00000018H
	mov	DWORD PTR _ret$[ebp], eax

; 381  :             if (ret) {

	cmp	DWORD PTR _ret$[ebp], 0
	je	SHORT $LN231@inflateBac@2

; 382  :                 strm->msg = (char *)"invalid code lengths set";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BJ@HDEPPGOH@invalid?5code?5lengths?5set?$AA@

; 383  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 384  :                 break;

	jmp	$LN342@inflateBac@2
$LN231@inflateBac@2:

; 385  :             }
; 386  :             Tracev((stderr, "inflate:       code lengths ok\n"));
; 387  : 
; 388  :             /* get length and distance code code lengths */
; 389  :             state->have = 0;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+104], 0
$LN230@inflateBac@2:

; 390  :             while (state->have < state->nlen + state->ndist) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+96]
	mov	edx, DWORD PTR _state$[ebp]
	add	ecx, DWORD PTR [edx+100]
	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+104], ecx
	jae	$LN229@inflateBac@2
$LN228@inflateBac@2:

; 391  :                 for (;;) {
; 392  :                     here = state->lencode[BITS(state->lenbits)];

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax+84]
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+76]
	mov	edx, DWORD PTR [ecx+edx*4]
	mov	DWORD PTR _here$[ebp], edx

; 393  :                     if ((unsigned)(here.bits) <= bits) break;

	movzx	eax, BYTE PTR _here$[ebp+1]
	cmp	eax, DWORD PTR _bits$[ebp]
	ja	SHORT $LN222@inflateBac@2
	jmp	SHORT $LN227@inflateBac@2
$LN222@inflateBac@2:

; 394  :                     PULLBYTE();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN221@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN221@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN221@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN222@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN222@inflateBac@2

; 395  :                 }

	jmp	$LN228@inflateBac@2
$LN227@inflateBac@2:

; 396  :                 if (here.val < 16) {

	movzx	eax, WORD PTR _here$[ebp+2]
	cmp	eax, 16					; 00000010H
	jge	$LN217@inflateBac@2
$LN213@inflateBac@2:

; 397  :                     NEEDBITS(here.bits);

	movzx	eax, BYTE PTR _here$[ebp+1]
	cmp	DWORD PTR _bits$[ebp], eax
	jae	SHORT $LN215@inflateBac@2
$LN208@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN207@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN207@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN207@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN208@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN208@inflateBac@2
	jmp	SHORT $LN213@inflateBac@2
$LN215@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN213@inflateBac@2
$LN203@inflateBac@2:

; 398  :                     DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN203@inflateBac@2

; 399  :                     state->lens[state->have++] = here.val;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	mov	edx, DWORD PTR _state$[ebp]
	mov	ax, WORD PTR _here$[ebp+2]
	mov	WORD PTR [edx+ecx*2+112], ax
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+104]
	add	edx, 1
	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+104], edx

; 400  :                 }
; 401  :                 else {

	jmp	$LN200@inflateBac@2
$LN217@inflateBac@2:

; 402  :                     if (here.val == 16) {

	movzx	eax, WORD PTR _here$[ebp+2]
	cmp	eax, 16					; 00000010H
	jne	$LN199@inflateBac@2
$LN195@inflateBac@2:

; 403  :                         NEEDBITS(here.bits + 2);

	movzx	eax, BYTE PTR _here$[ebp+1]
	add	eax, 2
	cmp	DWORD PTR _bits$[ebp], eax
	jae	SHORT $LN197@inflateBac@2
$LN190@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN189@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN189@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN189@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN190@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN190@inflateBac@2
	jmp	SHORT $LN195@inflateBac@2
$LN197@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN195@inflateBac@2
$LN185@inflateBac@2:

; 404  :                         DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN185@inflateBac@2

; 405  :                         if (state->have == 0) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+104], 0
	jne	SHORT $LN182@inflateBac@2

; 406  :                             strm->msg = (char *)"invalid bit length repeat";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BK@BMMPFBBH@invalid?5bit?5length?5repeat?$AA@

; 407  :                             state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 408  :                             break;

	jmp	$LN229@inflateBac@2
$LN182@inflateBac@2:

; 409  :                         }
; 410  :                         len = (unsigned)(state->lens[state->have - 1]);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	mov	edx, DWORD PTR _state$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2+110]
	mov	DWORD PTR _len$[ebp], eax

; 411  :                         copy = 3 + BITS(2);

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 3
	add	eax, 3
	mov	DWORD PTR _copy$[ebp], eax
$LN181@inflateBac@2:

; 412  :                         DROPBITS(2);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 2
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 2
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN181@inflateBac@2

; 413  :                     }
; 414  :                     else if (here.val == 17) {

	jmp	$LN178@inflateBac@2
$LN199@inflateBac@2:
	movzx	eax, WORD PTR _here$[ebp+2]
	cmp	eax, 17					; 00000011H
	jne	$LN153@inflateBac@2
$LN173@inflateBac@2:

; 415  :                         NEEDBITS(here.bits + 3);

	movzx	eax, BYTE PTR _here$[ebp+1]
	add	eax, 3
	cmp	DWORD PTR _bits$[ebp], eax
	jae	SHORT $LN175@inflateBac@2
$LN168@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN167@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN167@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN167@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN168@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN168@inflateBac@2
	jmp	SHORT $LN173@inflateBac@2
$LN175@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN173@inflateBac@2
$LN163@inflateBac@2:

; 416  :                         DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN163@inflateBac@2

; 417  :                         len = 0;

	mov	DWORD PTR _len$[ebp], 0

; 418  :                         copy = 3 + BITS(3);

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 7
	add	eax, 3
	mov	DWORD PTR _copy$[ebp], eax
$LN160@inflateBac@2:

; 419  :                         DROPBITS(3);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 3
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 3
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN160@inflateBac@2

; 420  :                     }
; 421  :                     else {

	jmp	$LN178@inflateBac@2
$LN153@inflateBac@2:

; 422  :                         NEEDBITS(here.bits + 7);

	movzx	eax, BYTE PTR _here$[ebp+1]
	add	eax, 7
	cmp	DWORD PTR _bits$[ebp], eax
	jae	SHORT $LN155@inflateBac@2
$LN148@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN147@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN147@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN147@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN148@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN148@inflateBac@2
	jmp	SHORT $LN153@inflateBac@2
$LN155@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN153@inflateBac@2
$LN143@inflateBac@2:

; 423  :                         DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN143@inflateBac@2

; 424  :                         len = 0;

	mov	DWORD PTR _len$[ebp], 0

; 425  :                         copy = 11 + BITS(7);

	mov	eax, DWORD PTR _hold$[ebp]
	and	eax, 127				; 0000007fH
	add	eax, 11					; 0000000bH
	mov	DWORD PTR _copy$[ebp], eax
$LN140@inflateBac@2:

; 426  :                         DROPBITS(7);

	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, 7
	mov	DWORD PTR _hold$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	sub	eax, 7
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN140@inflateBac@2
$LN178@inflateBac@2:

; 427  :                     }
; 428  :                     if (state->have + copy > state->nlen + state->ndist) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	add	ecx, DWORD PTR _copy$[ebp]
	mov	edx, DWORD PTR _state$[ebp]
	mov	eax, DWORD PTR [edx+96]
	mov	edx, DWORD PTR _state$[ebp]
	add	eax, DWORD PTR [edx+100]
	cmp	ecx, eax
	jbe	SHORT $LN136@inflateBac@2

; 429  :                         strm->msg = (char *)"invalid bit length repeat";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BK@BMMPFBBH@invalid?5bit?5length?5repeat?$AA@

; 430  :                         state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 431  :                         break;

	jmp	SHORT $LN229@inflateBac@2
$LN136@inflateBac@2:

; 432  :                     }
; 433  :                     while (copy--)

	mov	eax, DWORD PTR _copy$[ebp]
	mov	ecx, DWORD PTR _copy$[ebp]
	sub	ecx, 1
	mov	DWORD PTR _copy$[ebp], ecx
	test	eax, eax
	je	SHORT $LN200@inflateBac@2

; 434  :                         state->lens[state->have++] = (unsigned short)len;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+104]
	mov	edx, DWORD PTR _state$[ebp]
	mov	ax, WORD PTR _len$[ebp]
	mov	WORD PTR [edx+ecx*2+112], ax
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+104]
	add	edx, 1
	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+104], edx
	jmp	SHORT $LN136@inflateBac@2
$LN200@inflateBac@2:

; 435  :                 }
; 436  :             }

	jmp	$LN230@inflateBac@2
$LN229@inflateBac@2:

; 437  : 
; 438  :             /* handle error breaks in while */
; 439  :             if (state->mode == BAD) break;

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax], 29			; 0000001dH
	jne	SHORT $LN134@inflateBac@2
	jmp	$LN342@inflateBac@2
$LN134@inflateBac@2:

; 440  : 
; 441  :             /* check for end-of-block code (better have one) */
; 442  :             if (state->lens[256] == 0) {

	mov	eax, DWORD PTR _state$[ebp]
	movzx	ecx, WORD PTR [eax+624]
	test	ecx, ecx
	jne	SHORT $LN133@inflateBac@2

; 443  :                 strm->msg = (char *)"invalid code -- missing end-of-block";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0CF@DGDMADCD@invalid?5code?5?9?9?5missing?5end?9of?9b@

; 444  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 445  :                 break;

	jmp	$LN342@inflateBac@2
$LN133@inflateBac@2:

; 446  :             }
; 447  : 
; 448  :             /* build code tables -- note: do not change the lenbits or distbits
; 449  :                values here (9 and 6) without reading the comments in inftrees.h
; 450  :                concerning the ENOUGH constants, which depend on those values */
; 451  :             state->next = state->codes;

	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 1328				; 00000530H
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+108], eax

; 452  :             state->lencode = (code const FAR *)(state->next);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+108]
	mov	DWORD PTR [eax+76], edx

; 453  :             state->lenbits = 9;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+84], 9

; 454  :             ret = inflate_table(LENS, state->lens, state->nlen, &(state->next),
; 455  :                                 &(state->lenbits), state->work);

	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 752				; 000002f0H
	push	eax
	mov	ecx, DWORD PTR _state$[ebp]
	add	ecx, 84					; 00000054H
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	add	edx, 108				; 0000006cH
	push	edx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+96]
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	add	edx, 112				; 00000070H
	push	edx
	push	1
	call	_inflate_table
	add	esp, 24					; 00000018H
	mov	DWORD PTR _ret$[ebp], eax

; 456  :             if (ret) {

	cmp	DWORD PTR _ret$[ebp], 0
	je	SHORT $LN132@inflateBac@2

; 457  :                 strm->msg = (char *)"invalid literal/lengths set";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BM@IIMGAINC@invalid?5literal?1lengths?5set?$AA@

; 458  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 459  :                 break;

	jmp	$LN342@inflateBac@2
$LN132@inflateBac@2:

; 460  :             }
; 461  :             state->distcode = (code const FAR *)(state->next);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+108]
	mov	DWORD PTR [eax+80], edx

; 462  :             state->distbits = 6;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+88], 6

; 463  :             ret = inflate_table(DISTS, state->lens + state->nlen, state->ndist,
; 464  :                             &(state->next), &(state->distbits), state->work);

	mov	eax, DWORD PTR _state$[ebp]
	add	eax, 752				; 000002f0H
	push	eax
	mov	ecx, DWORD PTR _state$[ebp]
	add	ecx, 88					; 00000058H
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	add	edx, 108				; 0000006cH
	push	edx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+100]
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	mov	eax, DWORD PTR [edx+96]
	mov	ecx, DWORD PTR _state$[ebp]
	lea	edx, DWORD PTR [ecx+eax*2+112]
	push	edx
	push	2
	call	_inflate_table
	add	esp, 24					; 00000018H
	mov	DWORD PTR _ret$[ebp], eax

; 465  :             if (ret) {

	cmp	DWORD PTR _ret$[ebp], 0
	je	SHORT $LN131@inflateBac@2

; 466  :                 strm->msg = (char *)"invalid distances set";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BG@GMDFCBGP@invalid?5distances?5set?$AA@

; 467  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 468  :                 break;

	jmp	$LN342@inflateBac@2
$LN131@inflateBac@2:

; 469  :             }
; 470  :             Tracev((stderr, "inflate:       codes ok\n"));
; 471  :             state->mode = LEN;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 20			; 00000014H
$LN130@inflateBac@2:

; 472  : 
; 473  :         case LEN:
; 474  :             /* use inflate_fast() if we have enough input and output */
; 475  :             if (have >= 6 && left >= 258) {

	cmp	DWORD PTR _have$[ebp], 6
	jb	$LN121@inflateBac@2
	cmp	DWORD PTR _left$[ebp], 258		; 00000102H
	jb	$LN121@inflateBac@2
$LN128@inflateBac@2:

; 476  :                 RESTORE();

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _put$[ebp]
	mov	DWORD PTR [eax+12], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _left$[ebp]
	mov	DWORD PTR [eax+16], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _next$[ebp]
	mov	DWORD PTR [eax], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _have$[ebp]
	mov	DWORD PTR [eax+4], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR [eax+56], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _bits$[ebp]
	mov	DWORD PTR [eax+60], ecx
	xor	eax, eax
	jne	SHORT $LN128@inflateBac@2

; 477  :                 if (state->whave < state->wsize)

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [eax+44]
	cmp	edx, DWORD PTR [ecx+40]
	jae	SHORT $LN125@inflateBac@2

; 478  :                     state->whave = state->wsize - left;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	sub	ecx, DWORD PTR _left$[ebp]
	mov	edx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [edx+44], ecx
$LN125@inflateBac@2:

; 479  :                 inflate_fast(strm, state->wsize);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	push	ecx
	mov	edx, DWORD PTR _strm$[ebp]
	push	edx
	call	_inflate_fast
	add	esp, 8
$LN124@inflateBac@2:

; 480  :                 LOAD();

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	DWORD PTR _put$[ebp], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+16]
	mov	DWORD PTR _left$[ebp], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax]
	mov	DWORD PTR _next$[ebp], ecx
	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+4]
	mov	DWORD PTR _have$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+56]
	mov	DWORD PTR _hold$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN124@inflateBac@2

; 481  :                 break;

	jmp	$LN342@inflateBac@2
$LN121@inflateBac@2:

; 482  :             }
; 483  : 
; 484  :             /* get a literal, length, or end-of-block code */
; 485  :             for (;;) {
; 486  :                 here = state->lencode[BITS(state->lenbits)];

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax+84]
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+76]
	mov	edx, DWORD PTR [ecx+edx*4]
	mov	DWORD PTR _here$[ebp], edx

; 487  :                 if ((unsigned)(here.bits) <= bits) break;

	movzx	eax, BYTE PTR _here$[ebp+1]
	cmp	eax, DWORD PTR _bits$[ebp]
	ja	SHORT $LN115@inflateBac@2
	jmp	SHORT $LN120@inflateBac@2
$LN115@inflateBac@2:

; 488  :                 PULLBYTE();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN114@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN114@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN114@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN115@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN115@inflateBac@2

; 489  :             }

	jmp	$LN121@inflateBac@2
$LN120@inflateBac@2:

; 490  :             if (here.op && (here.op & 0xf0) == 0) {

	movzx	eax, BYTE PTR _here$[ebp]
	test	eax, eax
	je	$LN95@inflateBac@2
	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 240				; 000000f0H
	jne	$LN95@inflateBac@2

; 491  :                 last = here;

	mov	eax, DWORD PTR _here$[ebp]
	mov	DWORD PTR _last$[ebp], eax
$LN109@inflateBac@2:

; 492  :                 for (;;) {
; 493  :                     here = state->lencode[last.val +
; 494  :                             (BITS(last.bits + last.op) >> last.bits)];

	movzx	eax, WORD PTR _last$[ebp+2]
	movzx	ecx, BYTE PTR _last$[ebp+1]
	movzx	edx, BYTE PTR _last$[ebp]
	add	ecx, edx
	mov	edx, 1
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	movzx	ecx, BYTE PTR _last$[ebp+1]
	shr	edx, cl
	add	eax, edx
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+76]
	mov	eax, DWORD PTR [edx+eax*4]
	mov	DWORD PTR _here$[ebp], eax

; 495  :                     if ((unsigned)(last.bits + here.bits) <= bits) break;

	movzx	eax, BYTE PTR _last$[ebp+1]
	movzx	ecx, BYTE PTR _here$[ebp+1]
	add	eax, ecx
	cmp	eax, DWORD PTR _bits$[ebp]
	ja	SHORT $LN103@inflateBac@2
	jmp	SHORT $LN98@inflateBac@2
$LN103@inflateBac@2:

; 496  :                     PULLBYTE();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN102@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN102@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN102@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN103@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN103@inflateBac@2

; 497  :                 }

	jmp	$LN109@inflateBac@2
$LN98@inflateBac@2:

; 498  :                 DROPBITS(last.bits);

	movzx	ecx, BYTE PTR _last$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _last$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN98@inflateBac@2
$LN95@inflateBac@2:

; 499  :             }
; 500  :             DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN95@inflateBac@2

; 501  :             state->length = (unsigned)here.val;

	movzx	eax, WORD PTR _here$[ebp+2]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+64], eax

; 502  : 
; 503  :             /* process literal */
; 504  :             if (here.op == 0) {

	movzx	eax, BYTE PTR _here$[ebp]
	test	eax, eax
	jne	SHORT $LN92@inflateBac@2
$LN91@inflateBac@2:

; 505  :                 Tracevv((stderr, here.val >= 0x20 && here.val < 0x7f ?
; 506  :                         "inflate:         literal '%c'\n" :
; 507  :                         "inflate:         literal 0x%02x\n", here.val));
; 508  :                 ROOM();

	cmp	DWORD PTR _left$[ebp], 0
	jne	SHORT $LN90@inflateBac@2
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+52]
	mov	DWORD PTR _put$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	mov	DWORD PTR _left$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _left$[ebp]
	mov	DWORD PTR [eax+44], ecx
	mov	eax, DWORD PTR _left$[ebp]
	push	eax
	mov	ecx, DWORD PTR _put$[ebp]
	push	ecx
	mov	edx, DWORD PTR _out_desc$[ebp]
	push	edx
	call	DWORD PTR _out$[ebp]
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN90@inflateBac@2
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN90@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN91@inflateBac@2

; 509  :                 *put++ = (unsigned char)(state->length);

	mov	eax, DWORD PTR _put$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	dl, BYTE PTR [ecx+64]
	mov	BYTE PTR [eax], dl
	mov	eax, DWORD PTR _put$[ebp]
	add	eax, 1
	mov	DWORD PTR _put$[ebp], eax

; 510  :                 left--;

	mov	eax, DWORD PTR _left$[ebp]
	sub	eax, 1
	mov	DWORD PTR _left$[ebp], eax

; 511  :                 state->mode = LEN;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 20			; 00000014H

; 512  :                 break;

	jmp	$LN342@inflateBac@2
$LN92@inflateBac@2:

; 513  :             }
; 514  : 
; 515  :             /* process end of block */
; 516  :             if (here.op & 32) {

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 32					; 00000020H
	je	SHORT $LN86@inflateBac@2

; 517  :                 Tracevv((stderr, "inflate:         end of block\n"));
; 518  :                 state->mode = TYPE;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 11			; 0000000bH

; 519  :                 break;

	jmp	$LN342@inflateBac@2
$LN86@inflateBac@2:

; 520  :             }
; 521  : 
; 522  :             /* invalid code */
; 523  :             if (here.op & 64) {

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 64					; 00000040H
	je	SHORT $LN85@inflateBac@2

; 524  :                 strm->msg = (char *)"invalid literal/length code";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BM@FFFLPBBC@invalid?5literal?1length?5code?$AA@

; 525  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 526  :                 break;

	jmp	$LN342@inflateBac@2
$LN85@inflateBac@2:

; 527  :             }
; 528  : 
; 529  :             /* length code -- get extra bits, if any */
; 530  :             state->extra = (unsigned)(here.op) & 15;

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 15					; 0000000fH
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+72], eax

; 531  :             if (state->extra != 0) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+72], 0
	je	$LN67@inflateBac@2
$LN80@inflateBac@2:

; 532  :                 NEEDBITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _bits$[ebp]
	cmp	ecx, DWORD PTR [eax+72]
	jae	SHORT $LN82@inflateBac@2
$LN75@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN74@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN74@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN74@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN75@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN75@inflateBac@2
	jmp	SHORT $LN80@inflateBac@2
$LN82@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN80@inflateBac@2

; 533  :                 state->length += BITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax+72]
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	mov	eax, DWORD PTR _state$[ebp]
	add	edx, DWORD PTR [eax+64]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+64], edx
$LN70@inflateBac@2:

; 534  :                 DROPBITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR _hold$[ebp]
	mov	ecx, DWORD PTR [eax+72]
	shr	edx, cl
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, DWORD PTR [eax+72]
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN70@inflateBac@2
$LN67@inflateBac@2:

; 535  :             }
; 536  :             Tracevv((stderr, "inflate:         length %u\n", state->length));
; 537  : 
; 538  :             /* get distance code */
; 539  :             for (;;) {
; 540  :                 here = state->distcode[BITS(state->distbits)];

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax+88]
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+80]
	mov	edx, DWORD PTR [ecx+edx*4]
	mov	DWORD PTR _here$[ebp], edx

; 541  :                 if ((unsigned)(here.bits) <= bits) break;

	movzx	eax, BYTE PTR _here$[ebp+1]
	cmp	eax, DWORD PTR _bits$[ebp]
	ja	SHORT $LN61@inflateBac@2
	jmp	SHORT $LN66@inflateBac@2
$LN61@inflateBac@2:

; 542  :                 PULLBYTE();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN60@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN60@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN60@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN61@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN61@inflateBac@2

; 543  :             }

	jmp	$LN67@inflateBac@2
$LN66@inflateBac@2:

; 544  :             if ((here.op & 0xf0) == 0) {

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 240				; 000000f0H
	jne	$LN41@inflateBac@2

; 545  :                 last = here;

	mov	eax, DWORD PTR _here$[ebp]
	mov	DWORD PTR _last$[ebp], eax
$LN55@inflateBac@2:

; 546  :                 for (;;) {
; 547  :                     here = state->distcode[last.val +
; 548  :                             (BITS(last.bits + last.op) >> last.bits)];

	movzx	eax, WORD PTR _last$[ebp+2]
	movzx	ecx, BYTE PTR _last$[ebp+1]
	movzx	edx, BYTE PTR _last$[ebp]
	add	ecx, edx
	mov	edx, 1
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	movzx	ecx, BYTE PTR _last$[ebp+1]
	shr	edx, cl
	add	eax, edx
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+80]
	mov	eax, DWORD PTR [edx+eax*4]
	mov	DWORD PTR _here$[ebp], eax

; 549  :                     if ((unsigned)(last.bits + here.bits) <= bits) break;

	movzx	eax, BYTE PTR _last$[ebp+1]
	movzx	ecx, BYTE PTR _here$[ebp+1]
	add	eax, ecx
	cmp	eax, DWORD PTR _bits$[ebp]
	ja	SHORT $LN49@inflateBac@2
	jmp	SHORT $LN44@inflateBac@2
$LN49@inflateBac@2:

; 550  :                     PULLBYTE();

	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN48@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN48@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN48@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN49@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN49@inflateBac@2

; 551  :                 }

	jmp	$LN55@inflateBac@2
$LN44@inflateBac@2:

; 552  :                 DROPBITS(last.bits);

	movzx	ecx, BYTE PTR _last$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _last$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN44@inflateBac@2
$LN41@inflateBac@2:

; 553  :             }
; 554  :             DROPBITS(here.bits);

	movzx	ecx, BYTE PTR _here$[ebp+1]
	mov	eax, DWORD PTR _hold$[ebp]
	shr	eax, cl
	mov	DWORD PTR _hold$[ebp], eax
	movzx	eax, BYTE PTR _here$[ebp+1]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, eax
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN41@inflateBac@2

; 555  :             if (here.op & 64) {

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 64					; 00000040H
	je	SHORT $LN38@inflateBac@2

; 556  :                 strm->msg = (char *)"invalid distance code";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BG@LBKINIKP@invalid?5distance?5code?$AA@

; 557  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 558  :                 break;

	jmp	$LN342@inflateBac@2
$LN38@inflateBac@2:

; 559  :             }
; 560  :             state->offset = (unsigned)here.val;

	movzx	eax, WORD PTR _here$[ebp+2]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+68], eax

; 561  : 
; 562  :             /* get distance extra bits, if any */
; 563  :             state->extra = (unsigned)(here.op) & 15;

	movzx	eax, BYTE PTR _here$[ebp]
	and	eax, 15					; 0000000fH
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+72], eax

; 564  :             if (state->extra != 0) {

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+72], 0
	je	$LN37@inflateBac@2
$LN33@inflateBac@2:

; 565  :                 NEEDBITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _bits$[ebp]
	cmp	ecx, DWORD PTR [eax+72]
	jae	SHORT $LN35@inflateBac@2
$LN28@inflateBac@2:
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN27@inflateBac@2
	lea	eax, DWORD PTR _next$[ebp]
	push	eax
	mov	ecx, DWORD PTR _in_desc$[ebp]
	push	ecx
	call	DWORD PTR _in$[ebp]
	add	esp, 8
	mov	DWORD PTR _have$[ebp], eax
	cmp	DWORD PTR _have$[ebp], 0
	jne	SHORT $LN27@inflateBac@2
	mov	DWORD PTR _next$[ebp], 0
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN27@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN28@inflateBac@2
	mov	eax, DWORD PTR _have$[ebp]
	sub	eax, 1
	mov	DWORD PTR _have$[ebp], eax
	mov	eax, DWORD PTR _next$[ebp]
	movzx	edx, BYTE PTR [eax]
	mov	ecx, DWORD PTR _bits$[ebp]
	shl	edx, cl
	add	edx, DWORD PTR _hold$[ebp]
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _next$[ebp]
	add	eax, 1
	mov	DWORD PTR _next$[ebp], eax
	mov	eax, DWORD PTR _bits$[ebp]
	add	eax, 8
	mov	DWORD PTR _bits$[ebp], eax
	xor	eax, eax
	jne	SHORT $LN28@inflateBac@2
	jmp	SHORT $LN33@inflateBac@2
$LN35@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN33@inflateBac@2

; 566  :                 state->offset += BITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, 1
	mov	ecx, DWORD PTR [eax+72]
	shl	edx, cl
	sub	edx, 1
	and	edx, DWORD PTR _hold$[ebp]
	mov	eax, DWORD PTR _state$[ebp]
	add	edx, DWORD PTR [eax+68]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [ecx+68], edx
$LN23@inflateBac@2:

; 567  :                 DROPBITS(state->extra);

	mov	eax, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR _hold$[ebp]
	mov	ecx, DWORD PTR [eax+72]
	shr	edx, cl
	mov	DWORD PTR _hold$[ebp], edx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _bits$[ebp]
	sub	ecx, DWORD PTR [eax+72]
	mov	DWORD PTR _bits$[ebp], ecx
	xor	eax, eax
	jne	SHORT $LN23@inflateBac@2
$LN37@inflateBac@2:

; 568  :             }
; 569  :             if (state->offset > state->wsize - (state->whave < state->wsize ?
; 570  :                                                 left : 0)) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [eax+44]
	cmp	edx, DWORD PTR [ecx+40]
	sbb	eax, eax
	and	eax, DWORD PTR _left$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [ecx+40]
	sub	edx, eax
	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+68], edx
	jbe	SHORT $LN16@inflateBac@2

; 571  :                 strm->msg = (char *)"invalid distance too far back";

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+24], OFFSET ??_C@_0BO@ECPMAOGG@invalid?5distance?5too?5far?5back?$AA@

; 572  :                 state->mode = BAD;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax], 29			; 0000001dH

; 573  :                 break;

	jmp	$LN342@inflateBac@2
$LN16@inflateBac@2:

; 574  :             }
; 575  :             Tracevv((stderr, "inflate:         distance %u\n", state->offset));
; 576  : 
; 577  :             /* copy match from window to output */
; 578  :             do {
; 579  :                 ROOM();

	cmp	DWORD PTR _left$[ebp], 0
	jne	SHORT $LN15@inflateBac@2
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+52]
	mov	DWORD PTR _put$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	mov	DWORD PTR _left$[ebp], ecx
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _left$[ebp]
	mov	DWORD PTR [eax+44], ecx
	mov	eax, DWORD PTR _left$[ebp]
	push	eax
	mov	ecx, DWORD PTR _put$[ebp]
	push	ecx
	mov	edx, DWORD PTR _out_desc$[ebp]
	push	edx
	call	DWORD PTR _out$[ebp]
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN15@inflateBac@2
	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
	jmp	$inf_leave$80416
$LN15@inflateBac@2:
	xor	eax, eax
	jne	SHORT $LN16@inflateBac@2

; 580  :                 copy = state->wsize - state->offset;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _state$[ebp]
	mov	edx, DWORD PTR [eax+40]
	sub	edx, DWORD PTR [ecx+68]
	mov	DWORD PTR _copy$[ebp], edx

; 581  :                 if (copy < left) {

	mov	eax, DWORD PTR _copy$[ebp]
	cmp	eax, DWORD PTR _left$[ebp]
	jae	SHORT $LN11@inflateBac@2

; 582  :                     from = put + copy;

	mov	eax, DWORD PTR _put$[ebp]
	add	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _from$[ebp], eax

; 583  :                     copy = left - copy;

	mov	eax, DWORD PTR _left$[ebp]
	sub	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _copy$[ebp], eax

; 584  :                 }
; 585  :                 else {

	jmp	SHORT $LN10@inflateBac@2
$LN11@inflateBac@2:

; 586  :                     from = put - state->offset;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _put$[ebp]
	sub	ecx, DWORD PTR [eax+68]
	mov	DWORD PTR _from$[ebp], ecx

; 587  :                     copy = left;

	mov	eax, DWORD PTR _left$[ebp]
	mov	DWORD PTR _copy$[ebp], eax
$LN10@inflateBac@2:

; 588  :                 }
; 589  :                 if (copy > state->length) copy = state->length;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _copy$[ebp]
	cmp	ecx, DWORD PTR [eax+64]
	jbe	SHORT $LN9@inflateBac@2
	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+64]
	mov	DWORD PTR _copy$[ebp], ecx
$LN9@inflateBac@2:

; 590  :                 state->length -= copy;

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+64]
	sub	ecx, DWORD PTR _copy$[ebp]
	mov	edx, DWORD PTR _state$[ebp]
	mov	DWORD PTR [edx+64], ecx

; 591  :                 left -= copy;

	mov	eax, DWORD PTR _left$[ebp]
	sub	eax, DWORD PTR _copy$[ebp]
	mov	DWORD PTR _left$[ebp], eax
$LN8@inflateBac@2:

; 592  :                 do {
; 593  :                     *put++ = *from++;

	mov	eax, DWORD PTR _put$[ebp]
	mov	ecx, DWORD PTR _from$[ebp]
	mov	dl, BYTE PTR [ecx]
	mov	BYTE PTR [eax], dl
	mov	eax, DWORD PTR _put$[ebp]
	add	eax, 1
	mov	DWORD PTR _put$[ebp], eax
	mov	ecx, DWORD PTR _from$[ebp]
	add	ecx, 1
	mov	DWORD PTR _from$[ebp], ecx

; 594  :                 } while (--copy);

	mov	eax, DWORD PTR _copy$[ebp]
	sub	eax, 1
	mov	DWORD PTR _copy$[ebp], eax
	jne	SHORT $LN8@inflateBac@2

; 595  :             } while (state->length != 0);

	mov	eax, DWORD PTR _state$[ebp]
	cmp	DWORD PTR [eax+64], 0
	jne	$LN16@inflateBac@2

; 596  :             break;

	jmp	SHORT $LN342@inflateBac@2
$LN5@inflateBac@2:

; 597  : 
; 598  :         case DONE:
; 599  :             /* inflate stream terminated properly -- write leftover output */
; 600  :             ret = Z_STREAM_END;

	mov	DWORD PTR _ret$[ebp], 1

; 601  :             if (left < state->wsize) {

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR _left$[ebp]
	cmp	ecx, DWORD PTR [eax+40]
	jae	SHORT $LN4@inflateBac@2

; 602  :                 if (out(out_desc, state->window, state->wsize - left))

	mov	eax, DWORD PTR _state$[ebp]
	mov	ecx, DWORD PTR [eax+40]
	sub	ecx, DWORD PTR _left$[ebp]
	push	ecx
	mov	edx, DWORD PTR _state$[ebp]
	mov	eax, DWORD PTR [edx+52]
	push	eax
	mov	ecx, DWORD PTR _out_desc$[ebp]
	push	ecx
	call	DWORD PTR _out$[ebp]
	add	esp, 12					; 0000000cH
	test	eax, eax
	je	SHORT $LN4@inflateBac@2

; 603  :                     ret = Z_BUF_ERROR;

	mov	DWORD PTR _ret$[ebp], -5		; fffffffbH
$LN4@inflateBac@2:

; 604  :             }
; 605  :             goto inf_leave;

	jmp	SHORT $inf_leave$80416
$LN2@inflateBac@2:

; 606  : 
; 607  :         case BAD:
; 608  :             ret = Z_DATA_ERROR;

	mov	DWORD PTR _ret$[ebp], -3		; fffffffdH

; 609  :             goto inf_leave;

	jmp	SHORT $inf_leave$80416
$LN1@inflateBac@2:

; 610  : 
; 611  :         default:                /* can't happen, but makes compilers happy */
; 612  :             ret = Z_STREAM_ERROR;

	mov	DWORD PTR _ret$[ebp], -2		; fffffffeH

; 613  :             goto inf_leave;

	jmp	SHORT $inf_leave$80416
$LN342@inflateBac@2:

; 614  :         }

	jmp	$LN345@inflateBac@2
$inf_leave$80416:

; 615  : 
; 616  :     /* Return unused input */
; 617  :   inf_leave:
; 618  :     strm->next_in = next;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _next$[ebp]
	mov	DWORD PTR [eax], ecx

; 619  :     strm->avail_in = have;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR _have$[ebp]
	mov	DWORD PTR [eax+4], ecx

; 620  :     return ret;

	mov	eax, DWORD PTR _ret$[ebp]
$LN348@inflateBac@2:

; 621  : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	20					; 00000014H
	npad	2
$LN353@inflateBac@2:
	DD	$LN341@inflateBac@2
	DD	$LN310@inflateBac@2
	DD	$LN272@inflateBac@2
	DD	$LN130@inflateBac@2
	DD	$LN5@inflateBac@2
	DD	$LN2@inflateBac@2
	DD	$LN1@inflateBac@2
$LN352@inflateBac@2:
	DB	0
	DB	6
	DB	1
	DB	6
	DB	6
	DB	2
	DB	6
	DB	6
	DB	6
	DB	3
	DB	6
	DB	6
	DB	6
	DB	6
	DB	6
	DB	6
	DB	6
	DB	4
	DB	5
	npad	1
$LN354@inflateBac@2:
	DD	$LN318@inflateBac@2
	DD	$LN317@inflateBac@2
	DD	$LN316@inflateBac@2
	DD	$LN315@inflateBac@2
_inflateBack@20 ENDP
; Function compile flags: /Odtp /ZI
_TEXT	ENDS
;	COMDAT _fixedtables
_TEXT	SEGMENT
_state$ = 8						; size = 4
_fixedtables PROC					; COMDAT

; 75   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 76   : #ifdef BUILDFIXED
; 77   :     static int virgin = 1;
; 78   :     static code *lenfix, *distfix;
; 79   :     static code fixed[544];
; 80   : 
; 81   :     /* build fixed huffman tables if first call (may not be thread safe) */
; 82   :     if (virgin) {
; 83   :         unsigned sym, bits;
; 84   :         static code *next;
; 85   : 
; 86   :         /* literal/length table */
; 87   :         sym = 0;
; 88   :         while (sym < 144) state->lens[sym++] = 8;
; 89   :         while (sym < 256) state->lens[sym++] = 9;
; 90   :         while (sym < 280) state->lens[sym++] = 7;
; 91   :         while (sym < 288) state->lens[sym++] = 8;
; 92   :         next = fixed;
; 93   :         lenfix = next;
; 94   :         bits = 9;
; 95   :         inflate_table(LENS, state->lens, 288, &(next), &(bits), state->work);
; 96   : 
; 97   :         /* distance table */
; 98   :         sym = 0;
; 99   :         while (sym < 32) state->lens[sym++] = 5;
; 100  :         distfix = next;
; 101  :         bits = 5;
; 102  :         inflate_table(DISTS, state->lens, 32, &(next), &(bits), state->work);
; 103  : 
; 104  :         /* do this just once */
; 105  :         virgin = 0;
; 106  :     }
; 107  : #else /* !BUILDFIXED */
; 108  : #   include "inffixed.h"
; 109  : #endif /* BUILDFIXED */
; 110  :     state->lencode = lenfix;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+76], OFFSET ?lenfix@?1??fixedtables@@9@9

; 111  :     state->lenbits = 9;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+84], 9

; 112  :     state->distcode = distfix;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+80], OFFSET ?distfix@?1??fixedtables@@9@9

; 113  :     state->distbits = 5;

	mov	eax, DWORD PTR _state$[ebp]
	mov	DWORD PTR [eax+88], 5

; 114  : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
_fixedtables ENDP
_TEXT	ENDS
PUBLIC	_inflateBackEnd@4
; Function compile flags: /Odtp /ZI
;	COMDAT _inflateBackEnd@4
_TEXT	SEGMENT
_strm$ = 8						; size = 4
_inflateBackEnd@4 PROC					; COMDAT

; 625  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 64					; 00000040H
	push	ebx
	push	esi
	push	edi

; 626  :     if (strm == Z_NULL || strm->state == Z_NULL || strm->zfree == (free_func)0)

	cmp	DWORD PTR _strm$[ebp], 0
	je	SHORT $LN1@inflateBac@3
	mov	eax, DWORD PTR _strm$[ebp]
	cmp	DWORD PTR [eax+28], 0
	je	SHORT $LN1@inflateBac@3
	mov	eax, DWORD PTR _strm$[ebp]
	cmp	DWORD PTR [eax+36], 0
	jne	SHORT $LN2@inflateBac@3
$LN1@inflateBac@3:

; 627  :         return Z_STREAM_ERROR;

	mov	eax, -2					; fffffffeH
	jmp	SHORT $LN3@inflateBac@3
$LN2@inflateBac@3:

; 628  :     ZFREE(strm, strm->state);

	mov	eax, DWORD PTR _strm$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	push	ecx
	mov	edx, DWORD PTR _strm$[ebp]
	mov	eax, DWORD PTR [edx+40]
	push	eax
	mov	ecx, DWORD PTR _strm$[ebp]
	mov	edx, DWORD PTR [ecx+36]
	call	edx
	add	esp, 8

; 629  :     strm->state = Z_NULL;

	mov	eax, DWORD PTR _strm$[ebp]
	mov	DWORD PTR [eax+28], 0

; 630  :     Tracev((stderr, "inflate: end\n"));
; 631  :     return Z_OK;

	xor	eax, eax
$LN3@inflateBac@3:

; 632  : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	4
_inflateBackEnd@4 ENDP
_TEXT	ENDS
END
